window.FINALE_ACTIONS = {
  scan: { label: 'בדוק מצב', icon: '🔎', type: 'start' },
  move: { label: 'סע לנקודה', icon: '🤖➡️', type: 'move' },
  light: { label: 'הדלק אור', icon: '💡', type: 'action' },
  streetMove: { label: 'סע לרחוב החשוך', icon: '🤖➡️', type: 'move' },
  crosswalkMove: { label: 'סע למעבר החציה', icon: '🤖➡️🚸', type: 'move' },
  checkGreenLight: { label: 'בדוק שהרמזור ירוק', icon: '🚦✅', type: 'check' },
  crossingSound: { label: 'הפעל צליל מעבר', icon: '🔊🚸', type: 'action' },
  markCanCross: { label: 'סמן שאפשר לחצות', icon: '✅🚸', type: 'check' },
  checkBrokenLamp: { label: 'בדוק איזה פנס כבוי', icon: '🔎💡', type: 'check' },
  fixLamp: { label: 'תקן את הפנס', icon: '🛠️💡', type: 'action' },
  reportLightFixed: { label: 'סמן שהרחוב מואר', icon: '✅💡', type: 'check' },
  busMessage: { label: 'הודע שהאוטובוס הגיע', icon: '📢🚌', type: 'action' },
  openBusDoor: { label: 'פתח דלת אוטובוס', icon: '🚪🚌', type: 'action' },
  guideToBus: { label: 'כוון את הילדים לעלות', icon: '👧➡️🚌', type: 'action' },
  closeWater: { label: 'סגור את המים', icon: '🚰✋', type: 'action' },
  placeWarningSign: { label: 'הצב שלט זהירות', icon: '⚠️', type: 'action' },
  markAreaSafe: { label: 'סמן שהאזור בטוח', icon: '✅🏙️', type: 'check' },
  streetLight: { label: 'הדלק את האור', icon: '💡', type: 'action' },
  markSafe: { label: 'סמן שהדרך בטוחה', icon: '✅', type: 'check' },
  quietSign: { label: 'הצג סימן שקט', icon: '🤫', type: 'action' },
  markClassCalm: { label: 'סמן שהכיתה רגועה', icon: '✅🏫', type: 'check' },
  guideKids: { label: 'כוון את הילדים', icon: '👧➡️', type: 'action' },
  puddleMove: { label: 'גש אל השלולית', icon: '🤖➡️💧', type: 'move' },
  cleanTrash: { label: 'אסוף אשפה', icon: '🧹', type: 'action' },
  findTrash: { label: 'מצא את האשפה', icon: '🔎🗑️', type: 'start' },
  photoCleanPark: { label: 'צלם את הפארק נקי', icon: '📸🌳', type: 'check' },
  bridge: { label: 'הנח גשר', icon: '🌉', type: 'action' },
  alert: { label: 'שלח הודעה', icon: '📢', type: 'action' },
  libraryMessage: { label: 'שלח הודעה: נא לשמור על שקט', icon: '📢📚', type: 'action' },
  markLibraryCalm: { label: 'סמן שהספרייה רגועה', icon: '✅📚', type: 'check' },
  quietMessage: { label: 'שלח הודעה: נא להקשיב בשקט', icon: '📢', type: 'action' },
  checkGuard: { label: 'בדוק שיש שומר', icon: '👮', type: 'check' },
  enterCode: { label: 'הכנס קוד נכון', icon: '🔢', type: 'action' },
  rainMessage: { label: 'שלח הודעה: גשם בחוץ', icon: '📢🌧️', type: 'action' },
  umbrella: { label: 'פתח מטריה', icon: '☂️', type: 'action' },
  guideInside: { label: 'כוון את הילדים פנימה', icon: '👧➡️🏫', type: 'action' },
  open: { label: 'פתח שער', icon: '🔓', type: 'action' },
  photo: { label: 'צלם הוכחה', icon: '📸', type: 'check' },
  celebrate: { label: 'חגוג', icon: '🎉', type: 'extra' }
};

window.FINALE_CONDITIONS = {
  nightAndPeople: { label: 'עכשיו לילה ויש אנשים ברחוב', icon: '🌙+🚶' },
  dayAndPeople: { label: 'עכשיו יום ויש אנשים ברחוב', icon: '☀️+🚶' },
  nightEmpty: { label: 'עכשיו לילה אבל הרחוב ריק', icon: '🌙+🏙️' },
  dayEmpty: { label: 'עכשיו יום והרחוב ריק', icon: '☀️+🏙️' },

  waterAndTurtle: { label: 'יש נחל ויש צב שמחכה', icon: '🌊+🐢' },
  waterNoTurtle: { label: 'יש נחל אבל אין צב שמחכה', icon: '🌊+➖' },
  turtleNoWater: { label: 'יש צב שמחכה אבל אין נחל', icon: '🐢+➖' },
  noWaterNoTurtle: { label: 'אין נחל ואין צב שמחכה', icon: '🏞️' },

  noiseAndClass: { label: 'יש רעש ויש שיעור פעיל', icon: '🔊+🏫' },
  noiseNoClass: { label: 'יש רעש אבל אין שיעור פעיל', icon: '🔊+➖' },
  classNoNoise: { label: 'יש שיעור פעיל אבל אין רעש', icon: '🏫+🤫' },
  quietNoClass: { label: 'אין רעש ואין שיעור פעיל', icon: '🤫+➖' },

  guardAndCode: { label: 'יש שומר ליד השער ויש קוד נכון', icon: '👮+✅' },
  guardNoCode: { label: 'יש שומר ליד השער אבל אין קוד נכון', icon: '👮+❌' },
  codeNoGuard: { label: 'יש קוד נכון אבל אין שומר ליד השער', icon: '✅+➖' },
  noGuardNoCode: { label: 'אין שומר ליד השער ואין קוד נכון', icon: '➖+❌' },

  rainAndKids: { label: 'יורד גשם ויש ילדים בחוץ', icon: '🌧️+👧' },
  rainNoKids: { label: 'יורד גשם אבל אין ילדים בחוץ', icon: '🌧️+➖' },
  kidsNoRain: { label: 'יש ילדים בחוץ אבל לא יורד גשם', icon: '👧+☀️' },
  noRainNoKids: { label: 'לא יורד גשם ואין ילדים בחוץ', icon: '☀️+➖' },

  trashAndPark: { label: 'יש אשפה והפארק פתוח', icon: '🗑️+🌳' },
  trashClosedPark: { label: 'יש אשפה אבל הפארק סגור', icon: '🗑️+⛔' },
  cleanOpenPark: { label: 'הפארק פתוח אבל אין אשפה', icon: '🌳+✨' },
  cleanClosedPark: { label: 'אין אשפה והפארק סגור', icon: '✨+⛔' },

  kidsAndGreenLight: { label: 'יש ילדים ליד המעבר והרמזור ירוק להולכי רגל', icon: '👧+🚦' },
  kidsAndRedLight: { label: 'יש ילדים ליד המעבר אבל הרמזור אדום', icon: '👧+🔴' },
  greenLightNoKids: { label: 'הרמזור ירוק אבל אין ילדים ליד המעבר', icon: '🚦+➖' },
  noKidsRedLight: { label: 'אין ילדים והרמזור אדום', icon: '➖+🔴' },

  puddleAndKids: { label: 'יש שלולית גדולה ויש ילדים שצריכים לעבור', icon: '💧+👧' },
  puddleNoKids: { label: 'יש שלולית גדולה אבל אין ילדים', icon: '💧+➖' },
  kidsNoPuddle: { label: 'יש ילדים אבל אין שלולית גדולה', icon: '👧+➖' },
  noPuddleNoKids: { label: 'אין שלולית ואין ילדים', icon: '✅' },

  libraryNoiseAndActivity: { label: 'יש רעש ויש פעילות בספרייה', icon: '🔊+📚' },
  libraryNoiseNoActivity: { label: 'יש רעש אבל אין פעילות בספרייה', icon: '🔊+➖' },
  libraryActivityNoNoise: { label: 'יש פעילות בספרייה אבל שקט', icon: '📚+🤫' },
  libraryQuietNoActivity: { label: 'שקט ואין פעילות בספרייה', icon: '🤫+➖' },

  nightAndBrokenLamp: { label: 'עכשיו לילה ויש פנס כבוי ברחוב', icon: '🌙+💡' },
  nightNoBrokenLamp: { label: 'עכשיו לילה אבל כל הפנסים דולקים', icon: '🌙+✨' },
  dayAndBrokenLamp: { label: 'עכשיו יום ויש פנס כבוי ברחוב', icon: '☀️+💡' },
  dayNoBrokenLamp: { label: 'עכשיו יום וכל הפנסים דולקים', icon: '☀️+✨' },

  kidsAndBusArrived: { label: 'יש ילדים בתחנה והאוטובוס הגיע', icon: '👧+🚌' },
  kidsNoBus: { label: 'יש ילדים בתחנה אבל האוטובוס עוד לא הגיע', icon: '👧+➖' },
  busNoKids: { label: 'האוטובוס הגיע אבל אין ילדים בתחנה', icon: '🚌+➖' },
  noKidsNoBus: { label: 'אין ילדים בתחנה והאוטובוס עוד לא הגיע', icon: '➖+➖' },

  finishEventAndLeak: { label: 'יש אירוע סיום בכיכר ויש נזילה ליד האנשים', icon: '🏁+💧' },
  finishEventNoLeak: { label: 'יש אירוע סיום בכיכר אבל אין נזילה', icon: '🏁+✅' },
  leakNoFinishEvent: { label: 'יש נזילה אבל אין אירוע סיום בכיכר', icon: '💧+➖' },
  noEventNoLeak: { label: 'אין אירוע סיום ואין נזילה', icon: '➖+✅' }
};
window.FINALE_MISSIONS = [
  {
    id: 1,
    emoji: '🌙',
    title: 'הרחוב החשוך',
    district: 'רחוב העיר',
    goal: 'לעזור לאנשים ללכת בבטחה ברחוב חשוך.',
    condition: 'nightAndPeople',
    conditionOptions: ['dayAndPeople', 'nightAndPeople', 'nightEmpty', 'dayEmpty'],
    correctActions: ['streetMove', 'streetLight', 'markSafe'],
    distractor: 'celebrate',
    explanation: 'כי היא פועלת רק בלילה כשיש אנשים ברחוב, ואז מדליקה אור לפני שמסמנים שהדרך בטוחה.',
    hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה סיסי צריכה לעשות כדי שהדרך תהיה בטוחה, ומה רק נשמע נחמד אבל לא באמת עוזר עכשיו.',
    learningNote: 'זו משימת שילוב: תנאי “וגם” מוביל לרצף פעולות קצר.'
  },
  {
    id: 2,
    emoji: '🐢',
    title: 'הצב ליד הנחל',
    district: 'פארק המים',
    goal: 'יש נחל בדרך, והצב צריך לעבור לצד השני בבטחה.',
    condition: 'waterAndTurtle',
    conditionOptions: ['waterNoTurtle', 'turtleNoWater', 'waterAndTurtle', 'noWaterNoTurtle'],
    correctActions: ['move', 'bridge', 'markSafe'],
    distractor: 'light',
    explanation: 'כי היא פועלת רק כשיש נחל וצב שצריך לעבור, ואז מניחה גשר לפני שמסמנים שהמעבר בטוח.',
    hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר לעבור בבטחה, ומה מתאים אולי לסיפור אחר אבל לא לבעיה הזאת.',
    learningNote: 'דיבוג: פעולה יכולה להיות נכונה במקום אחר אבל מיותרת במשימה הזו.'
  },
  {
    id: 3,
    emoji: '🏫',
    title: 'כיתה רועשת מדי',
    district: 'בית הספר',
    goal: 'לעזור לכיתה לחזור לעבודה רגועה.',
    condition: 'noiseAndClass',
    conditionOptions: ['classNoNoise', 'quietNoClass', 'noiseAndClass', 'noiseNoClass'],
    correctActions: ['quietMessage', 'quietSign', 'markClassCalm'],
    distractor: 'bridge',
    explanation: 'כי היא פועלת רק כשיש כיתה ורעש, ואז מזכירה לשמור על שקט לפני שמסמנים שהכיתה רגועה.',
    hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר לכיתה לחזור לשקט, ומה לא באמת קשור ללמידה רגועה.',
    learningNote: 'לפעמים פעולה היא הודעה ולא תנועה פיזית. גם זה פלט של מערכת חכמה.'
  },
  {
    id: 4,
    emoji: '🏫',
    title: 'שער בית הספר',
    district: 'כניסת בית הספר',
    goal: 'סיסי עוזרת לפתוח את שער בית הספר רק כשיש שומר ליד השער וקוד נכון.',
    condition: 'guardAndCode',
    conditionOptions: ['guardNoCode', 'guardAndCode', 'noGuardNoCode', 'codeNoGuard'],
    correctActions: ['checkGuard', 'enterCode', 'open'],
    distractor: 'celebrate',
    explanation: 'כי היא פועלת רק כשיש שומר וקוד נכון, ואז בודקת ומכניסה קוד לפני שפותחים את השער.',
    hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו איזו פעולה מתאימה לכניסה לבית ספר, ומה עלול להיות מיותר או לא בטוח.',
    learningNote: 'תנאי “וגם” עוזר למנוע פעולה בזמן לא נכון.'
  },
  {
    id: 5,
    emoji: '🌧️',
    title: 'גשם בהפסקה',
    district: 'חצר בית הספר',
    goal: 'להזהיר ילדים בחוץ כשמתחיל גשם.',
    condition: 'rainAndKids',
    conditionOptions: ['kidsNoRain', 'rainNoKids', 'rainAndKids', 'noRainNoKids'],
    correctActions: ['rainMessage', 'umbrella', 'guideInside'],
    distractor: 'light',
    explanation: 'כי היא פועלת רק כשיש גשם וילדים בחוץ, ואז מגינה עליהם לפני שמכוונים אותם פנימה.',
    hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר לילדים להגיע למקום בטוח, ומה לא קשור לגשם בחצר.',
    learningNote: 'אותו רעיון תכנותי יכול לעבוד בסיפורים שונים: תנאי, פעולה, בדיקה.'
  },
  {
    id: 6,
    emoji: '🌳',
    title: 'הפארק צריך ניקיון',
    district: 'פארק העיר',
    goal: 'בפארק יש אשפה, וסיסי צריכה לעזור לנקות אותו.',
    condition: 'trashAndPark',
    conditionOptions: ['cleanOpenPark', 'trashAndPark', 'trashClosedPark', 'cleanClosedPark'],
    correctActions: ['findTrash', 'cleanTrash', 'photoCleanPark'],
    distractor: 'light',
    explanation: 'כי היא פועלת רק כשהפארק פתוח ויש אשפה, ואז מנקה לפני שמתעדים שהפארק נקי.',
    hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה באמת מטפל בלכלוך, ומה לא עוזר להפוך את הפארק לנקי.',
    learningNote: 'שיעור שיא: הילדים מחברים תנאים, רצף, פעולה מתאימה ודיבוג.'
  }
];

window.FINALE_MISSIONS.push(
  { id: 7, emoji: '🚦', title: 'מעבר חציה עמוס', district: 'רחוב בית הספר', goal: 'יש הרבה ילדים ליד מעבר החציה, וסיסי צריכה לעזור להם לחצות בבטחה.', condition: 'kidsAndGreenLight', conditionOptions: ['kidsAndRedLight', 'greenLightNoKids', 'kidsAndGreenLight', 'noKidsRedLight'], correctActions: ['checkGreenLight','crossingSound','markCanCross'], distractor: 'bridge', explanation: 'כי היא פועלת רק כשהרמזור ירוק ויש ילדים, ואז נותנת סימן לפני שמסמנים שאפשר לחצות.', hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר לילדים לדעת מתי לחצות, ומה לא פותר בעיית חציה.', learningNote: 'תנאי נכון מוביל לפעולה בטוחה ומתאימה.' },
  { id: 8, emoji: '🌉', title: 'גשרון אחרי גשם', district: 'גינת העיר', goal: 'לעזור לילדים לעבור שלולית גדולה.', condition: 'puddleAndKids', conditionOptions: ['puddleNoKids', 'puddleAndKids', 'noPuddleNoKids', 'kidsNoPuddle'], correctActions: ['puddleMove','bridge','guideKids'], distractor: 'open', explanation: 'כי היא פועלת רק כשיש שלולית וילדים, ואז מניחה גשרון לפני שמכוונים אותם לעבור בבטחה.', hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר לעבור מעל מכשול בדרך, ומה לא פותר את הבעיה הזאת.', learningNote: 'דיבוג: פעולה טובה במקום אחד יכולה להיות לא מתאימה במקום אחר.' },
  { id: 9, emoji: '📚', title: 'שעת סיפור בספרייה', district: 'ספרייה עירונית', goal: 'בספרייה יש שעת סיפור, ויש רעש שמפריע לילדים להקשיב. סיסי צריכה להזכיר לכולם לשמור על שקט בעדינות.', condition: 'libraryNoiseAndActivity', conditionOptions: ['libraryActivityNoNoise', 'libraryNoiseNoActivity', 'libraryNoiseAndActivity', 'libraryQuietNoActivity'], correctActions: ['libraryMessage','quietSign','markLibraryCalm'], distractor: 'light', explanation: 'כי היא פועלת רק כשיש פעילות ורעש בספרייה, ואז מזכירה שקט לפני שמסמנים שהספרייה רגועה.', hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר לילדים להקשיב בשקט, ומה לא קשור לפעילות בספרייה.', learningNote: 'פלט של מערכת יכול להיות גם הודעה שמכוונת אנשים לפעולה רגועה ונכונה.' },
  { id: 10, emoji: '💡', title: 'פנס רחוב כבוי', district: 'מרכז העיר', goal: 'בלילה פנס אחד ברחוב כבוי, וסיסי צריכה לעזור להחזיר אור לרחוב.', condition: 'nightAndBrokenLamp', conditionOptions: ['dayAndBrokenLamp', 'nightNoBrokenLamp', 'nightAndBrokenLamp', 'dayNoBrokenLamp'], correctActions: ['checkBrokenLamp','fixLamp','reportLightFixed'], actionOptions: ['fixLamp','bridge','reportLightFixed','checkBrokenLamp'], distractor: 'bridge', explanation: 'כי היא פועלת רק בלילה כשיש פנס כבוי, ואז מתקנת אותו לפני שמסמנים שהרחוב מואר.', hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר להחזיר אור לרחוב, ומה מתאים אולי למכשול בדרך.', learningNote: 'תנאי וגם עוזר לבצע תיקון רק בזמן ובמקום שבהם באמת צריך אותו.' },
  { id: 11, emoji: '🚌', title: 'תחנת האוטובוס', district: 'תחנה חכמה', goal: 'ילדים מחכים בתחנה, והאוטובוס הגיע. סיסי צריכה לעזור להם לעלות בבטחה.', condition: 'kidsAndBusArrived', conditionOptions: ['kidsNoBus', 'busNoKids', 'kidsAndBusArrived', 'noKidsNoBus'], correctActions: ['busMessage','openBusDoor','guideToBus'], actionOptions: ['guideToBus','busMessage','bridge','openBusDoor'], distractor: 'bridge', explanation: 'כי היא פועלת רק כשהאוטובוס הגיע ויש ילדים בתחנה, ואז פותחת דלת לפני שמכוונים אותם לעלות.', hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה עוזר לילדים לעלות לאוטובוס בבטחה, ומה מתאים למכשול בדרך ולא לתחנה.', learningNote: 'מערכת חכמה עוזרת לאנשים בזמן הנכון ורק כשהמצב מתאים.' },
  { id: 12, emoji: '🏁', title: 'אירוע הסיום בכיכר', district: 'כיכר העיר', goal: 'בכיכר העיר מתקיים אירוע סיום, ויש נזילה ליד המקום שבו אנשים עוברים. סיסי צריכה לעצור את המים ולשמור שהאירוע ימשיך בבטחה.', condition: 'finishEventAndLeak', conditionOptions: ['finishEventNoLeak', 'leakNoFinishEvent', 'finishEventAndLeak', 'noEventNoLeak'], correctActions: ['placeWarningSign','closeWater','markAreaSafe'], actionOptions: ['markAreaSafe','celebrate','closeWater','placeWarningSign'], distractor: 'celebrate', explanation: 'כי היא פועלת רק כשיש אירוע ונזילה, ואז מזהירה וסוגרת את המים לפני שמסמנים שהאזור בטוח.', hint: 'רמז: חפשו מצב שבו שני הדברים נכונים. אחר כך חשבו מה שומר על האנשים ומה עוצר את הבעיה, ומה רק משמח אבל לא פותר את הנזילה.', learningNote: 'סיום הקורס: תנאי נכון, רצף פעולות, והסבר למה הפעולה מתאימה.' }
);