const opt = (id, label, emoji, why) => ({ id, label, emoji, why });
const choice = (prompt, hint, answer, options) => ({ prompt, hint, answer, options });
const pat = (prompt, sequence, answer, options, why) => ({ prompt, sequence, answer, options, why });

const O = {
  fox: opt('fox','שועל','🦊','נכון! הרמזים מתאימים לשועל של היער.'),
  bee: opt('bee','דבורה','🐝','נכון! זמזום ופרחים מובילים לדבורה.'),
  snail: opt('snail','חילזון','🐌','נכון! שביל רירי הוא סימן של חילזון.'),
  bird: opt('bird','ציפור','🐦','נכון! נוצה וציוץ מובילים לציפור.'),
  red: opt('red','אדום','🔴','נכון! בחרנו לפי הצבע שרואים.'),
  blue: opt('blue','כחול','🔵','נכון! זה הסימן הכחול במחברת.'),
  dots: opt('dots','עם נקודות','🔘','נכון! הדוגמה עם הנקודות היא הרמז.'),
  stripes: opt('stripes','עם פסים','🟰','נכון! פסים הם מאפיין שאפשר למיין לפיו.'),
  big: opt('big','גדול','⬆️','נכון! זה שייך לקבוצת הגדולים.'),
  small: opt('small','קטן','⬇️','נכון! זה שייך לקבוצת הקטנים.'),
  dry: opt('dry','יבש','🏜️','נכון! זה הסימן של יובש.'),
  wet: opt('wet','רטוב','💧','נכון! זה הסימן של רטיבות.'),
  safe: opt('safe','מקום בטוח','🛡️','נכון! קודם בודקים שהמקום בטוח.'),
  twigs: opt('twigs','לאסוף זרדים','🪵','נכון! זרדים הם חומר הבנייה של הקן.'),
  weave: opt('weave','לסדר קן','🪺','נכון! עכשיו מסדרים את הזרדים לצורה של קן.'),
  soft: opt('soft','להוסיף עלים רכים','🍃','נכון! גוזלים צריכים שכבה רכה.'),
  remove: opt('remove','להוציא קוץ','🧹','נכון! קוץ חד הוא סכנה שצריך להסיר.'),
  waitBird: opt('waitBird','לחכות לאמא ציפור','🐦','נכון! לפעמים האלגוריתם צריך לעצור ולחכות.'),
  acorn: opt('acorn','בלוט','🌰','נכון! זה הזרע שנראה כמו בלוט.'),
  maple: opt('maple','זרע כנף','🍁','נכון! לזרע כנף יש צורה שעפה ברוח.'),
  berry: opt('berry','גרגר יער','🫐','נכון! זה שייך לקבוצת הגרגרים.'),
  cone: opt('cone','אצטרובל','🌲','נכון! אצטרובל שייך לעצי מחט.'),
  owl: opt('owl','ינשוף','🦉','נכון! ינשוף פעיל בלילה.'),
  bat: opt('bat','עטלף','🦇','נכון! עטלף עף בלילה.'),
  firefly: opt('firefly','גחלילית','✨','נכון! גחלילית מאירה בחושך.'),
  hedgehog: opt('hedgehog','קיפוד','🦔','נכון! קיפוד יכול להסתובב בלילה.'),
  carry: opt('carry','לסחוב פירור','🍞','נכון! הנמלה לוקחת פירור לשיירה.'),
  follow: opt('follow','ללכת אחרי הריח','👃','נכון! השיירה עוקבת אחרי סימן ריח.'),
  repeat: opt('repeat','לחזור בלולאה','🔁','נכון! פעולה שחוזרת הרבה פעמים הופכת ללולאה.'),
  rest: opt('rest','לעצור בתחנה','🛑','נכון! לפעמים צריך עצירה לפני המשך.'),
  right: opt('right','ימינה','➡️','נכון! זה הצעד ימינה בשביל.'),
  up: opt('up','למעלה','⬆️','נכון! זה הצעד למעלה במפה.'),
  bridge: opt('bridge','לעבור בגשר','🌉','נכון! הגשר עוזר לחצות את הנחל.'),
  avoid: opt('avoid','לעקוף מכשול','🚧','נכון! מתכננים מסלול שלא נתקע.'),
  water: opt('water','להשקות','💧','נכון! כשהאדמה יבשה משקים.'),
  shade: opt('shade','לעשות צל','🌳','נכון! צל עוזר כשחם מדי.'),
  openGate: opt('openGate','לפתוח שער מים','🚰','נכון! פותחים מים רק כשהנחל צריך.'),
  closeGate: opt('closeGate','לסגור שער מים','🔒','נכון! אם יש מספיק מים, סוגרים כדי לא להציף.'),
  spotted: opt('spotted','פטרייה מנוקדת','🍄','נכון! צריך גם צבע וגם נקודות.'),
  plain: opt('plain','פטרייה חלקה','⚪','נכון! זו פטרייה בלי נקודות.'),
  tall: opt('tall','פטרייה גבוהה','📏','נכון! הגובה הוא המאפיין.'),
  tinyMush: opt('tinyMush','פטרייה קטנה','🔍','נכון! היא שייכת לקבוצת הקטנות.'),
  slow: opt('slow','לאט','🐢','נכון! הצב מתקדם לאט.'),
  fast: opt('fast','מהר','🐇','נכון! הארנב קופץ מהר.'),
  wait: opt('wait','לחכות רגע','⏳','נכון! כשמשהו איטי, האלגוריתם מחכה.'),
  compare: opt('compare','להשוות זמנים','⏱️','נכון! משווים כדי להבין מי הגיע קודם.'),
  ask: opt('ask','לשאול שאלה','❓','נכון! עץ החלטות מתחיל בשאלה.'),
  branch: opt('branch','לבחור ענף','🌿','נכון! כל תשובה מובילה לענף אחר.'),
  leaf: opt('leaf','להגיע לעלה תשובה','🍂','נכון! בסוף העץ מגיעים להחלטה.'),
  retry: opt('retry','לנסות שוב','🔄','נכון! אם התוצאה לא טובה, חוזרים ובודקים.'),
  test: opt('test','לעשות ניסוי','🧪','נכון! משנים דבר אחד ובודקים מה קרה.'),
  note: opt('note','לרשום במחברת','📒','נכון! חוקרת טובה רושמת תצפית.'),
  fix: opt('fix','לתקן את הכלל','🛠️','נכון! דיבוג הוא תיקון כלל שלא עבד.'),
  protect: opt('protect','להגן על השמורה','🛡️','נכון! המטרה היא לשמור על הטבע.'),
};

function tasksFrom(defs) { return defs.map(([p,h,a,ops]) => choice(p,h,a,ops)); }
function patternTasks(topic, a, b, c, names='') { return [
  pat(`לומי מסדרת ${topic}. מה בא עכשיו?`, [a,b,a,b,'?'], a, [a,b,c], `הדפוס חוזר אחד־אחד ${names}.`),
  pat(`במחברת של לומי יש רצף ${topic}. מה חסר?`, [a,a,b,a,a,'?'], b, [a,b,c], 'שני פריטים ואז פריט אחר.'),
  pat(`איזה סימן ממשיך את ${topic}?`, [a,b,c,a,b,'?'], c, [a,b,c], 'הרצף חוזר בשלשות.'),
  pat(`לומי רוצה שהשביל יישאר מסודר. מה הסיום?`, [b,a,b,a,b,'?'], a, [a,b,c], 'כל פעם מתחלפים.'),
  pat(`מה חסר אחרי שתי חזרות ${topic}?`, [c,c,a,c,c,'?'], a, [a,b,c], 'שניים ואז אחד.'),
  pat(`איזה פריט שומר על הלולאה של לומי?`, [a,b,b,a,b,'?'], b, [a,b,c], 'אחד ואז שניים.'),
  pat(`לומי מנחשת את הצעד הבא ${topic}.`, [a,c,a,c,'?'], a, [a,b,c], 'יש קפיצה בין שני סימנים.'),
  pat(`איזה סימן חסר במחברת?`, [b,c,c,b,c,'?'], c, [a,b,c], 'אחד ואז שניים.'),
  pat(`מצאו חוקיות ב${topic}.`, [a,a,a,b,a,a,a,'?'], b, [a,b,c], 'שלושה ואז סימן מיוחד.'),
  pat(`מה יקרה בתחנה הבאה של לומי?`, [c,b,a,c,b,'?'], a, [a,b,c], 'אותו סדר חוזר.'),
  pat(`בחרו סוף נכון ל${topic}.`, [b,b,c,b,b,'?'], c, [a,b,c], 'שתי חזרות ואז סימן אחר.'),
  pat(`איזה פריט ישמור על הדפוס האחרון?`, [a,b,c,c,a,b,'?'], c, [a,b,c], 'אחד, אחד, שניים.'),
];}

function tracksTasks(){return tasksFrom([
 ['לומי מצאה עקבות קטנות וזנב ארוך ליד הנחל. מי עבר שם?','קוראים רמזים כמו בלשים קטנים.','fox',[O.fox,O.bee,O.snail,O.bird]],
 ['יש זמזום ליד פרח צהוב. מי השאירה את הרמז?','הרמז הוא צליל ופרח.','bee',[O.fox,O.bee,O.snail,O.bird]],
 ['על העלה יש שביל מבריק ורירי. מי טייל לאט?','מחפשים חיה שמשאירה שביל.','snail',[O.fox,O.bee,O.snail,O.bird]],
 ['לומי מצאה נוצה קטנה על השביל. מי כנראה הייתה שם?','נוצה שייכת לחיה עם כנפיים.','bird',[O.fox,O.bee,O.snail,O.bird]],
 ['מי לא שייכת לקבוצת “עפים”?','בודקים לפי תכונה אחת: עף או לא עף.','snail',[O.bee,O.bird,O.snail,O.fox]],
 ['מי מתאימה לקבוצת “פעילה בלילה”?','שועל יוצא לחפש אוכל בלילה.','fox',[O.fox,O.bee,O.snail,O.bird]],
 ['יש פרח, אבקה וזמזום. איזה רמז הכי חזק?','שלושה סימנים מובילים לאותה חיה.','bee',[O.bee,O.fox,O.snail,O.bird]],
 ['יש קונכייה קטנה ושביל על האדמה. מי זו?','קונכייה היא רמז מצוין.','snail',[O.snail,O.bee,O.fox,O.bird]],
 ['לומי שומעת ציוץ מעל העץ. מי מסתתרת?','הצליל הוא ציוץ.','bird',[O.bird,O.snail,O.fox,O.bee]],
 ['אם יש זנב ארוך וגם עקבות על האדמה — מי מתאים?','שני תנאים יחד.','fox',[O.fox,O.bird,O.bee,O.snail]],
 ['אם יש כנפיים וגם זמזום — מי מתאים?','לא כל כנפיים הן ציפור; זמזום משנה.','bee',[O.bee,O.bird,O.fox,O.snail]],
 ['לומי מסכמת: שביל רירי ⇒ ?','זה כלל אם־אז מתוך הטבע.','snail',[O.snail,O.fox,O.bee,O.bird]],
]);}
function butterflyTasks(){return tasksFrom([
 ['פרפר עם כנפיים כחולות נחת על פרח. לאיזו קבוצה הוא שייך?','ממיינים לפי צבע.','blue',[O.blue,O.red,O.dots,O.stripes]],
 ['פרפר אדום עף ליד לומי. באיזה סל מדבקות נשים אותו?','הצבע הוא הרמז.','red',[O.red,O.blue,O.dots,O.stripes]],
 ['על הכנפיים יש נקודות קטנות. מה המאפיין?','מסתכלים על הדוגמה.','dots',[O.dots,O.stripes,O.red,O.blue]],
 ['כנפיים עם פסים ארוכים. איזו תווית מתאימה?','הדוגמה היא פסים.','stripes',[O.stripes,O.dots,O.blue,O.red]],
 ['לומי מחפשת “פרפר כחול עם נקודות”. מה קודם בודקים?','בודקים צבע ואז דוגמה.','blue',[O.blue,O.red,O.big,O.small]],
 ['מי יוצא דופן: כחול, כחול, כחול, אדום?','מחפשים מי לא בקבוצה.','red',[O.red,O.blue,O.dots,O.stripes]],
 ['הפרפר גדול וכחול. לפי איזה מאפיין נמיין אם הסל כתוב “גודל”?','הסל מבקש גודל, לא צבע.','big',[O.big,O.small,O.blue,O.red]],
 ['פרפר קטן עם פסים. אם הכלל הוא “בחר קטנים”, מה בוחרים?','הכלל קובע את התכונה החשובה.','small',[O.small,O.big,O.stripes,O.dots]],
 ['לומי רואה שני פרפרים עם פסים. מה המשותף?','הדוגמה חוזרת.','stripes',[O.stripes,O.dots,O.red,O.blue]],
 ['אם יש נקודות וגם צבע אדום — איזה תנאי מתקיים ראשון?','מתחילים מתכונה שקל לראות.','dots',[O.dots,O.stripes,O.big,O.small]],
 ['פרפר בלי נקודות ובלי פסים. איזו דוגמה אין לו?','בודקים מה חסר.','dots',[O.dots,O.stripes,O.blue,O.red]],
 ['לומי מסכמת טבלה: צבע, גודל, דוגמה. מה זו מיומנות?','זה מיון לפי תכונות.','blue',[O.blue,O.big,O.dots,O.stripes]],
]);}
function nestTasks(){return tasksFrom([
 ['לומי עוזרת לציפור לבנות קן. מה הצעד הראשון?','לפני שבונים, בודקים מקום בטוח.','safe',[O.safe,O.twigs,O.weave,O.soft]],
 ['המקום בטוח. מה צריך לפני שמסדרים קן?','אי אפשר לסדר חומרים לפני שאוספים אותם.','twigs',[O.twigs,O.weave,O.soft,O.remove]],
 ['יש זרדים ועלים. מה בונה מהם צורה של קן?','עכשיו הופכים חומרים למבנה.','weave',[O.weave,O.twigs,O.safe,O.waitBird]],
 ['הקן קשה מדי לגוזלים. מה מוסיפים?','גוזלים צריכים שכבה רכה.','soft',[O.soft,O.remove,O.safe,O.twigs]],
 ['לומי מצאה קוץ חד בתוך הקן. מה הדיבוג?','מסירים סכנה מהקן.','remove',[O.remove,O.soft,O.waitBird,O.weave]],
 ['הסדר כתוב: לסדר קן → לאסוף זרדים. מה צריך לקרות קודם?','הסדר הפוך.','twigs',[O.twigs,O.weave,O.safe,O.soft]],
 ['הגוזל מצייץ והקן מוכן. למי מחכים?','לא כל בעיה פותרים בבנייה.','waitBird',[O.waitBird,O.twigs,O.remove,O.safe]],
 ['ענף בקן רופף. איזו פעולה מתקנת?','מחזקים את המבנה.','weave',[O.weave,O.soft,O.remove,O.waitBird]],
 ['חסרים חומרים לקן. מה עושים?','חסר קלט לבנייה.','twigs',[O.twigs,O.safe,O.soft,O.remove]],
 ['הקן ליד שביל של חתול. מה קודם?','בטיחות לפני בנייה.','safe',[O.safe,O.twigs,O.weave,O.waitBird]],
 ['לומי מוסיפה עלה רך ועוד עלה רך ועוד עלה רך. איזו פעולה חוזרת?','זו חזרה נעימה בקן.','soft',[O.soft,O.repeat,O.remove,O.safe]],
 ['בסוף יש מקום בטוח, זרדים, קן ועלים רכים. מה הצלחנו לבנות?','רצף פעולות יצר תוצאה.','weave',[O.weave,O.twigs,O.safe,O.remove]],
]);}
function seedTasks(){return tasksFrom([
 ['לומי מצאה זרע עגול וחום מתחת לאלון. מה זה?','הצורה מזכירה כובע קטן.','acorn',[O.acorn,O.maple,O.berry,O.cone]],
 ['זרע עם כנף קטנה מסתובב ברוח. מה שמו במחברת?','הוא כאילו טס.','maple',[O.maple,O.acorn,O.berry,O.cone]],
 ['גרגרים כחולים קטנים בקערה. לאיזו קבוצה?','ממיינים לפי סוג הפרי.','berry',[O.berry,O.cone,O.acorn,O.maple]],
 ['משהו קשה עם קשקשים ליד עץ אורן. מה זה?','זה בא מעץ מחט.','cone',[O.cone,O.acorn,O.maple,O.berry]],
 ['מה שייך לקבוצת “עף ברוח”?','בודקים איך הזרע נע.','maple',[O.maple,O.acorn,O.cone,O.berry]],
 ['מה שייך לקבוצת “עגול וכבד”?','הוא נופל ליד העץ.','acorn',[O.acorn,O.maple,O.berry,O.cone]],
 ['לומי סופרת 3 בלוטים ועוד 1. איזה סוג היא סופרת?','השם חשוב בטבלת הדאטה.','acorn',[O.acorn,O.berry,O.maple,O.cone]],
 ['אם הזרע רך ומתוק, איזו קבוצה מתאימה?','לא כל זרע קשה.','berry',[O.berry,O.cone,O.maple,O.acorn]],
 ['מי יוצא דופן: בלוט, בלוט, בלוט, אצטרובל?','מחפשים פריט אחר בקבוצה.','cone',[O.cone,O.acorn,O.maple,O.berry]],
 ['מה כדאי לרשום קודם בטבלת לומי?','שם הקבוצה לפני המספר.','acorn',[O.acorn,O.big,O.small,O.wet]],
 ['זרע כנף עף רחוק. מה עזר לו?','הרוח מפזרת אותו.','maple',[O.maple,O.cone,O.berry,O.acorn]],
 ['לומי רוצה למיין לפי “קשה/רך”. מה יכול להיות רך?','גרגר יער רך יותר מבלוט.','berry',[O.berry,O.acorn,O.cone,O.maple]],
]);}
function nightTasks(){return tasksFrom([
 ['בלילה לומי שומעת הו־הו מהעץ. מי ער?','קול לילה מוכר.','owl',[O.owl,O.bat,O.firefly,O.hedgehog]],
 ['צל קטן עף בלי ציוץ. מי זה יכול להיות?','עטלף עף בלילה.','bat',[O.bat,O.owl,O.firefly,O.hedgehog]],
 ['נקודה מאירה מעל הדשא. מי מדליקה אור קטן?','יש חיה שמנצנצת.','firefly',[O.firefly,O.owl,O.bat,O.hedgehog]],
 ['רשרוש ליד העלים וקוצים קטנים. מי הולך שם?','קוצים הם רמז.','hedgehog',[O.hedgehog,O.firefly,O.bat,O.owl]],
 ['אם חשוך מאוד — מה לומי עושה קודם?','חוקרת לא רצה; היא בודקת.','ask',[O.ask,O.branch,O.leaf,O.retry]],
 ['אם יש קול מהעץ — לאן מסתכלים?','המקור כנראה למעלה.','branch',[O.branch,O.leaf,O.ask,O.retry]],
 ['אם יש אור קטן וזז — מי מתאים?','האור הוא רמז לגחלילית.','firefly',[O.firefly,O.owl,O.bat,O.hedgehog]],
 ['אם יש כנפיים ואין ציוץ — מי סביר?','כנפיים בלילה בלי ציוץ.','bat',[O.bat,O.owl,O.firefly,O.hedgehog]],
 ['לומי לא בטוחה. מה עושים באלגוריתם חקירה?','מנסים שוב עם רמז חדש.','retry',[O.retry,O.leaf,O.branch,O.ask]],
 ['אם שומעים הו־הו וגם רואים עיניים גדולות — מי זה?','שני רמזים יחד.','owl',[O.owl,O.bat,O.firefly,O.hedgehog]],
 ['מי לא מאיר בלילה?','מחפשים מי בלי אור.','hedgehog',[O.hedgehog,O.firefly,O.owl,O.bat]],
 ['בסוף לומי רושמת תצפית. מה היא עושה?','מחברת המסע שומרת נתונים.','note',[O.note,O.retry,O.ask,O.branch]],
]);}
function antTasks(){return tasksFrom([
 ['נמלה מצאה פירור. מה הפעולה הראשונה בשיירה?','המשימה היא להביא אוכל לקן.','carry',[O.carry,O.follow,O.repeat,O.rest]],
 ['השיירה הולכת לפי ריח על השביל. מה הכלל?','נמלים עוקבות אחרי סימן.','follow',[O.follow,O.carry,O.rest,O.repeat]],
 ['אותו צעד חוזר: ללכת, ללכת, ללכת. מה מתאים?','חזרה הופכת ללולאה.','repeat',[O.repeat,O.carry,O.follow,O.rest]],
 ['אם נמלה עייפה בתחנה — מה כדאי?','לפעמים עוצרים ואז ממשיכים.','rest',[O.rest,O.repeat,O.carry,O.follow]],
 ['אם יש 5 פירורים, מה חוזר 5 פעמים?','סוחבים פירור שוב ושוב.','carry',[O.carry,O.repeat,O.follow,O.rest]],
 ['אם הריח נעלם — מה צריכה השיירה לעשות?','קודם מוצאים סימן מחדש.','follow',[O.follow,O.rest,O.carry,O.repeat]],
 ['לומי רוצה לקצר “קחי פירור” 6 פעמים. מה הרעיון?','זה בדיוק לולאה.','repeat',[O.repeat,O.carry,O.follow,O.rest]],
 ['אם יש אבן בדרך, השיירה עוצרת רגע. מה הפעולה?','עצירה היא חלק מהמסלול.','rest',[O.rest,O.follow,O.carry,O.repeat]],
 ['מה הפלט של השיירה בסוף?','האוכל מגיע לקן.','carry',[O.carry,O.follow,O.repeat,O.rest]],
 ['איזו פעולה שייכת יותר לנמלים מאשר לציפורים?', 'נמלים עוקבות אחרי ריח.', 'follow', [O.follow,O.waitBird,O.soft,O.weave]],
 ['אם כל נמלה עושה אותו דבר — איזו מיומנות לוגית?','חזרה מסודרת.','repeat',[O.repeat,O.carry,O.rest,O.follow]],
 ['לומי שואלת: למה השיירה לא מתבלבלת?','יש לה כלל ברור לעקוב אחריו.','follow',[O.follow,O.repeat,O.rest,O.carry]],
]);}
function routeTask(prompt, goalText, start, goal, obstacles, solution, targetIcon='🏁', obstacleIcon='🪨') { return { prompt, goalText, start, goal, obstacles, solution, targetIcon, obstacleIcon }; }
function pathTasks(){return [
 routeTask('לומי עומדת בתחילת השביל ורוצה להגיע לעץ. בנו לה מסלול עם בלוקים.', 'הגיעו לעץ בלי לגעת באבן.', {x:0,y:3}, {x:2,y:3}, [{x:1,y:2}], ['right','right']),
 routeTask('הגשר נמצא למעלה. לומי צריכה לעלות ואז לפנות אל הדגל.', 'תכננו שני צעדים: למעלה ואז ימינה.', {x:0,y:3}, {x:1,y:2}, [{x:2,y:2}], ['up','right']),
 routeTask('יש שיח באמצע. עזרו ללומי לעקוף אותו בדרך לפרח.', 'לא דורכים על השיח.', {x:0,y:2}, {x:2,y:2}, [{x:1,y:2}], ['up','right','right','down']),
 routeTask('לומי רוצה להגיע לפטרייה שמעליה. איזה רצף קצר מתאים?', 'עלו שתי משבצות.', {x:1,y:3}, {x:1,y:1}, [{x:2,y:2}], ['up','up']),
 routeTask('הנחל חוסם את הדרך הישרה. צריך מסלול שמסתובב מסביב.', 'עקפו את המים והגיעו לעלה.', {x:0,y:3}, {x:3,y:2}, [{x:1,y:3},{x:1,y:2},{x:2,y:1}], ['up','up','up','right','right','right','down','down']),
 routeTask('לומי אוספת כוכב בסוף השביל. בנו רצף ימינה ולמעלה.', 'הכוכב מחכה בפינה.', {x:0,y:3}, {x:3,y:0}, [{x:1,y:1},{x:2,y:2}], ['right','right','right','up','up','up']),
 routeTask('יש שתי אבנים קטנות. לומי צריכה למצוא דרך נקייה.', 'אל תעברו דרך האבנים.', {x:0,y:1}, {x:3,y:1}, [{x:1,y:1},{x:2,y:0}], ['down','right','right','right','up']),
 routeTask('הגוזל מחכה בקצה השביל. תכננו מסלול של פניות.', 'להגיע לגוזל בלי קוצים.', {x:0,y:0}, {x:3,y:2}, [{x:1,y:0},{x:1,y:1},{x:2,y:3}], ['down','down','right','right','right']),
 routeTask('לומי צריכה להגיע לגשר ואז לחצות לצד השני.', 'הדרך הבטוחה עוברת באמצע.', {x:0,y:2}, {x:3,y:2}, [{x:1,y:3},{x:2,y:1}], ['right','right','right']),
 routeTask('השביל מתפתל כמו נחש קטן. סדרו את הבלוקים בזהירות.', 'לא לצאת מהמפה.', {x:3,y:3}, {x:0,y:0}, [{x:2,y:3},{x:2,y:1},{x:1,y:1}], ['up','up','up','left','left','left']),
 routeTask('לומי רוצה לבדוק מסלול ארוך יותר לשמורת הפרחים.', 'תכננו לפני שמריצים.', {x:0,y:0}, {x:3,y:3}, [{x:1,y:0},{x:1,y:1},{x:2,y:2}], ['down','down','down','right','right','right']),
 routeTask('אתגר סיום: עזרו ללומי להגיע למצפן בקצה המפה.', 'זה מסלול עם כמה פניות — כמו אלגוריתם קטן.', {x:0,y:3}, {x:3,y:0}, [{x:0,y:2},{x:1,y:1},{x:2,y:1}], ['right','right','right','up','up','up']),
];}

function visualMazeTasks(targetIcon, worldIcon='🌿', obstacleIcon='🪨') { return [
 routeTask(`🧒 ➜ ${targetIcon}`, 'בנו רצף חצים קצר והגיעו אל הסימן.', {x:0,y:3}, {x:2,y:3}, [{x:1,y:2}], ['right','right'], targetIcon, obstacleIcon),
 routeTask(`🧒 ⬆️ ➜ ${targetIcon}`, 'עלו ואז פנו. הרצף הוא אלגוריתם קטן.', {x:0,y:3}, {x:1,y:2}, [{x:2,y:2}], ['up','right'], targetIcon, obstacleIcon),
 routeTask(`🧒 ${obstacleIcon} ${targetIcon}`, 'עקפו את המחסום בלי לגעת בו.', {x:0,y:2}, {x:2,y:2}, [{x:1,y:2}], ['up','right','right','down'], targetIcon, obstacleIcon),
 routeTask(`🧒 ⬆️⬆️ ${targetIcon}`, 'שני חצים למעלה. פשוט ורציף.', {x:1,y:3}, {x:1,y:1}, [{x:2,y:2}], ['up','up'], targetIcon, obstacleIcon),
 routeTask(`🧒 ➜ ${worldIcon} ➜ ${targetIcon}`, 'מצאו דרך מסביב למחסומים.', {x:0,y:3}, {x:3,y:2}, [{x:1,y:3},{x:1,y:2},{x:2,y:1}], ['up','up','up','right','right','right','down','down'], targetIcon, obstacleIcon),
 routeTask(`🧒 ➡️⬆️ ${targetIcon}`, 'קודם ימינה, אחר כך למעלה.', {x:0,y:3}, {x:3,y:0}, [{x:1,y:1},{x:2,y:2}], ['right','right','right','up','up','up'], targetIcon, obstacleIcon),
 routeTask(`🧒 ${obstacleIcon}${obstacleIcon} ${targetIcon}`, 'יש שני מחסומים. בנו דרך נקייה.', {x:0,y:1}, {x:3,y:1}, [{x:1,y:1},{x:2,y:0}], ['down','right','right','right','up'], targetIcon, obstacleIcon),
 routeTask(`🧒 ↴ ${targetIcon}`, 'מסלול עם פנייה אחת גדולה.', {x:0,y:0}, {x:3,y:2}, [{x:1,y:0},{x:1,y:1},{x:2,y:3}], ['down','down','right','right','right'], targetIcon, obstacleIcon),
 routeTask(`🧒 ➡️➡️➡️ ${targetIcon}`, 'קו ישר הוא גם אלגוריתם.', {x:0,y:2}, {x:3,y:2}, [{x:1,y:3},{x:2,y:1}], ['right','right','right'], targetIcon, obstacleIcon),
 routeTask(`🧒 🌀 ${targetIcon}`, 'השביל מתפתל. סדרו חצים לפי הדרך.', {x:3,y:3}, {x:0,y:0}, [{x:2,y:3},{x:2,y:1},{x:1,y:1}], ['up','up','up','left','left','left'], targetIcon, obstacleIcon),
 routeTask(`🧒 ${worldIcon}${worldIcon} ${targetIcon}`, 'תכננו לפני ההרצה.', {x:0,y:0}, {x:3,y:3}, [{x:1,y:0},{x:1,y:1},{x:2,y:2}], ['down','down','down','right','right','right'], targetIcon, obstacleIcon),
 routeTask(`🧒 ⭐ ${targetIcon}`, 'אתגר סיום: כמה חצים ברצף.', {x:0,y:3}, {x:3,y:0}, [{x:0,y:2},{x:1,y:1},{x:2,y:1}], ['right','right','right','up','up','up'], targetIcon, obstacleIcon),
];}
function streamTasks(){return tasksFrom([
 ['האדמה ליד הנחל יבשה. מה עושים?','קלט: יבש. פלט: השקיה.','water',[O.water,O.closeGate,O.shade,O.wait]],
 ['יש יותר מדי מים בשביל. מה עושים לשער?','לא מציפים את השמורה.','closeGate',[O.closeGate,O.openGate,O.water,O.shade]],
 ['הנחל נמוך מאוד. מה מתאים?','פותחים כדי להזרים מים.','openGate',[O.openGate,O.closeGate,O.wait,O.shade]],
 ['השמש מחממת שתיל צעיר. מה עוזר?','קלט: חום. פלט: צל.','shade',[O.shade,O.water,O.openGate,O.closeGate]],
 ['אם החיישן אומר “רטוב מספיק” — מה עושים?','לא משקים סתם.','wait',[O.wait,O.water,O.openGate,O.shade]],
 ['טיפות נופלות שוב ושוב מהענף. מה יש כאן?', 'אירוע שחוזר.', 'repeat', [O.repeat,O.water,O.closeGate,O.openGate]],
 ['אם לומי פתחה מים ושכחה לסגור — מה התיקון?', 'צריך לעצור בזמן.', 'closeGate', [O.closeGate,O.openGate,O.water,O.wait]],
 ['אם הצמח יבש וגם חם — מה פעולה ראשונה עדינה?', 'קודם מים.', 'water', [O.water,O.shade,O.wait,O.closeGate]],
 ['מהו הקלט במשימה “האדמה יבשה”?','המצב שנמדד.','dry',[O.dry,O.wet,O.water,O.shade]],
 ['מהו הפלט במשימה “להשקות”?','הפעולה שלומי עושה.','water',[O.water,O.dry,O.wet,O.shade]],
 ['אם יש בוץ בכל מקום — איזו תווית מתאימה?', 'זה סימן לרטיבות.', 'wet', [O.wet,O.dry,O.water,O.openGate]],
 ['לומי מסכמת: אם יבש אז מים. מה זה?', 'כלל פשוט וחכם.', 'water', [O.water,O.wait,O.shade,O.closeGate]],
]);}
function mushroomTasks(){return tasksFrom([
 ['לומי מחפשת פטרייה אדומה עם נקודות. מה בוחרים?', 'צריך שני תנאים: צבע וגם דוגמה.', 'spotted', [O.spotted,O.plain,O.tall,O.tinyMush]],
 ['פטרייה לבנה בלי נקודות. איזו תווית?', 'אין נקודות בכלל.', 'plain', [O.plain,O.spotted,O.tall,O.tinyMush]],
 ['פטרייה שמגיעה כמעט לברך של לומי. מה המאפיין?', 'בודקים גובה.', 'tall', [O.tall,O.tinyMush,O.plain,O.spotted]],
 ['פטרייה קטנה מתחת לעלה. לאיזו קבוצה?', 'הגודל הוא הרמז.', 'tinyMush', [O.tinyMush,O.tall,O.spotted,O.plain]],
 ['אם יש צבע נכון אבל אין נקודות — האם זו מנוקדת?', 'חייבים שגם הנקודות יופיעו.', 'plain', [O.plain,O.spotted,O.tall,O.tinyMush]],
 ['אם יש נקודות וגם צבע מתאים — מה מתקיים?', 'תנאי וגם.', 'spotted', [O.spotted,O.plain,O.tall,O.tinyMush]],
 ['מי יוצאת דופן: קטנה, קטנה, קטנה, גבוהה?', 'מחפשים שונה לפי גובה.', 'tall', [O.tall,O.tinyMush,O.plain,O.spotted]],
 ['לומי רוצה למיין לפי “יש נקודות”. מה חשוב?', 'לא הגובה ולא הצבע לבד.', 'spotted', [O.spotted,O.tall,O.tinyMush,O.plain]],
 ['אם הפטרייה חלקה לגמרי — מה אין לה?', 'אין דוגמה.', 'plain', [O.plain,O.spotted,O.tall,O.tinyMush]],
 ['שני תנאים: גבוהה וגם חלקה. מה בודקים ראשון?', 'בודקים תכונה אחת ואז השנייה.', 'tall', [O.tall,O.plain,O.spotted,O.tinyMush]],
 ['אם תנאי אחד חסר, מה לומי עושה?', 'לא מאשרת מיד; בודקת שוב.', 'retry', [O.retry,O.spotted,O.tall,O.plain]],
 ['לומי כותבת בטבלה: צבע, גובה, נקודות. זו...', 'מיון לפי תכונות.', 'note', [O.note,O.retry,O.spotted,O.plain]],
]);}
function turtleTasks(){return tasksFrom([
 ['הצב זז צעד אחד לאט. איזו תווית מתאימה?', 'קצב התנועה הוא הרמז.', 'slow', [O.slow,O.fast,O.wait,O.compare]],
 ['הארנב קופץ מהר בשביל. איזו תווית?', 'הוא מגיע מהר.', 'fast', [O.fast,O.slow,O.wait,O.compare]],
 ['אם הצב עדיין בדרך, מה האלגוריתם צריך לעשות?', 'לא ממשיכים לפני שהוא מגיע.', 'wait', [O.wait,O.slow,O.fast,O.compare]],
 ['לומי רוצה לדעת מי הגיע ראשון. מה עושים?', 'מודדים ומשווים.', 'compare', [O.compare,O.wait,O.fast,O.slow]],
 ['אם יש 3 צעדים איטיים, מה חוזר?', 'הצעדים חוזרים בקצב קבוע.', 'slow', [O.slow,O.repeat,O.fast,O.wait]],
 ['אם הארנב רץ מהר מדי ועבר את היעד — מה עושים?', 'בודקים ומתקנים.', 'retry', [O.retry,O.fast,O.wait,O.compare]],
 ['מי צריך יותר זמן לחצות גשר?', 'הצב איטי יותר.', 'slow', [O.slow,O.fast,O.compare,O.wait]],
 ['אם מחכים לצב בתחנה — איזו פעולה זו?', 'עצירה מתוכננת.', 'wait', [O.wait,O.compare,O.fast,O.slow]],
 ['מה עוזר ללומי לתכנן מרוץ הוגן?', 'השוואת זמנים.', 'compare', [O.compare,O.wait,O.slow,O.fast]],
 ['אם פעולה מתרחשת מהר מדי, מה אפשר להוסיף?', 'לפעמים צריך השהיה.', 'wait', [O.wait,O.fast,O.slow,O.compare]],
 ['מי מתאים לקבוצת “מהירים”?', 'קצב גבוה.', 'fast', [O.fast,O.slow,O.wait,O.compare]],
 ['לומי כותבת: צב=איטי, ארנב=מהיר. זו...', 'סיווג לפי קצב.', 'note', [O.note,O.compare,O.fast,O.slow]],
]);}
function treeTasks(){return tasksFrom([
 ['לומי מגיעה לעץ החלטות. מה עושים קודם?', 'עץ החלטות מתחיל בשאלה.', 'ask', [O.ask,O.branch,O.leaf,O.retry]],
 ['אם התשובה היא “כן”, לאן הולכים?', 'כל תשובה מובילה לענף.', 'branch', [O.branch,O.ask,O.leaf,O.retry]],
 ['בסוף הענף יש תשובה סופית. מה זה?', 'החלטה בקצה העץ.', 'leaf', [O.leaf,O.branch,O.ask,O.retry]],
 ['אם הגענו לתשובה לא מתאימה — מה עושים?', 'חוזרים ובודקים שאלה אחרת.', 'retry', [O.retry,O.ask,O.branch,O.leaf]],
 ['השאלה: “יש כנפיים?” מה זו?', 'תנאי שמחלק לקבוצות.', 'ask', [O.ask,O.branch,O.leaf,O.retry]],
 ['אם “יש כנפיים” כן — לאיזה ענף?', 'עוברים לפי התשובה.', 'branch', [O.branch,O.ask,O.leaf,O.retry]],
 ['אם אין כנפיים ואין רגליים מהירות — צריך עוד...', 'שאלה חדשה עוזרת להחליט.', 'ask', [O.ask,O.retry,O.leaf,O.branch]],
 ['לומי הגיעה לעלה “דבורה”. מה זה?', 'תוצאה של החלטות.', 'leaf', [O.leaf,O.ask,O.branch,O.retry]],
 ['אם שאלה אחת לא מספיקה — מה מוסיפים?', 'עוד תנאי בעץ.', 'ask', [O.ask,O.branch,O.retry,O.leaf]],
 ['אם ענף מוביל תמיד לטעות — מה מתקנים?', 'מדבגים את העץ.', 'fix', [O.fix,O.ask,O.branch,O.leaf]],
 ['מה שומר על עץ החלטות ברור?', 'שאלה אחת בכל צומת.', 'ask', [O.ask,O.leaf,O.retry,O.fix]],
 ['בסוף לומי מציירת את העץ במחברת. מה היא עושה?', 'שומרת את ההיגיון לפעם הבאה.', 'note', [O.note,O.ask,O.branch,O.leaf]],
]);}
function labTasks(){return tasksFrom([
 ['לומי רוצה לבדוק אם צמח אוהב שמש. מה עושים?', 'ניסוי משנה דבר אחד.', 'test', [O.test,O.note,O.fix,O.retry]],
 ['אחרי הניסוי, מה חשוב לרשום?', 'בלי רישום שוכחים תוצאה.', 'note', [O.note,O.test,O.fix,O.retry]],
 ['אם התוצאה לא כמו שחשבנו — מה עושים?', 'מדע ותכנות אוהבים ניסיון נוסף.', 'retry', [O.retry,O.test,O.note,O.fix]],
 ['אם הכלל “כל יום מים” מציף את העציץ — מה עושים?', 'מתקנים כלל לא מדויק.', 'fix', [O.fix,O.test,O.note,O.retry]],
 ['לומי בודקת רק דבר אחד: יותר אור. למה?', 'ככה יודעים מה גרם לשינוי.', 'test', [O.test,O.note,O.fix,O.retry]],
 ['אם שכחנו לרשום מה קרה — מה חסר?', 'מחברת תצפית.', 'note', [O.note,O.test,O.retry,O.fix]],
 ['אם שתיל אחד קיבל מים ואחד לא — זו...', 'השוואה בניסוי.', 'test', [O.test,O.compare,O.note,O.fix]],
 ['אם כלל עובד רק בבוקר ולא בערב — מה צריך?', 'תנאי מדויק יותר.', 'fix', [O.fix,O.test,O.note,O.retry]],
 ['אם לומי טעתה במדידה — מה עושים?', 'מנסים שוב לאט.', 'retry', [O.retry,O.note,O.test,O.fix]],
 ['מה עוזר להבין באג בטבע?', 'בודקים שלב אחרי שלב.', 'test', [O.test,O.fix,O.note,O.retry]],
 ['בסוף המעבדה לומי כותבת מסקנה. מה הפעולה?', 'שומרים ידע.', 'note', [O.note,O.test,O.fix,O.retry]],
 ['אם המסקנה לא שומרת על הצמח — מה מתקנים?', 'דיבוג של כלל.', 'fix', [O.fix,O.note,O.test,O.retry]],
]);}
function reserveTasks(){return tasksFrom([
 ['בשמורה יש שביל עם קוצים. מה לומי עושה?', 'שומרים על החיות ועל הילדים.', 'avoid', [O.avoid,O.protect,O.note,O.retry]],
 ['חיה קטנה צריכה אזור שקט. מה המטרה?', 'שומרים על בית הגידול.', 'protect', [O.protect,O.avoid,O.water,O.note]],
 ['אם הנחל יבש — מה פעולה מתאימה?', 'שמורה צריכה מים.', 'water', [O.water,O.protect,O.closeGate,O.note]],
 ['אם יש יותר מדי מים — מה עושים?', 'מונעים הצפה.', 'closeGate', [O.closeGate,O.water,O.protect,O.retry]],
 ['לומי רואה בעיה חדשה. מה קודם?', 'שואלים ובודקים.', 'ask', [O.ask,O.protect,O.water,O.note]],
 ['אחרי פתרון מוצלח — מה רושמים?', 'מחברת המסע שומרת תובנות.', 'note', [O.note,O.protect,O.retry,O.ask]],
 ['אם פתרון לא עבד — מה עושים?', 'חוזרים, מתקנים ומנסים שוב.', 'retry', [O.retry,O.fix,O.note,O.protect]],
 ['אם הכלל פוגע בפרחים — מה צריך?', 'תיקון כלל.', 'fix', [O.fix,O.protect,O.note,O.retry]],
 ['מה מחבר את כל המסע של לומי?', 'הגנה על הטבע בעזרת חשיבה.', 'protect', [O.protect,O.note,O.ask,O.water]],
 ['אם צריך לעקוף אזור רגיש — איזו פעולה?', 'לא דורכים על הקן/הצמח.', 'avoid', [O.avoid,O.protect,O.note,O.retry]],
 ['אם יש גם יובש וגם שמש חזקה — מה אפשר לשלב?', 'מים וצל.', 'water', [O.water,O.shade,O.protect,O.closeGate]],
 ['בסוף הקורס לומי נותנת תג. מה הילד/ה הפכו להיות?', 'חוקרי טבע לוגיים.', 'protect', [O.protect,O.note,O.test,O.fix]],
]);}

window.LUMI_LESSONS = [
  { id:1, icon:'🐾', title:'עקבות ביער', concept:'מיון לפי סימנים', story:'לומי מצאה עקבות ליד הנחל. כל רמז הוא סימן קטן בסיפור, והילדים עוזרים לה להבין איזו חיה עברה שם.', sticker:'🦊', stickerName:'מדבקת שועל', type:'route', tasks:visualMazeTasks('🦊','🐾','🪵') },
  { id:2, icon:'🌸', title:'גינת הדפוסים', concept:'רצפים ודפוסים', story:'בגינה של לומי הפרחים גדלים לפי חוקיות קסומה. הילדים מנחשים מה יבוא בהמשך כמו קוראי סודות של הטבע.', sticker:'🌻', stickerName:'מדבקת חמנייה', type:'route', tasks:visualMazeTasks('🌻','🌷','🌵') },
  { id:3, icon:'☁️', title:'תחנת מזג האוויר', concept:'אם־אז', story:'לומי עומדת בתחנת עננים קטנה. גשם, רוח ושמש הופכים לכללי אם־אז שילדים יכולים להבין.', sticker:'🌈', stickerName:'מדבקת קשת', type:'route', tasks:visualMazeTasks('☂️','☁️','🌧️') },
  { id:4, icon:'🦋', title:'פרפרים וצבעים', concept:'קטגוריות ותכונות', story:'לומי פותחת עמוד צבעוני במחברת וממיינת פרפרים לפי צבע, גודל ודוגמה על הכנפיים.', sticker:'🦋', stickerName:'מדבקת פרפר', type:'route', tasks:visualMazeTasks('🦋','🌸','🪨') },
  { id:5, icon:'🪺', title:'קן הציפורים', concept:'סדר פעולות', story:'לומי עוזרת לציפור לבנות קן: מקום בטוח, זרדים, עלים רכים, ואז בדיקה שאין סכנות לגוזלים.', sticker:'🐦', stickerName:'מדבקת ציפור', type:'route', tasks:visualMazeTasks('🪺','🐦','🌵') },
  { id:6, icon:'🧺', title:'אוסף הזרעים', concept:'דאטה וספירה', story:'לומי מוצאת בלוטים, אצטרובלים וזרעי כנף. כל זרע נכנס לקבוצה אחרת במחברת האוספים.', sticker:'🌰', stickerName:'מדבקת בלוט', type:'route', tasks:visualMazeTasks('🌰','🌲','🪨') },
  { id:7, icon:'🌙', title:'לילה ביער', concept:'חיפוש לפי רמזים', story:'הלילה יורד, ולומי מקשיבה לקולות קטנים: ינשוף, עטלף, גחלילית וקיפוד מופיעים כמו סיפור לפני השינה.', sticker:'🦉', stickerName:'מדבקת ינשוף', type:'route', tasks:visualMazeTasks('🦉','🌙','🌲') },
  { id:8, icon:'🐜', title:'שיירת הנמלים', concept:'לולאות', story:'שיירת נמלים חרוצה מוצאת פירורים. לומי מגלה שחזרה מסודרת היא בעצם לולאה.', sticker:'🐜', stickerName:'מדבקת נמלה', type:'route', tasks:visualMazeTasks('🍞','🐜','🪨') },
  { id:9, icon:'🏞️', title:'מפת השביל', concept:'תכנון אלגוריתמי ובלוקים', story:'לומי פורשת מפה קטנה של היער: גשר, נחל, אבנים ושביל. הילדים בונים מסלול מבלוקים, מריצים, ומתקנים כמו מתכנתים צעירים.', sticker:'🧭', stickerName:'מדבקת מצפן', type:'route', tasks:visualMazeTasks('🧭','🏞️','🪨') },
  { id:10, icon:'💧', title:'טיפות לנחל', concept:'קלט־פלט', story:'נחל קטן מבקש עזרה. לומי קוראת סימני יובש ורטיבות ובוחרת מתי לפתוח מים ומתי לעצור.', sticker:'💧', stickerName:'מדבקת טיפה', type:'route', tasks:visualMazeTasks('💧','🌊','🪨') },
  { id:11, icon:'🍄', title:'יער הפטריות', concept:'תנאי וגם', story:'ביער הפטריות של לומי לא מספיק צבע אחד: לפעמים צריך גם צבע נכון וגם נקודות נכונות.', sticker:'🍄', stickerName:'מדבקת פטרייה', type:'route', tasks:visualMazeTasks('🍄','🌲','🪵') },
  { id:12, icon:'🐢', title:'הצב והקצב', concept:'מהירות וזמן', story:'צב איטי וארנב מהיר יוצאים למסלול. לומי לומדת מתי לחכות, מתי להשוות ומתי לנסות שוב.', sticker:'🐢', stickerName:'מדבקת צב', type:'route', tasks:visualMazeTasks('🐢','🌿','🪨') },
  { id:13, icon:'🌳', title:'עץ ההחלטות', concept:'עץ תנאים', story:'בעץ גדול של לומי כל ענף הוא שאלה. עונים כן או לא עד שמגיעים לעלה תשובה.', sticker:'🌳', stickerName:'מדבקת עץ', type:'route', tasks:visualMazeTasks('🌳','🍃','🪨') },
  { id:14, icon:'🧪', title:'מעבדת הטבע', concept:'ניסוי ודיבוג', story:'במעבדה הקטנה ליד העץ לומי משנה דבר אחד בכל פעם, רושמת מה קרה ומתקנת כלל שלא עבד.', sticker:'🔬', stickerName:'מדבקת מעבדה', type:'route', tasks:visualMazeTasks('🧪','🔬','🧱') },
  { id:15, icon:'🌍', title:'שמורת לומי', concept:'פרויקט סיום', story:'בשמורה של לומי מחברים את כל מה שלמדנו: רמזים, דפוסים, תנאים, מים, מסלול והגנה על חיות וצמחים.', sticker:'🏆', stickerName:'תג חוקרת טבע', type:'route', tasks:visualMazeTasks('🏆','🌍','🪨') },
];
