window.OCEAN_LESSONS = [
  {
    id: 1,
    title: 'שלום, שונית!',
    unit: 'צלילה ראשונה',
    emoji: '🐠',
    place: 'שונית אלמוגים',
    mission: 'סיסי הצוללת צריכה להגיע לצדפה הירוקה בלי להיתקע בסלעי ים.',
    concept: 'רצף פקודות',
    oceanFact: 'שונית אלמוגים היא כמו עיר קטנה מתחת למים, עם הרבה בעלי חיים שמסתתרים בה.',
    goal: { x: 5, y: 1 },
    start: { x: 1, y: 4 },
    obstacles: [{ x: 3, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 3 }],
    collectibles: [{ x: 2, y: 4 }, { x: 4, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  },
  {
    id: 2,
    title: 'אוצר בחול',
    unit: 'מפת אוצר',
    emoji: '🪙',
    place: 'קרקעית הים',
    mission: 'סיסי מחפשת מטבע עתיק ומנווטת בין אבנים קטנות בקרקעית.',
    concept: 'פקודות קצרות ומדויקות',
    oceanFact: 'בקרקעית הים יש חול, אבנים, צדפים ולפעמים גם שרידים של ספינות ישנות.',
    goal: { x: 6, y: 3 },
    start: { x: 1, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 3, y: 2 }, { x: 5, y: 2 }],
    collectibles: [{ x: 2, y: 2 }, { x: 4, y: 3 }, { x: 6, y: 2 }],
    commands: ['down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 3,
    title: 'יער האצות',
    unit: 'מסלול מתפתל',
    emoji: '🌿',
    place: 'יער אצות',
    mission: 'סיסי עוברת בין אצות גבוהות ומנסה לא לגעת בהן.',
    concept: 'תכנון מסלול',
    oceanFact: 'אצות הן צמחים פשוטים שחיים במים, וחלקן נותנות מחסה לדגים קטנים.',
    goal: { x: 6, y: 1 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 4 }, { x: 4, y: 3 }, { x: 5, y: 2 }],
    collectibles: [{ x: 1, y: 4 }, { x: 3, y: 3 }, { x: 5, y: 1 }],
    commands: ['up', 'up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 4,
    title: 'הסרטן השומר',
    unit: 'זהירות בדרך',
    emoji: '🦀',
    place: 'מערת סרטנים',
    mission: 'סיסי עוברת ליד סרטן חמוד, אבל צריכה לשמור מרחק ולעקוף אותו.',
    concept: 'אם יש מכשול — משנים כיוון',
    oceanFact: 'סרטנים הולכים הרבה פעמים הצידה, ויש להם שריון קשה שמגן עליהם.',
    goal: { x: 5, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 4, y: 1 }, { x: 4, y: 2 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    collectibles: [{ x: 2, y: 1 }, { x: 3, y: 4 }, { x: 5, y: 4 }],
    commands: ['down', 'down', 'down', 'down', 'right', 'right', 'right', 'right']
  },
  {
    id: 5,
    title: 'צב ים בדרך הביתה',
    unit: 'עוזרים לחבר',
    emoji: '🐢',
    place: 'מסלול הצבים',
    mission: 'סיסי עוזרת לצב ים קטן למצוא את הדרך הבטוחה הביתה.',
    concept: 'פעולה בסוף מסלול',
    oceanFact: 'צבי ים חוזרים לעיתים לחופים שבהם בקעו כדי להטיל ביצים כשהם גדלים.',
    goal: { x: 6, y: 4 },
    start: { x: 1, y: 3 },
    obstacles: [{ x: 3, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 5 }],
    collectibles: [{ x: 2, y: 3 }, { x: 4, y: 4 }, { x: 6, y: 5 }],
    commands: ['down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 6,
    title: 'לא להעיר את הכריש',
    unit: 'מסלול שקט',
    emoji: '🦈',
    place: 'מפרץ הכרישים',
    mission: 'סיסי בוחרת מסלול בטוח ושקט ליד כריש ישן.',
    concept: 'מכשולים ובחירת נתיב',
    oceanFact: 'כרישים מריחים טוב מאוד במים, ולכן הם מוצאים אוכל גם ממרחק.',
    goal: { x: 6, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }, { x: 5, y: 3 }],
    collectibles: [{ x: 1, y: 4 }, { x: 3, y: 2 }, { x: 5, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 7,
    title: 'ניקוי פלסטיק',
    unit: 'שומרים על הים',
    emoji: '♻️',
    place: 'חוף נקי',
    mission: 'סיסי אוספת פסולת קטנה מהמים ומגיעה לנקודת המיחזור.',
    concept: 'משימה עם איסוף',
    oceanFact: 'פלסטיק בים מסוכן לבעלי חיים, לכן חשוב לאסוף אשפה ולא להשאיר אותה בחוף.',
    goal: { x: 6, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 4 }],
    collectibles: [{ x: 2, y: 1 }, { x: 3, y: 3 }, { x: 5, y: 5 }],
    commands: ['down', 'down', 'down', 'down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 8,
    title: 'הדולפין מצייר מסלול',
    unit: 'אתגר סיום',
    emoji: '🐬',
    place: 'מפרץ הדולפינים',
    mission: 'סיסי עוקבת אחרי דולפין שמראה לה דרך קצרה וחכמה.',
    concept: 'בדיקה ושיפור מסלול',
    oceanFact: 'דולפינים מתקשרים בקולות ויכולים לזהות דברים במים בעזרת הדים.',
    goal: { x: 5, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 3 }, { x: 4, y: 3 }, { x: 5, y: 4 }],
    collectibles: [{ x: 1, y: 4 }, { x: 3, y: 2 }, { x: 5, y: 3 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  }
];

window.OCEAN_LESSONS.push(
  {
    id: 9,
    title: 'מערת הפנינים',
    unit: 'מסלול בתוך מערה',
    emoji: '🦪',
    place: 'מערה כחולה',
    mission: 'סיסי נכנסת למערה ומגיעה לצדפה נוצצת בלי לגעת בסלעים.',
    concept: 'תכנון סביב מכשולים',
    oceanFact: 'פנינים נוצרות בתוך צדפות מסוימות בשכבות עדינות ומבריקות.',
    goal: { x: 6, y: 4 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 3 }, { x: 5, y: 3 }],
    collectibles: [{ x: 2, y: 1 }, { x: 4, y: 2 }, { x: 6, y: 3 }],
    commands: ['right', 'right', 'right', 'right', 'right', 'down', 'down', 'down']
  },
  {
    id: 10,
    title: 'להקת דגים',
    unit: 'שומרים על קצב',
    emoji: '🐟',
    place: 'מסלול להקה',
    mission: 'סיסי שוחה ליד להקת דגים ושומרת על מסלול שקט וברור.',
    concept: 'רצף יציב',
    oceanFact: 'דגים רבים שוחים בלהקות כדי להגן אחד על השני ולמצוא דרך יחד.',
    goal: { x: 6, y: 1 },
    start: { x: 1, y: 4 },
    obstacles: [{ x: 2, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 2 }, { x: 5, y: 2 }],
    collectibles: [{ x: 1, y: 3 }, { x: 3, y: 4 }, { x: 5, y: 1 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 11,
    title: 'שונית לילה',
    unit: 'ניווט זהיר',
    emoji: '🌙',
    place: 'שונית בלילה',
    mission: 'סיסי מאירה בעדינות את הדרך ומגיעה לנקודת תצפית לילית.',
    concept: 'בדיקה לפני פעולה',
    oceanFact: 'בלילה חלק מבעלי החיים בים פעילים יותר, ולכן צריך להתבונן בזהירות.',
    goal: { x: 5, y: 5 },
    start: { x: 1, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 3, y: 3 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    collectibles: [{ x: 2, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 5 }],
    commands: ['down', 'down', 'down', 'right', 'right', 'right', 'right']
  },
  {
    id: 12,
    title: 'חזרה לנמל',
    unit: 'אתגר סיום',
    emoji: '⚓',
    place: 'נמל קטן',
    mission: 'סיסי מסיימת את המסע וחוזרת לנמל במסלול בטוח ונקי.',
    concept: 'אלגוריתם מסלול מלא',
    oceanFact: 'נמל הוא מקום שבו כלי שיט עוצרים, מתקנים ציוד ומתכוננים למסע הבא.',
    goal: { x: 6, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 4 }],
    collectibles: [{ x: 2, y: 1 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    commands: ['right', 'right', 'right', 'right', 'right', 'down', 'down', 'down', 'down']
  }
);
