window.OCEAN_LESSONS = [
  {
    id: 1,
    title: 'שלום, שונית!',
    unit: 'צלילה ראשונה',
    emoji: '🐠',
    place: 'שונית אלמוגים',
    mission: 'סיסי הצוללת צריכה להגיע לצדפה הירוקה בלי להיתקע בסלעי ים.',
    concept: 'רצף פקודות',
    oceanFact: 'שונית אלמוגים היא כמו עיר קטנה מתחת למים, עם הרבה בעלי חיים שמסתתרים בה.',
    goal: { x: 5, y: 1 },
    start: { x: 1, y: 4 },
    obstacles: [{ x: 3, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 3 }],
    collectibles: [{ x: 2, y: 4 }, { x: 4, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  },
  {
    id: 2,
    title: 'אוצר בחול',
    unit: 'מפת אוצר',
    emoji: '🪙',
    place: 'קרקעית הים',
    mission: 'סיסי מחפשת מטבע עתיק בקרקעית הים. אספו קודם את המטבע 🪙, ואז הגיעו לצדפה הירוקה בלי להיתקע בסלעים.',
    concept: 'פקודות קצרות ומדויקות',
    oceanFact: 'בקרקעית הים יש חול, אבנים, צדפים ולפעמים גם שרידים של ספינות ישנות.',
    goal: { x: 6, y: 3 },
    start: { x: 1, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 3, y: 2 }, { x: 5, y: 2 }],
    requiredCollectible: { x: 4, y: 4, icon: '🪙', name: 'המטבע העתיק' },
    collectibles: [{ x: 2, y: 2 }, { x: 6, y: 2 }],
    commands: ['down', 'right', 'right', 'right', 'down', 'right', 'right', 'up']
  },
  {
    id: 3,
    title: 'יער האצות',
    unit: 'מסלול מתפתל',
    emoji: '🌿',
    place: 'יער אצות',
    mission: 'סיסי עוברת בין אצות גבוהות ומנסה לא לגעת בהן.',
    concept: 'תכנון מסלול',
    oceanFact: 'אצות הן צמחים פשוטים שחיים במים, וחלקן נותנות מחסה לדגים קטנים.',
    goal: { x: 6, y: 1 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 4 }, { x: 2, y: 2 }, { x: 4, y: 3 }, { x: 5, y: 2 }],
    collectibles: [{ x: 1, y: 4 }, { x: 3, y: 3 }, { x: 5, y: 1 }],
    commands: ['up', 'up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 4,
    title: 'הסרטן השומר',
    unit: 'זהירות בדרך',
    emoji: '🦀',
    place: 'מערת סרטנים',
    mission: 'הסרטן שומר על המערה. סיסי צריכה להגיע לצדפה הירוקה, אבל לשמור מרחק: לא לעבור באזור הזהירות שליד הסרטן.',
    concept: 'שומרים מרחק ממכשול',
    oceanFact: 'סרטנים הולכים הרבה פעמים הצידה, ויש להם שריון קשה שמגן עליהם.',
    goal: { x: 5, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 4, y: 1 }, { x: 4, y: 2 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    dangerZones: [{ x: 3, y: 1 }, { x: 3, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 1 }, { x: 5, y: 2 }, { x: 5, y: 3 }],
    collectibles: [{ x: 2, y: 1 }, { x: 2, y: 5 }, { x: 1, y: 5 }],
    commands: ['down', 'down', 'down', 'down', 'right', 'right', 'right', 'right']
  },
  {
    id: 5,
    title: 'צב ים בדרך הביתה',
    unit: 'עוזרים לחבר',
    emoji: '🐢',
    place: 'מסלול הצבים',
    mission: 'צב ים קטן צריך להגיע הביתה. הגיעו קודם אל הצב 🐢, ואז לוו אותו לבית הירוק בלי להיתקע בסלעים.',
    concept: 'קודם עוזרים לחבר, ואז מגיעים ליעד',
    oceanFact: 'צבי ים חוזרים לעיתים לחופים שבהם בקעו כדי להטיל ביצים כשהם גדלים.',
    goal: { x: 6, y: 4 },
    goalIcon: '🏠',
    start: { x: 1, y: 3 },
    obstacles: [{ x: 3, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 5 }],
    requiredCollectible: { x: 2, y: 5, icon: '🐢', name: 'הצב', missingMessage: 'כמעט! קודם צריך להגיע אל הצב, ורק אחר כך ללוות אותו הביתה.' },
    collectibles: [{ x: 2, y: 3 }, { x: 4, y: 4 }, { x: 6, y: 3 }],
    commands: ['down', 'down', 'right', 'up', 'right', 'right', 'right', 'right']
  },
  {
    id: 6,
    title: 'לא להעיר את הכריש',
    unit: 'מסלול שקט',
    emoji: '🦈',
    place: 'מפרץ הכרישים',
    mission: 'סיסי בוחרת מסלול בטוח ושקט ליד כריש ישן.',
    concept: 'מכשולים ובחירת נתיב',
    oceanFact: 'כרישים מריחים טוב מאוד במים, ולכן הם מוצאים אוכל גם ממרחק.',
    goal: { x: 6, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 4 }, { x: 4, y: 5 }, { x: 4, y: 3 }, { x: 5, y: 1 }],
    collectibles: [{ x: 1, y: 4 }, { x: 3, y: 1 }, { x: 5, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 7,
    title: 'ניקוי פלסטיק',
    unit: 'שומרים על הים',
    emoji: '♻️',
    place: 'חוף נקי',
    mission: 'סיסי צריכה לאסוף שני פריטי פסולת מהמים 🧴🥤, ואז להגיע לנקודת המיחזור כדי שלא יזיקו לבעלי חיים.',
    concept: 'קודם אוספים, ואז ממחזרים',
    oceanFact: 'פלסטיק בים מסוכן לבעלי חיים, לכן חשוב לאסוף אשפה ולא להשאיר אותה בחוף.',
    goal: { x: 6, y: 5 },
    goalIcon: '♻️',
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 4 }, { x: 6, y: 1 }],
    requiredCollectibles: [
      { x: 3, y: 3, icon: '🧴', name: 'בקבוק הפלסטיק' },
      { x: 5, y: 5, icon: '🥤', name: 'כוס הפלסטיק' }
    ],
    requiredMissingMessage: 'כמעט! קודם צריך לאסוף את שני פריטי הפסולת, ורק אחר כך להגיע לנקודת המיחזור.',
    collectibles: [{ x: 2, y: 1 }, { x: 1, y: 4 }, { x: 4, y: 5 }],
    commands: ['down', 'down', 'right', 'right', 'down', 'down', 'right', 'right', 'right']
  },
  {
    id: 8,
    title: 'הדולפין מצייר מסלול',
    unit: 'אתגר סיום',
    emoji: '🐬',
    place: 'מפרץ הדולפינים',
    mission: 'הדולפין מראה לסיסי דרך קצרה וחכמה: בכל רגע הוא מהבהב על משבצת אחרת במסלול הקצר אל הצדפה הירוקה.',
    concept: 'רמזים למסלול קצר',
    oceanFact: 'דולפינים מתקשרים בקולות ויכולים לזהות דברים במים בעזרת הדים.',
    goal: { x: 5, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 3 }, { x: 4, y: 3 }, { x: 5, y: 4 }],
    dolphinGuidePath: [{ x: 1, y: 4 }, { x: 1, y: 3 }, { x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 }, { x: 5, y: 2 }],
    collectibles: [{ x: 1, y: 4 }, { x: 3, y: 2 }, { x: 5, y: 3 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  }
];

window.OCEAN_LESSONS.push(
  {
    id: 9,
    title: 'מערת הפנינים',
    unit: 'מסלול בתוך מערה',
    emoji: '🦪',
    place: 'מערה כחולה',
    mission: 'סיסי נכנסת למערת הפנינים. אספו שתי פניני מפתח 💎💎 כדי לפתוח את שער המערה, ואז הגיעו לצדפה הנוצצת.',
    concept: 'פתיחת שער בעזרת איסוף',
    oceanFact: 'פנינים נוצרות בתוך צדפות מסוימות בשכבות עדינות ומבריקות.',
    goal: { x: 6, y: 4 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 3 }, { x: 5, y: 3 }],
    requiredCollectibles: [
      { x: 4, y: 2, icon: '💎', name: 'פנינת המפתח הראשונה' },
      { x: 1, y: 3, icon: '💎', name: 'פנינת המפתח השנייה' }
    ],
    requiredMissingMessage: 'כמעט! קודם צריך לאסוף את שתי פניני המפתח כדי לפתוח את שער המערה.',
    caveGate: { x: 6, y: 3 },
    caveGateMessage: 'השער עדיין סגור! אספו קודם את שתי פניני המפתח 💎💎.',
    caveGateRequiredMessage: 'כמעט! צריך להיכנס לצדפה דרך שער המערה, אחרי שאוספים את שתי פניני המפתח.',
    collectibles: [{ x: 2, y: 1 }, { x: 3, y: 5 }, { x: 5, y: 2 }],
    commands: ['down', 'down', 'up', 'up', 'right', 'right', 'right', 'down', 'up', 'right', 'right', 'down', 'down', 'down']
  },
  {
    id: 10,
    title: 'להקת דגים',
    unit: 'שומרים על קצב',
    emoji: '🐟',
    place: 'מסלול להקה',
    mission: 'סיסי שוחה ליד להקת דגים בתנועה. הדגים זזים הלוך ושוב 🐟. אם דג נמצא במשבצת — לא נכנסים אליה. כשהדג זז והמשבצת ריקה — אפשר לעבור. אם נתקלים בדג, נסו להריץ שוב כשהדג במשבצת השנייה.',
    concept: 'שמירה על מרחק מלהקה',
    oceanFact: 'דגים רבים שוחים בלהקות כדי להגן אחד על השני ולמצוא דרך יחד.',
    goal: { x: 6, y: 1 },
    start: { x: 1, y: 4 },
    obstacles: [{ x: 2, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 2 }, { x: 5, y: 2 }],
    blockedDecorationMessage: 'כמעט! זו להקת הדגים בתנועה. צריך לעקוף אותה בעדינות ולא להיכנס לתוכה.',
    collectibles: [{ x: 1, y: 3 }, { x: 3, y: 1 }, { x: 5, y: 1 }],
    movingDecorations: [
      { icon: '🐟', blocked: true, positions: [{ x: 2, y: 4 }, { x: 2, y: 5 }], pattern: [0, 1, 1, 1, 0, 0] },
      { icon: '🐟', blocked: true, positions: [{ x: 4, y: 4 }, { x: 5, y: 4 }], pattern: [0, 0, 1, 1, 1, 0] },
      { icon: '🐟', blocked: true, positions: [{ x: 1, y: 1 }, { x: 1, y: 2 }], pattern: [0, 0, 0, 1, 1, 1] }
    ],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 11,
    title: 'שונית לילה',
    unit: 'ניווט זהיר',
    emoji: '🌙',
    place: 'שונית בלילה',
    mission: 'שונית הלילה חשוכה. רואים רק את סיסי, את הריבועים שלידה, ואת הצדפה הירוקה. הובילו את סיסי בזהירות. אם היא נתקלת בסלע בחושך — עכשיו הסלע מתגלה, ואפשר לשנות מסלול ולנסות שוב.',
    concept: 'ניווט בחושך ובדיקה תוך כדי',
    oceanFact: 'בלילה חלק מבעלי החיים בים פעילים יותר, ולכן צריך להתבונן בזהירות.',
    goal: { x: 5, y: 5 },
    nightFog: true,
    start: { x: 1, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 3, y: 3 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    collectibles: [{ x: 2, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 5 }],
    commands: ['down', 'down', 'down', 'right', 'right', 'right', 'right']
  },
  {
    id: 12,
    title: 'חזרה לנמל',
    unit: 'אתגר סיום',
    emoji: '⚓',
    place: 'נמל קטן',
    mission: 'סיסי מסיימת את המסע וחוזרת לנמל. אספו קודם את המפה 🗺️, עברו ליד המצוף 🛟, ואז הגיעו לנמל בבטחה.',
    concept: 'תרגיל סיכום עם כמה שלבים',
    oceanFact: 'נמל הוא מקום שבו כלי שיט עוצרים, מתקנים ציוד ומתכוננים למסע הבא.',
    goal: { x: 6, y: 5 },
    goalIcon: '⚓',
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 3 }, { x: 5, y: 3 }, { x: 3, y: 5 }],
    requiredCollectible: { x: 1, y: 5, icon: '🗺️', name: 'המפה' },
    requiredWaypoints: [{ x: 5, y: 1, icon: '🛟', name: 'המצוף' }],
    requiredMissingMessage: 'כמעט! קודם צריך לאסוף את המפה ולעבור ליד המצוף, ורק אחר כך להגיע לנמל.',
    collectibles: [{ x: 2, y: 1 }, { x: 4, y: 2 }, { x: 6, y: 4 }],
    commands: ['down', 'down', 'down', 'down', 'up', 'up', 'up', 'up', 'right', 'right', 'right', 'right', 'down', 'right', 'down', 'down', 'down']
  }
);
