window.SPACE_LESSONS = [
  {
    id: 1,
    title: 'שלום, ירח!',
    unit: 'המראה רכה',
    emoji: '🌙',
    place: 'הירח',
    mission: 'סיסי צריכה להגיע בעדינות לדגל שעל הירח בלי להיתקע בסלעים.',
    concept: 'רצף פקודות',
    spaceFact: 'הירח לא מאיר בעצמו — הוא מחזיר אלינו אור מהשמש.',
    goal: { x: 5, y: 1 },
    start: { x: 1, y: 4 },
    obstacles: [{ x: 3, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 3 }],
    stars: [{ x: 2, y: 4 }, { x: 4, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  },
  {
    id: 2,
    title: 'כוכב האבק האדום',
    unit: 'מאדים',
    emoji: '🔴',
    place: 'מאדים',
    mission: 'הרובר של סיסי אוסף דגימת אדמה אדומה ושולח “מצאתי!”',
    concept: 'פקודות קצרות ומדויקות',
    spaceFact: 'מאדים נראה אדום כי באדמה שלו יש הרבה ברזל חלוד.',
    goal: { x: 6, y: 3 },
    start: { x: 1, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 3, y: 2 }, { x: 5, y: 2 }],
    stars: [{ x: 2, y: 2 }, { x: 4, y: 3 }, { x: 6, y: 2 }],
    commands: ['down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 3,
    title: 'טבעת שבתאי',
    unit: 'ענקי הגז',
    emoji: '🪐',
    place: 'שבתאי',
    mission: 'סיסי טסה בין גושי קרח קטנים שמרכיבים את הטבעות.',
    concept: 'תכנון מסלול',
    spaceFact: 'הטבעות של שבתאי עשויות בעיקר מקרח ואבנים קטנות.',
    goal: { x: 6, y: 1 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 4 }, { x: 4, y: 3 }, { x: 5, y: 2 }],
    stars: [{ x: 1, y: 4 }, { x: 3, y: 3 }, { x: 5, y: 1 }],
    commands: ['up', 'up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 4,
    title: 'שמש בלי להתקרב מדי',
    unit: 'השמש',
    emoji: '☀️',
    place: 'קרוב לשמש',
    mission: 'סיסי בודקת חום עם חיישן ונשארת באזור בטוח.',
    concept: 'אם חם מדי — עוצרים',
    spaceFact: 'השמש היא כוכב. היא נותנת לכדור הארץ אור וחום.',
    goal: { x: 5, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 4, y: 1 }, { x: 4, y: 2 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    stars: [{ x: 2, y: 1 }, { x: 3, y: 4 }, { x: 5, y: 4 }],
    commands: ['down', 'down', 'down', 'down', 'right', 'right', 'right', 'right']
  },
  {
    id: 5,
    title: 'חבר חייזר קטן',
    unit: 'תקשורת',
    emoji: '👽',
    place: 'כוכבון ירוק',
    mission: 'סיסי מגיעה לחייזר חמוד ומשדרת הודעת שלום.',
    concept: 'פקודת פעולה בסוף מסלול',
    spaceFact: 'בחלל שולחים מידע בגלי רדיו, כי קול רגיל לא עובר בריק.',
    goal: { x: 6, y: 4 },
    start: { x: 1, y: 3 },
    obstacles: [{ x: 3, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 5 }],
    stars: [{ x: 2, y: 3 }, { x: 4, y: 4 }, { x: 6, y: 5 }],
    commands: ['down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 6,
    title: 'גשם מטאורים',
    unit: 'זהירות בדרך',
    emoji: '☄️',
    place: 'שדה מטאורים',
    mission: 'סיסי מתכננת נתיב בטוח בין מטאורים קטנים.',
    concept: 'מכשול = לשנות כיוון',
    spaceFact: 'מטאור הוא אבן חלל שנכנסת לאטמוספרה ונראית כמו “כוכב נופל”.',
    goal: { x: 6, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }, { x: 5, y: 3 }],
    stars: [{ x: 1, y: 4 }, { x: 3, y: 2 }, { x: 5, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 7,
    title: 'תחנת החלל',
    unit: 'עזרה לצוות',
    emoji: '🛰️',
    place: 'תחנת חלל',
    mission: 'סיסי מביאה סוללה חדשה לתחנת החלל.',
    concept: 'משימה עם נקודת איסוף',
    spaceFact: 'אסטרונאוטים בתחנת החלל מקיפים את כדור הארץ הרבה פעמים ביום.',
    goal: { x: 6, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 4 }],
    stars: [{ x: 2, y: 1 }, { x: 3, y: 3 }, { x: 5, y: 5 }],
    commands: ['down', 'down', 'down', 'down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 8,
    title: 'הטלסקופ הסקרן',
    unit: 'תצפית',
    emoji: '🔭',
    place: 'מצפה כוכבים',
    mission: 'סיסי מכוונת טלסקופ ומוצאת קבוצת כוכבים.',
    concept: 'בדיקה ואז פעולה',
    spaceFact: 'טלסקופ עוזר לנו לראות דברים רחוקים מאוד בשמים.',
    goal: { x: 5, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 3 }, { x: 4, y: 3 }, { x: 5, y: 4 }],
    stars: [{ x: 1, y: 4 }, { x: 3, y: 2 }, { x: 5, y: 3 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  }
];
