window.SPACE_LESSONS = [
  {
    id: 1,
    title: 'שלום, ירח!',
    unit: 'המראה רכה',
    emoji: '🌙',
    place: 'הירח',
    mission: 'סיסי צריכה להגיע בעדינות לדגל הירוק שעל הירח בלי להיתקע בסלעים האדומים.',
    concept: 'רצף פקודות',
    spaceFact: 'הירח לא מאיר בעצמו — הוא מחזיר אלינו אור מהשמש. בלוח: 🪨/אדום = סלע שחוסם דרך, 🏁/ירוק = יעד הסיום.',
    goal: { x: 5, y: 1 },
    start: { x: 1, y: 4 },
    obstacles: [{ x: 3, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 3 }],
    stars: [{ x: 2, y: 4 }, { x: 4, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  },
  {
    id: 2,
    title: 'כוכב האבק האדום',
    unit: 'מאדים',
    emoji: '🔴',
    place: 'מאדים',
    mission: 'הרובר של סיסי אוסף דגימת אדמה אדומה ושולח “מצאתי!”',
    concept: 'פקודות קצרות ומדויקות',
    spaceFact: 'מאדים נראה אדום כי באדמה שלו יש הרבה ברזל חלוד.',
    goal: { x: 6, y: 3 },
    start: { x: 1, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 3, y: 2 }, { x: 5, y: 2 }],
    stars: [{ x: 2, y: 2 }, { x: 4, y: 3 }, { x: 6, y: 2 }],
    commands: ['down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 3,
    title: 'טבעת שבתאי',
    unit: 'ענקי הגז',
    emoji: '🪐',
    place: 'שבתאי',
    mission: 'סיסי טסה בין גושי קרח קטנים שמרכיבים את הטבעות.',
    concept: 'תכנון מסלול',
    spaceFact: 'הטבעות של שבתאי עשויות בעיקר מקרח ואבנים קטנות.',
    goal: { x: 6, y: 1 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 4 }, { x: 4, y: 3 }, { x: 5, y: 2 }],
    stars: [{ x: 1, y: 4 }, { x: 3, y: 3 }, { x: 5, y: 1 }],
    commands: ['up', 'up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 4,
    title: 'שמש בלי להתקרב מדי',
    unit: 'השמש',
    emoji: '☀️',
    place: 'קרוב לשמש',
    mission: 'סיסי בודקת חום עם חיישן ונשארת באזור בטוח.',
    concept: 'אם חם מדי — עוצרים',
    spaceFact: 'השמש היא כוכב. היא נותנת לכדור הארץ אור וחום.',
    goal: { x: 5, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 4, y: 1 }, { x: 4, y: 2 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    stars: [{ x: 2, y: 1 }, { x: 3, y: 4 }, { x: 5, y: 4 }],
    commands: ['down', 'down', 'down', 'down', 'right', 'right', 'right', 'right']
  },
  {
    id: 5,
    title: 'חבר חייזר קטן',
    unit: 'תקשורת',
    emoji: '👽',
    place: 'כוכבון ירוק',
    mission: 'סיסי מגיעה לחייזר חמוד ומשדרת הודעת שלום. אפשר לאסוף ⭐ כוכבים בדרך כדי לקבל בונוס ולתכנן מסלול חכם יותר.',
    concept: 'פקודת פעולה בסוף מסלול',
    spaceFact: 'בחלל שולחים מידע בגלי רדיו, כי קול רגיל לא עובר בריק. הכוכבים הם בונוס: לא חובה, אבל הם מדרבנים קוד מורכב ומעניין יותר.',
    goal: { x: 6, y: 4 },
    start: { x: 1, y: 3 },
    obstacles: [{ x: 3, y: 2 }, { x: 3, y: 3 }, { x: 5, y: 5 }],
    stars: [{ x: 2, y: 3 }, { x: 4, y: 4 }, { x: 6, y: 5 }],
    commands: ['down', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 6,
    title: 'גשם מטאורים',
    unit: 'זהירות בדרך',
    emoji: '☄️',
    place: 'שדה מטאורים',
    mission: 'סיסי מתכננת נתיב בטוח בין מטאורים קטנים.',
    concept: 'מכשול = לשנות כיוון',
    spaceFact: 'מטאור הוא אבן חלל שנכנסת לאטמוספרה ונראית כמו “כוכב נופל”.',
    goal: { x: 6, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }, { x: 5, y: 3 }],
    stars: [{ x: 1, y: 4 }, { x: 3, y: 2 }, { x: 5, y: 2 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 7,
    title: 'תחנת החלל',
    unit: 'עזרה לצוות',
    emoji: '🛰️',
    place: 'תחנת חלל',
    mission: 'סיסי צריכה קודם לאסוף סוללה חדשה, ורק אחר כך להביא אותה לתחנת החלל.',
    concept: 'משימה עם נקודת איסוף חובה',
    spaceFact: 'אסטרונאוטים בתחנת החלל מקיפים את כדור הארץ הרבה פעמים ביום.',
    goal: { x: 6, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 4 }],
    stars: [{ x: 3, y: 3 }, { x: 5, y: 5 }],
    requiredItems: [{ id: 'battery', icon: '🔋', label: 'סוללה לתחנת החלל', position: { x: 2, y: 1 }, collectedMessage: 'סיסי אספה את הסוללה! עכשיו אפשר להגיע לתחנה.' }],
    commands: ['right', 'right', 'right', 'right', 'right', 'down', 'down', 'down', 'down']
  },
  {
    id: 8,
    title: 'הטלסקופ הסקרן',
    unit: 'תצפית',
    emoji: '🔭',
    place: 'מצפה כוכבים',
    mission: 'סיסי צריכה להגיע לטלסקופ, לכוון אותו, ואז להגיע לנקודת התצפית ולמצוא קבוצת כוכבים.',
    concept: 'איסוף כלי ואז פעולה',
    spaceFact: 'טלסקופ עוזר לנו לראות דברים רחוקים מאוד בשמים.',
    goal: { x: 5, y: 2 },
    start: { x: 1, y: 5 },
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 3 }, { x: 4, y: 3 }, { x: 5, y: 4 }],
    stars: [{ x: 1, y: 4 }, { x: 4, y: 2 }, { x: 5, y: 3 }],
    requiredItems: [{ id: 'telescope', icon: '🔭', label: 'טלסקופ לכיוון', position: { x: 3, y: 2 }, collectedMessage: 'סיסי כיוונה את הטלסקופ! עכשיו ממשיכים לנקודת התצפית.' }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right']
  }
];

window.SPACE_LESSONS.push(
  {
    id: 9,
    title: 'מעבר בין אסטרואידים',
    unit: 'מסלול בטוח',
    emoji: '🪨',
    place: 'חגורת אסטרואידים',
    mission: 'סיסי מתכננת נתיב בין אבני חלל בלי לפגוע באף אחת.',
    concept: 'תכנון סביב מכשולים',
    spaceFact: 'אסטרואידים הם גושי סלע שמקיפים את השמש במסלולים שונים.',
    goal: { x: 6, y: 4 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 3 }, { x: 5, y: 3 }],
    stars: [{ x: 2, y: 1 }, { x: 4, y: 2 }, { x: 6, y: 3 }],
    commands: ['right', 'right', 'right', 'right', 'right', 'down', 'down', 'down']
  },
  {
    id: 10,
    title: 'תיקון אנטנה',
    unit: 'תקשורת חלל',
    emoji: '📡',
    place: 'לווין תקשורת',
    mission: 'סיסי מגיעה לאנטנה כדי להחזיר קשר עם כדור הארץ.',
    concept: 'פקודה בסוף מסלול',
    spaceFact: 'לוויינים עוזרים לנו בתקשורת, ניווט וחיזוי מזג אוויר.',
    goal: { x: 6, y: 1 },
    start: { x: 1, y: 4 },
    obstacles: [{ x: 2, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 2 }, { x: 5, y: 2 }],
    stars: [{ x: 1, y: 3 }, { x: 3, y: 4 }, { x: 5, y: 1 }],
    commands: ['up', 'up', 'up', 'right', 'right', 'right', 'right', 'right']
  },
  {
    id: 11,
    title: 'כוכב שביט נוצץ',
    unit: 'מעקב אחרי תנועה',
    emoji: '🌠',
    place: 'מסלול שביט',
    mission: 'סיסי עוקבת אחרי זנב של שביט ומגיעה לנקודת צילום בטוחה.',
    concept: 'בדיקת נתיב לפני הרצה',
    spaceFact: 'כוכב שביט עשוי קרח ואבק, וכשהוא מתקרב לשמש נוצר לו זנב בהיר.',
    goal: { x: 5, y: 5 },
    start: { x: 1, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 3, y: 3 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    stars: [{ x: 2, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 5 }],
    commands: ['down', 'down', 'down', 'right', 'right', 'right', 'right']
  },
  {
    id: 12,
    title: 'חזרה הביתה לכדור הארץ',
    unit: 'אתגר סיום',
    emoji: '🌍',
    place: 'מסלול חזרה',
    mission: 'סיסי מסיימת את שיעור החלל וחוזרת לנחיתה בטוחה בכדור הארץ.',
    concept: 'אלגוריתם מסלול מלא',
    spaceFact: 'כדור הארץ הוא הבית שלנו, ולכן משימות חלל מסתיימות תמיד בתכנון חזרה בטוח.',
    goal: { x: 6, y: 5 },
    start: { x: 1, y: 1 },
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 4 }, { x: 5, y: 4 }],
    stars: [{ x: 2, y: 1 }, { x: 4, y: 3 }, { x: 6, y: 4 }],
    commands: ['right', 'right', 'right', 'right', 'right', 'down', 'down', 'down', 'down']
  }
);
