import assert from 'node:assert/strict';
import test from 'node:test';
import { existsSync, readFileSync } from 'node:fs';
import vm from 'node:vm';

const root = new URL('../', import.meta.url);
const homepageHtml = readFileSync(new URL('index.html', root), 'utf8');
const courseHtml = readFileSync(new URL('drone-intelligence-lab-grade9.html', root), 'utf8');
const playHtml = readFileSync(new URL('drone-intelligence-lab-grade9-play.html', root), 'utf8');
const slidesHtml = readFileSync(new URL('drone-intelligence-lab-grade9-slides.html', root), 'utf8');
const guideHtml = readFileSync(new URL('drone-intelligence-lab-grade9-guide.html', root), 'utf8');
const lessonsSource = readFileSync(new URL('js/drone-intelligence-lab-grade9-lessons.js', root), 'utf8');

function assertIncludes(source, needle, message = `Missing: ${needle}`) { assert.ok(source.includes(needle), message); }
function loadLessons() { const sandbox = { window: {} }; vm.createContext(sandbox); vm.runInContext(lessonsSource, sandbox); return sandbox.window; }
const data = loadLessons();

test('Drone Intelligence Lab exposes a 15 lesson grade 9 JavaScript intelligence scaffold', () => {
  const lessons = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS;
  assert.equal(lessons.length, 15);
  assert.equal(JSON.stringify(lessons.map(l => l.id)), JSON.stringify(Array.from({ length: 15 }, (_, i) => i + 1)));
  assert.ok(lessons.every(l => l.durationMinutes === 90));
  assert.ok(lessons.every(l => l.grade === 'כיתה ט׳ עתודה'));
  assert.ok(lessons.every(l => l.language === 'JavaScript'));
  assert.ok(lessons.every(l => l.tabletFirst === true));
  assert.ok(lessons.slice(0, 4).every(l => l.physicalFlightAllowed === false));
  assert.equal(lessons[4].physicalFlightAllowed, true);
  assert.equal(lessons[5].physicalFlightAllowed, false);
  assert.equal(lessons[6].physicalFlightAllowed, false);
  assert.equal(lessons[7].physicalFlightAllowed, true);
  assert.equal(lessons[8].physicalFlightAllowed, true);
  assert.equal(lessons[9].physicalFlightAllowed, false);
  assert.ok(lessons.slice(10).every(l => l.physicalFlightAllowed === true));
});

test('Drone Intelligence Lab follows the syllabus topics for grade 9', () => {
  const lessons = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS;
  assertIncludes(lessons[5].title, 'לוגיקה אלגוריתמית מורכבת');
  assertIncludes(lessons[5].concept, 'Boolean');
  assertIncludes(lessons[6].title, 'סריקה תלת־ממדית');
  assertIncludes(lessons[7].title, 'מכשולים דינמיים');
  assertIncludes(lessons[8].title, 'ניתוח יעילות קוד');
  assertIncludes(lessons[8].concept, 'Performance');
  assertIncludes(lessons[9].title, 'מעבדה חכמה בשטח');
  assertIncludes(lessons[13].title, 'דוח טכנולוגי');
  assertIncludes(lessons[14].title, 'פיץ׳ טכנולוגי');
});

test('Drone Intelligence Lab lesson 1 implements the reactor simulator safety and syntax plan', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[0];
  assertIncludes(lesson.title, 'סריקת כור וירטואלית');
  assertIncludes(lesson.concept, 'Industrial Syntax');
  assertIncludes(lesson.story, 'IAEA');
  assertIncludes(lesson.story, 'Flyability Elios');
  assertIncludes(lesson.mission, 'סימולטיבית בלבד');
  assertIncludes(lesson.mission, '80 ס״מ');
  assertIncludes(lesson.mission, '120 ס״מ');
  assert.equal(lesson.physicalFlightAllowed, false);
  assert.equal(lesson.workspaceMode, 'droneblocks-app');
  assert.equal(lesson.presentationMode, 'focused');
  assert.ok(lesson.blocks.includes('flyUp'));
  assert.ok(lesson.blocks.includes('flyDown'));
  assert.ok(lesson.blocks.includes('sleep'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assertIncludes(lesson.lessonFlow[2].teacher, 'כבוי וללא סוללה');
  assertIncludes(lesson.lessonFlow[2].teacher, 'VPS');
  assert.ok(lesson.exercises.some(ex => ex.title.includes('כיול גובה 80 ס״מ')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('סריקה דו־שלבית')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyUp(120);')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyDown(60);')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('לא מחברים רחפן')));
  assertIncludes(lesson.deliverable, 'Reactor_Survey_GroupX');
  assertIncludes(lesson.visualDiagram.src, 'reactor-vertical-scan.svg');
  assertIncludes(lesson.visualDiagram.caption, 'ס״מ');
  assert.doesNotMatch(JSON.stringify(lesson), /אינץ|inch|inches/i);
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 1 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
  const lessonOneSvg = readFileSync(new URL(lesson.visualDiagram.src, root), 'utf8');
  assertIncludes(lessonOneSvg, '80 ס״מ');
  assertIncludes(lessonOneSvg, '120 ס״מ');
  assert.doesNotMatch(lessonOneSvg, /אינץ|inch|inches/i);
});

test('Drone Intelligence Lab lesson 2 implements the Thermal Shield Box Mission comparison plan', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[1];
  assertIncludes(lesson.title, 'Thermal Shield Box Mission');
  assertIncludes(lesson.concept, 'Strafing מול Yaw');
  assertIncludes(lesson.story, 'Perceptual Robotics');
  assertIncludes(lesson.mission, 'שתי גרסאות JavaScript');
  assertIncludes(lesson.mission, '150 ס״מ');
  assert.equal(lesson.physicalFlightAllowed, false);
  assert.equal(lesson.workspaceMode, 'droneblocks-app');
  assert.equal(lesson.presentationMode, 'focused');
  assert.ok(lesson.blocks.includes('flyForward'));
  assert.ok(lesson.blocks.includes('flyRight'));
  assert.ok(lesson.blocks.includes('flyBackward'));
  assert.ok(lesson.blocks.includes('flyLeft'));
  assert.ok(lesson.blocks.includes('yawRight'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assertIncludes(lesson.lessonFlow[1].teacher, 'Perceptual Robotics');
  assertIncludes(lesson.lessonFlow[2].title, 'Pitch/Roll/Yaw');
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Strafing Box 150 ס״מ')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Yaw Box 150 ס״מ')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyRight(150);')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyForward(150);')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.yawRight(90);')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('סימולטור בלבד')));
  assertIncludes(lesson.deliverable, 'Meeting2_BoxMission_[TeamName]');
  assertIncludes(lesson.assessment[0], '150 ס״מ');
  assertIncludes(lesson.visualDiagram.src, 'thermal-shield-box-mission.svg');
  assertIncludes(lesson.visualDiagram.caption, '150 ס״מ');
  assert.doesNotMatch(JSON.stringify(lesson), /אינץ|inch|inches/i);
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 2 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
  const lessonTwoSvg = readFileSync(new URL(lesson.visualDiagram.src, root), 'utf8');
  assertIncludes(lessonTwoSvg, '150 ס״מ');
  assert.doesNotMatch(lessonTwoSvg, /אינץ|inch|inches/i);
});

test('Drone Intelligence Lab lesson 3 implements the Mars Simulator cloud and 3D scan plan', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[2];
  assertIncludes(lesson.title, 'Mars Seismic Scan');
  assertIncludes(lesson.concept, 'Mars Simulator');
  assertIncludes(lesson.story, 'NASA JPL');
  assertIncludes(lesson.story, 'ESA');
  assertIncludes(lesson.mission, 'סימולטור Mars בלבד');
  assertIncludes(lesson.mission, '150 ס״מ');
  assertIncludes(lesson.mission, '250 ס״מ');
  assertIncludes(lesson.mission, '220 ס״מ');
  assert.equal(lesson.physicalFlightAllowed, false);
  assert.equal(lesson.workspaceMode, 'droneblocks-app');
  assert.equal(lesson.presentationMode, 'focused');
  assert.ok(lesson.blocks.includes('flyUp'));
  assert.ok(lesson.blocks.includes('flyDown'));
  assert.ok(lesson.blocks.includes('flyForward'));
  assert.ok(lesson.blocks.includes('yawRight'));
  assert.ok(lesson.blocks.includes('sleep'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assertIncludes(lesson.lessonFlow[1].teacher, 'NASA JPL');
  assertIncludes(lesson.lessonFlow[2].title, 'אטמוספירת מאדים');
  assert.ok(lesson.exercises.some(ex => ex.title.includes('ענן לפני קוד')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('רכס וסייסמוגרף')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyUp(150);')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyForward(250);')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyDown(70);')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyUp(140);')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyForward(300);')));
  assert.ok(lesson.debugging.some(bug => bug.problem.includes('Mars Simulator')));
  assertIncludes(lesson.deliverable, 'Mars_Seismic_Scan_TeamX');
  assertIncludes(lesson.visualDiagram.src, 'mars-seismic-scan.svg');
  assertIncludes(lesson.visualDiagram.caption, '220 ס״מ');
  assert.doesNotMatch(JSON.stringify(lesson), /אינץ|inch|inches/i);
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 3 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
  const lessonThreeSvg = readFileSync(new URL(lesson.visualDiagram.src, root), 'utf8');
  assertIncludes(lessonThreeSvg, '150 ס״מ');
  assertIncludes(lessonThreeSvg, '80 ס״מ');
  assertIncludes(lessonThreeSvg, '220 ס״מ');
  assertIncludes(lessonThreeSvg, 'flyForward(250)');
  assert.doesNotMatch(lessonThreeSvg, /אינץ|inch|inches|50״|140״/i);
});

test('Drone Intelligence Lab lesson 4 implements the metric Methane LoopScan variables and for loop plan', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[3];
  assertIncludes(lesson.title, 'Methane LoopScan');
  assertIncludes(lesson.concept, 'שיטה מטרית');
  assertIncludes(lesson.story, 'מטמנת דודאים');
  assertIncludes(lesson.mission, 'לולאת for');
  assertIncludes(lesson.mission, 'City Simulator או Minimal Grid');
  assert.equal(lesson.physicalFlightAllowed, false);
  assert.equal(lesson.workspaceMode, 'droneblocks-app');
  assert.equal(lesson.presentationMode, 'focused');
  assert.ok(lesson.blocks.includes('variable'));
  assert.ok(lesson.blocks.includes('loop'));
  assert.ok(lesson.blocks.includes('flyRight'));
  assert.ok(lesson.blocks.includes('condition'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('פירוק for')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('אתגר שינוי מטרי')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let scanLength = 150;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('for (let i = 0; i < 2; i++)')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('if (i < 1)')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('סנטימטרים')));
  assert.ok(lesson.instructorSlides.some(slide => slide.title.includes('אתגר מתאן בדודאים')));
  assertIncludes(lesson.deliverable, 'Meeting4_Methane_Loop_Grade9');
  assertIncludes(lesson.visualDiagram.src, 'methane-loop-scan.svg');
  assertIncludes(lesson.visualDiagram.caption, '220/130');
  assert.doesNotMatch(JSON.stringify(lesson), /אינץ|inch|inches/i);
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 4 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
  const lessonFourSvg = readFileSync(new URL(lesson.visualDiagram.src, root), 'utf8');
  assertIncludes(lessonFourSvg, '150');
  assertIncludes(lessonFourSvg, '80');
  assertIncludes(lessonFourSvg, '100');
  assert.doesNotMatch(lessonFourSvg, /אינץ|inch|inches/i);
});

test('Drone Intelligence Lab lesson 5 implements the first physical SpaceX Static Fire safety gate', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[4];
  assertIncludes(lesson.title, 'SpaceX Static Fire');
  assertIncludes(lesson.concept, 'הטסה פיזית ראשונה');
  assertIncludes(lesson.story, 'SpaceX');
  assertIncludes(lesson.mission, 'WiFi Handshake');
  assert.equal(lesson.physicalFlightAllowed, true);
  assert.equal(lesson.workspaceMode, 'physical-lab');
  assert.ok(lesson.blocks.includes('safety_check'));
  assert.ok(lesson.blocks.includes('wifi'));
  assert.ok(lesson.blocks.includes('battery'));
  assert.ok(lesson.blocks.includes('abort'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Pre‑Flight')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Static Fire')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let sideLength = 100;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyUp(safeAltitude);')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('מלבן הטיסה')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('סוללה')));
  assertIncludes(lesson.deliverable, 'Meeting5_Static_Fire_Calibrated_v2');
  assertIncludes(lesson.visualDiagram.src, 'spacex-static-fire-safe-zone.svg');
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 5 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
});

test('Drone Intelligence Lab lesson 6 implements the Mars if/else dynamic decision plan', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[5];
  assertIncludes(lesson.title, 'Mars Mission Logic');
  assertIncludes(lesson.concept, 'Boolean');
  assertIncludes(lesson.story, 'NASA JPL');
  assertIncludes(lesson.mission, 'stormLevel');
  assert.equal(lesson.physicalFlightAllowed, false);
  assert.equal(lesson.workspaceMode, 'droneblocks-code');
  assert.ok(lesson.blocks.includes('condition'));
  assert.ok(lesson.blocks.includes('variable'));
  assert.ok(lesson.blocks.includes('flyRight'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('= מול ==')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Storm Challenge')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let stormLevel = 1;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('if (stormLevel == 1)')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('else if (stormLevel == 2)')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyRight(emergencyDistance);')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('סימולטור בלבד')));
  assertIncludes(lesson.deliverable, 'Meeting6_Mars_Logic_Grade9');
  assertIncludes(lesson.visualDiagram.src, 'mars-storm-decision-logic.svg');
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 6 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
});

test('Drone Intelligence Lab lesson 7 implements the Helical 3D city scanning plan', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[6];
  assertIncludes(lesson.title, 'Helical 3D Scan');
  assertIncludes(lesson.concept, '3D Helical Scanning');
  assertIncludes(lesson.story, 'Pix4D');
  assertIncludes(lesson.mission, 'City בלבד');
  assert.equal(lesson.physicalFlightAllowed, false);
  assert.equal(lesson.workspaceMode, 'droneblocks-code');
  assert.ok(lesson.blocks.includes('loop'));
  assert.ok(lesson.blocks.includes('flyUp'));
  assert.ok(lesson.blocks.includes('flyForward'));
  assert.ok(lesson.blocks.includes('yawRight'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('חישוב 8 צלעות')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('3D Calibration Challenge')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let scanDistance = 120;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let altitudeStep = 30;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('for (let i = 0; i < 8; i++)')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.flyUp(altitudeStep);')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('סימולטור בלבד')));
  assertIncludes(lesson.deliverable, 'Meeting7_3D_Spiral_Scan_Calibrated');
  assertIncludes(lesson.visualDiagram.src, 'helical-3d-building-scan.svg');
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 7 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
});

test('Drone Intelligence Lab lesson 8 implements the physical dynamic obstacle debugging challenge', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[7];
  assertIncludes(lesson.title, 'Dynamic Obstacles Challenge');
  assertIncludes(lesson.concept, 'Telemetry');
  assertIncludes(lesson.story, 'Zipline');
  assertIncludes(lesson.mission, '10 דקות');
  assert.equal(lesson.physicalFlightAllowed, true);
  assert.equal(lesson.workspaceMode, 'physical-lab');
  assert.ok(lesson.blocks.includes('telemetry'));
  assert.ok(lesson.blocks.includes('battery'));
  assert.ok(lesson.blocks.includes('abort'));
  assert.ok(lesson.blocks.includes('variable'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('שמירת v1')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Dynamic Debug')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let obstacleDistance = 120;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('clearanceAltitude = 130')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('Safe Fly Zone')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('30%')));
  assertIncludes(lesson.deliverable, 'Meeting8_Dynamic_Challenge_Solved');
  assertIncludes(lesson.visualDiagram.src, 'dynamic-obstacle-debug-challenge.svg');
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 8 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
});

test('Drone Intelligence Lab lesson 9 implements the physical telemetry performance tuning data lab', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[8];
  assertIncludes(lesson.title, 'Wing Performance Tuning');
  assertIncludes(lesson.concept, 'Battery Optimization');
  assertIncludes(lesson.story, 'Wing');
  assertIncludes(lesson.mission, 'Battery Burn Rate');
  assert.equal(lesson.physicalFlightAllowed, true);
  assert.equal(lesson.workspaceMode, 'physical-lab');
  assert.ok(lesson.blocks.includes('telemetry'));
  assert.ok(lesson.blocks.includes('battery'));
  assert.ok(lesson.blocks.includes('loop'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Burn Rate')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Algorithm A')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Algorithm B')));
  assert.ok(lesson.codeSamples.some(sample => sample.title.includes('Algorithm A') && sample.code.includes('tello.sleep(5);')));
  assert.ok(lesson.codeSamples.some(sample => sample.title.includes('Algorithm B') && sample.code.includes('for (let i = 0; i < 4; i++)')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('Burn Rate = ΔBattery / Total Time')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('חצי־פיזי')));
  assertIncludes(lesson.deliverable, 'Meeting9_Algorithm_Perfect_v3');
  assertIncludes(lesson.visualDiagram.src, 'performance-tuning-data-lab.svg');
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 9 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
});

test('Drone Intelligence Lab lesson 10 implements the IAI project blueprint planning lesson', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[9];
  assertIncludes(lesson.title, 'IAI Project Blueprint');
  assertIncludes(lesson.concept, 'System Design');
  assertIncludes(lesson.story, 'Israel Aerospace Industries');
  assertIncludes(lesson.mission, 'טאבלטים הפוכים');
  assert.equal(lesson.physicalFlightAllowed, false);
  assert.equal(lesson.workspaceMode, 'project-workflow');
  assert.ok(lesson.blocks.includes('function'));
  assert.ok(lesson.blocks.includes('condition'));
  assert.ok(lesson.blocks.includes('project'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('טאבלטים הפוכים')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Helper Function')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('function patrolZone(sides, distance)')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let intrusionDetected = false;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('patrolZone(4, scanDistance);')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('אין הטסה פיזית')));
  assertIncludes(lesson.deliverable, 'Meeting10_IAI_Project_Final_Blueprint');
  assertIncludes(lesson.visualDiagram.src, 'iai-project-blueprint.svg');
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 10 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
});

test('Drone Intelligence Lab lesson 11 implements the full physical Launchpad Flight Testing photo calibration lab', () => {
  const lesson = data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS[10];
  assertIncludes(lesson.title, 'Launchpad Flight Testing');
  assertIncludes(lesson.concept, 'Visual Telemetry');
  assertIncludes(lesson.concept, 'Motion Blur');
  assertIncludes(lesson.story, 'NASA JPL');
  assertIncludes(lesson.story, 'I‑A‑I');
  assertIncludes(lesson.mission, '150×150 ס״מ');
  assertIncludes(lesson.mission, 'Meeting11_IAI_Flight_Testing_Calibrated_v2');
  assert.equal(lesson.physicalFlightAllowed, true);
  assert.equal(lesson.workspaceMode, 'physical-lab');
  assert.equal(lesson.presentationMode, 'focused');
  assert.ok(lesson.blocks.includes('photo'));
  assert.ok(lesson.blocks.includes('wifi'));
  assert.ok(lesson.blocks.includes('battery'));
  assert.ok(lesson.blocks.includes('debug'));
  assert.ok(lesson.lessonFlow.length >= 9);
  assert.ok(lesson.exercises.some(ex => ex.title.includes('WiFi Handshake')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Visual Telemetry')));
  assert.ok(lesson.exercises.some(ex => ex.title.includes('Calibration')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('function scanAndPhoto(sides, distance)')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('tello.takePhoto();')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let scanDistance = 150;')));
  assert.ok(lesson.codeSamples.some(sample => sample.code.includes('let safeAltitude = 110;')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('משקפי מגן')));
  assert.ok(lesson.safetyRules.some(rule => rule.includes('נוהל שתי קופסאות')));
  assertIncludes(lesson.deliverable, '3 תמונות חדות');
  assertIncludes(lesson.deliverable, 'I‑A‑I');
  assertIncludes(lesson.deliverable, 'Meeting11_IAI_Flight_Testing_Calibrated_v2');
  assertIncludes(lesson.visualDiagram.src, 'project-v1-integration-lab.svg');
  assertIncludes(lesson.visualDiagram.caption, '150×150 ס״מ');
  assert.ok(existsSync(new URL(lesson.visualDiagram.src, root)), 'lesson 11 visual diagram asset should exist');
  assert.ok(lesson.screenshotSlides.some(shot => shot.src === lesson.visualDiagram.src));
  const lessonElevenSvg = readFileSync(new URL(lesson.visualDiagram.src, root), 'utf8');
  assertIncludes(lessonElevenSvg, '150 ס״מ');
  assertIncludes(lessonElevenSvg, 'I‑A‑I');
  assertIncludes(lessonElevenSvg, 'Motion Blur');
});

test('Drone Intelligence Lab pages are linked from homepage and use the hybrid model', () => {
  assertIncludes(homepageHtml, 'Drone Intelligence Lab');
  assertIncludes(homepageHtml, 'href="drone-intelligence-lab-grade9.html"');
  assertIncludes(homepageHtml, 'href="drone-intelligence-lab-grade9-play.html?lesson=1"');
  assertIncludes(courseHtml, 'Drone Intelligence Lab');
  assertIncludes(courseHtml, 'משימות חכמות וניתוח שטח');
  assertIncludes(courseHtml, 'js/drone-intelligence-lab-grade9-lessons.js');
  assertIncludes(courseHtml, 'drone-intelligence-lab-grade9-slides.html?lesson=1');
  assertIncludes(courseHtml, 'drone-intelligence-lab-grade9-guide.html?lesson=1');
  assertIncludes(playHtml, 'window.getDroneIntelligenceLabGrade9Lesson');
  assertIncludes(playHtml, 'DroneBlocks Code בטאבלט');
  assertIncludes(playHtml, 'Drone Intelligence ט׳');
  assertIncludes(playHtml, 'לכיתה ט׳ עתודה');
  assertIncludes(playHtml, 'renderAppWorkflow');
  assertIncludes(slidesHtml, 'מצגת הקרנה — Drone Intelligence Lab כיתה ט׳ עתודה');
  assertIncludes(guideHtml, 'מערך מדריך — Drone Intelligence Lab');
  assertIncludes(guideHtml, 'זירת משימה וקוד לדוגמה');
});

test('Drone Intelligence Lab course page has sky and flight effect styling', () => {
  assertIncludes(courseHtml, 'linear-gradient(180deg,#6dd5ff');
  assertIncludes(courseHtml, '@keyframes skyDrift');
  assertIncludes(courseHtml, '@keyframes flyAcross');
  assertIncludes(courseHtml, 'body:after');
  assertIncludes(courseHtml, '🚁');
});

test('Drone Intelligence Lab lesson model is ready for future full lesson production', () => {
  for (const lesson of data.DRONE_INTELLIGENCE_LAB_GRADE9_LESSONS) {
    assert.ok(lesson.lessonFlow.length >= 7, `lesson ${lesson.id} should have 90 minute flow`);
    assert.ok(lesson.exercises.length >= 7, `lesson ${lesson.id} should have scaffold exercises`);
    assert.ok(lesson.successCriteria.length >= 5, `lesson ${lesson.id} should have success criteria`);
    assert.ok(lesson.instructorGuide?.pedagogy?.length >= 3, `lesson ${lesson.id} should have instructor pedagogy notes`);
    assert.ok(lesson.appWorkflow?.length >= 4, `lesson ${lesson.id} should have external app workflow`);
  }
});
