import { readFileSync } from 'node:fs';
import { strict as assert } from 'node:assert';
import vm from 'node:vm';

const root = new URL('../', import.meta.url);
const read = path => readFileSync(new URL(path, root), 'utf8');

const dataCode = read('js/webcode-lessons.js');
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(dataCode, sandbox);

const lessons = sandbox.window.WEBCODE_LESSONS;
assert.equal(Array.isArray(lessons), true, 'lessons array exists');
assert.equal(lessons.length, 30, 'WebCode course includes thirty lessons');
assert.deepEqual(Array.from(lessons, l => l.id), Array.from({ length: 30 }, (_, i) => i + 1), 'lesson ids are sequential 1-30');
lessons.forEach(lessonItem => {
  assert.equal(lessonItem.durationMinutes, 90, `lesson ${lessonItem.id} is framed as 90 minutes`);
  assert.ok(lessonItem.starter?.html?.includes('<main'), `lesson ${lessonItem.id} has starter HTML`);
  assert.ok(lessonItem.starter?.css?.includes('background'), `lesson ${lessonItem.id} has starter CSS`);
  assert.ok(lessonItem.starter?.js?.includes('function'), `lesson ${lessonItem.id} has starter JavaScript`);
  assert.ok(lessonItem.lessonFlow.length >= 7, `lesson ${lessonItem.id} has a full guide flow`);
  const minimumExercises = [6, 7, 8, 9].includes(lessonItem.id) ? 6 : [2, 4, 5].includes(lessonItem.id) ? 7 : 8;
  assert.ok(lessonItem.exercises.length >= minimumExercises, `lesson ${lessonItem.id} has enough exercises`);
  assert.ok(lessonItem.vocabulary.length >= 4, `lesson ${lessonItem.id} has vocabulary`);
});

const lesson = lessons[0];
assert.equal(lesson.durationMinutes, 90, 'lesson is framed as 90 minutes');
assert.ok(lesson.title.includes('עמוד אמיתי') && lesson.title.includes('Blockly'), 'lesson has concise real Blockly page-builder title');
assert.ok(lesson.starter.html.includes('<button onclick="sayHello()">'), 'starter has working button');
assert.ok(lesson.starter.css.includes('border-radius'), 'starter includes visible styling');
assert.ok(lesson.starter.js.includes('getElementById("message")'), 'starter JS targets message id');
assert.ok(lesson.exercises.length >= 8, 'lesson includes many exercises');
assert.ok(lesson.lessonFlow.length >= 7, 'lesson includes full 90-minute guide flow');
assert.ok(lesson.vocabulary.some(v => v[0] === 'HTML'), 'vocabulary includes HTML');
assert.ok(lesson.vocabulary.some(v => v[0] === 'CSS'), 'vocabulary includes CSS');
assert.ok(lesson.vocabulary.some(v => v[0] === 'JavaScript'), 'vocabulary includes JavaScript');
assert.equal(lesson.mode, 'Real Blockly page builder', 'lesson 1 uses a real Blockly page builder');
assert.equal(lesson.realBlocklyBuilder, true, 'lesson 1 enables real Blockly workspace');
assert.ok(lesson.exercises.some(ex => ex.prompt.includes('גררו')), 'lesson 1 exercises require dragging blocks');

const lesson2 = lessons[1];
assert.equal(lesson2.durationMinutes, 90, 'lesson 2 is framed as 90 minutes');
assert.ok(lesson2.title.includes('סטודיו עיצוב'), 'lesson 2 focuses on real Blockly design studio');
assert.equal(lesson2.mode, 'Real Blockly design studio', 'lesson 2 uses real Blockly design studio mode');
assert.equal(lesson2.realBlocklyBuilder, true, 'lesson 2 enables real Blockly workspace');
assert.ok(lesson2.exercises.some(ex => ex.title.includes('Hover')), 'lesson 2 includes hover design exercise');
assert.ok(lesson2.exercises[0].title.includes('מתחילים פשוט'), 'lesson 2 starts simple before adding design blocks');
assert.equal(lesson2.exercises.length, 7, 'lesson 2 keeps only the non-redundant design exercises');
assert.ok(lesson2.vocabulary.some(v => v[0] === 'hover'), 'lesson 2 vocabulary includes hover');

const lesson3 = lessons[2];
assert.equal(lesson3.durationMinutes, 90, 'lesson 3 is framed as 90 minutes');
assert.equal(lesson3.title, 'כפתורים ופעולות קסם עם Blockly', 'lesson 3 title is clear and natural Hebrew');
assert.ok(lesson3.starter.html.includes('onclick="makeHappy()"'), 'lesson 3 has onclick event');
assert.ok(lesson3.starter.js.includes('classList.toggle("magic")'), 'lesson 3 includes classList toggle');
assert.ok(lesson3.exercises.length >= 8, 'lesson 3 includes many exercises');
assert.ok(!lesson3.exercises[0].prompt.includes('הרצה'), 'lesson 3 exercise 1 does not ask for a missing Run button');
assert.ok(lesson3.exercises[0].prompt.includes('כפתור “הפעילו קסם”') && lesson3.exercises[0].prompt.includes('בתצוגה החיה בצד שמאל'), 'lesson 3 exercise 1 points learners to the named live preview button');
assert.equal(lesson3.exercises[0].check.requiresPreviewButtonText, 'הפעילו קסם', 'lesson 3 exercise 1 requires clicking the preview magic button');
assert.ok(!lesson3.exercises[1].prompt.includes('הרצה'), 'lesson 3 exercise 2 does not ask for a missing Run button');
assert.equal(JSON.stringify(lesson3.exercises[1].check.changedBlocklyFields), JSON.stringify([{ type: 'web_button', field: 'LABEL', defaultValue: 'הפעילו קסם' }]), 'lesson 3 exercise 2 now requires changing only the visible button label');
assert.ok(!lesson3.exercises[1].check.unchangedBlocklyFields, 'lesson 3 exercise 2 no longer treats the button as the message-control block');
assert.ok(lesson3.exercises[1].hint.includes('בלוק “כפתור” קובע מה כתוב על הכפתור') && lesson3.exercises[1].hint.includes('בלוק פעולה'), 'lesson 3 exercise 2 explains button label versus click action');
assert.equal(lesson3.exercises[1].check.requiresPreviewButtonClick, true, 'lesson 3 exercise 2 requires trying the renamed preview button');
assert.equal(lesson3.exercises[2].check.requiresCodePeek, true, 'lesson 3 exercise 3 requires opening generated code peek');
assert.equal(lesson3.exercises[2].check.requiresCodeSelectionTab, 'html', 'lesson 3 exercise 3 requires HTML generated-code selection');
assert.deepEqual(Array.from(lesson3.exercises[2].check.requiresCodeSelectionBlockTypes), ['web_button'], 'lesson 3 exercise 3 requires selecting the button block');
assert.ok(lesson3.exercises[2].answerBox?.label.includes('מילת קוד') && lesson3.exercises[2].check.requiresCodeLineAnswer?.requiredSnippets?.includes('button') && lesson3.exercises[2].check.requiresCodeLineAnswer?.requiredSnippets?.includes('id') && lesson3.exercises[2].check.requiresCodeLineAnswer?.requiredSnippets?.includes('onclick'), 'lesson 3 exercise 3 accepts short code words actually visible in the selected HTML button line, including button, id, and onclick');
assert.equal(JSON.stringify(lesson3.exercises[3].check.changedBlocklyFields), JSON.stringify([{ type: 'web_action_message', field: 'TEXT', defaultValue: 'הודעה חדשה מהפעולה ✨' }]), 'lesson 3 exercise 4 requires changing the action-message text, separately from the button label');
assert.ok(lesson3.exercises[3].hint.includes('בלוק פעולה') && lesson3.exercises[3].hint.includes('message.textContent'), 'lesson 3 exercise 4 explains that click-message behavior belongs to the action block');
assert.equal(lesson3.exercises[3].check.requiresPreviewButtonText, 'הפעילו קסם', 'lesson 3 exercise 4 requires pressing the preview button after changing message');
assert.equal(lesson3.exercises[3].check.requiresPreviewMessageChangedFrom, 'כאן תופיע הודעה מהכפתור...', 'lesson 3 exercise 4 requires visible preview message change');
assert.ok(lesson3.exercises[3].check.blockFeedback.includes('חסר בלוק'), 'lesson 3 exercise 4 gives specific missing-action-block feedback');
assert.ok(lesson3.exercises[4].check.changedBlocklyFields?.some(rule => rule.type === 'web_action_emoji' && rule.field === 'EMOJI' && rule.defaultValue === '🤖'), 'lesson 3 exercise 5 requires changing the action emoji from default');
assert.equal(lesson3.exercises[4].check.requiresPreviewEmojiChangedFrom, '✨', 'lesson 3 exercise 5 requires the visible emoji to change in preview');
assert.ok(lesson3.exercises[5].check.changedBlocklyFieldsFromBaseline?.some(rule => rule.type === 'web_action_background' && rule.field === 'BG'), 'lesson 3 exercise 6 requires changing the background action from the entry baseline');
assert.equal(lesson3.exercises[5].check.ensureStarterBlocks?.[0]?.type, 'web_action_background', 'lesson 3 exercise 6 auto-adds the required background action block when missing');
assert.equal(lesson3.exercises[5].check.ensureStarterBlocks?.[0]?.after, 'web_button', 'lesson 3 exercise 6 inserts the background action after the button');
assert.equal(lesson3.exercises[5].check.exactBlockTypeCounts?.web_action_background, 1, 'lesson 3 exercise 6 rejects adding a second background action block');
assert.equal(lesson3.exercises[5].check.requiresPreviewButtonText, 'הפעילו קסם', 'lesson 3 exercise 6 requires pressing the preview button');
assert.equal(lesson3.exercises[6].check.requiresPreviewCardClass, 'magic', 'lesson 3 exercise 7 requires the preview card to enter magic mode');
assert.equal(lesson3.exercises[7].check.requiresCodeSelectionTab, 'js', 'lesson 3 exercise 8 requires selecting generated JavaScript');
assert.ok(lesson3.exercises[7].check.requiresCodeSelectionBlockTypes?.includes('web_action_emoji'), 'lesson 3 exercise 8 requires selecting an action block');
assert.ok(lesson3.exercises[3].check.fieldFeedback.includes('שנו את הטקסט'), 'lesson 3 exercise 4 gives specific unchanged-text feedback');
assert.ok(lesson3.vocabulary.some(v => v[0] === 'onclick'), 'lesson 3 vocabulary includes onclick');

const lessons4to24 = lessons.slice(3, 24);
lessons4to24.forEach(lessonItem => {
  assert.equal(lessonItem.realBlocklyBuilder, true, `lesson ${lessonItem.id} uses real draggable Blockly blocks`);
  assert.equal(lessonItem.blocklyLessonBuilder, true, `lesson ${lessonItem.id} uses the lesson-specific Blockly builder`);
  assert.equal(lessonItem.bridgeBlocks.length, 0, `lesson ${lessonItem.id} does not expose legacy helper/code-card buttons`);
  assert.ok(lessonItem.mode.includes('Real Blockly full rework'), `lesson ${lessonItem.id} is marked as a full real Blockly rework`);
  assert.ok(lessonItem.progressionStage.includes('בלוקים אמיתיים'), `lesson ${lessonItem.id} stays in the block-first phase`);
  assert.ok(lessonItem.blocklyBlocks.length >= 5, `lesson ${lessonItem.id} has several draggable lesson blocks`);
  assert.ok(lessonItem.blocklyBlocks.some(block => block.args0?.length), `lesson ${lessonItem.id} has editable fields/dropdowns inside lesson blocks`);
  assert.equal(lessonItem.exercises.length, [6, 8, 9].includes(lessonItem.id) ? 6 : [4, 5, 7].includes(lessonItem.id) ? 7 : 8, `lesson ${lessonItem.id} has the reviewed exercise count`);
  lessonItem.exercises.forEach(ex => {
    assert.ok(ex.prompt.includes('בלוק') || ex.prompt.includes('תצוגה') || ex.prompt.includes('קוד שנוצר') || ex.prompt.includes('תיבת הקוד'), `lesson ${lessonItem.id} exercise ${ex.id} is phrased around blocks/preview/generated code`);
    assert.ok(ex.noCheck || (ex.check && Object.keys(ex.check).length > 0), `lesson ${lessonItem.id} exercise ${ex.id} has a validator or is explicitly no-check`);
  });
  assert.ok(!lessonItem.exercises[0].prompt.includes('הריצו'), `lesson ${lessonItem.id} exercise 1 is not a fake run-the-already-running-preview task`);
  assert.ok(lessonItem.exercises[0].check.blockTypes?.length, `lesson ${lessonItem.id} exercise 1 requires a real block action`);
  const blockChecks = lessonItem.exercises.filter(ex => ex.check.blockTypes?.length);
  assert.ok(blockChecks.length >= (lessonItem.id === 4 ? 5 : [6, 8, 9].includes(lessonItem.id) ? 5 : lessonItem.id === 7 ? 6 : 6), `lesson ${lessonItem.id} requires connected Blockly blocks in most exercises`);
  const final = lessonItem.exercises.at(-1).check;
  if (lessonItem.id !== 4) {
    assert.equal(final.requiresCodePeek, true, `lesson ${lessonItem.id} final exercise requires generated-code peek`);
    assert.ok(final.requiresCodeSelectionBlockTypes?.length >= 1, `lesson ${lessonItem.id} final exercise requires selecting a connected generated-code block`);
  }
});

const lesson4 = lessons[3];
assert.equal(lesson4.durationMinutes, 90, 'lesson 4 is framed as 90 minutes');
assert.ok(lesson4.title.includes('קלט'), 'lesson 4 focuses on user input');
assert.ok(lesson4.title.includes('ברכות'), 'lesson 4 is framed as a fun personal generator');
assert.ok(lesson4.starter.html.includes('id="nameInput"'), 'lesson 4 has name input');
assert.ok(lesson4.starter.js.includes('.value'), 'lesson 4 reads input value');
assert.ok(lesson4.exercises[0].prompt.includes('גררו') && lesson4.exercises[0].check.blockTypes?.includes('lesson_4_name_label'), 'lesson 4 uses a draggable block for the first input-label change');
assert.ok(lesson4.exercises[1].check.blockTypes?.includes('lesson_4_topic_label'), 'lesson 4 uses a draggable block for the topic-label change');
assert.ok(lesson4.exercises[3].prompt.includes('לחצו על כפתור הברכה'), 'lesson 4 result-sentence exercise tells learners to press the preview button');
assert.equal(lesson4.exercises[3].check.requiresPreviewButtonClick, true, 'lesson 4 result-sentence exercise requires pressing the preview button');
assert.ok(lesson4.exercises[3].check.requiresPreviewResultFromBlockOutput?.some(rule => rule.type === 'lesson_4_sentence'), 'lesson 4 result-sentence exercise checks the preview result contains the generated sentence text');
const lesson4EndingBlock = lesson4.blocklyBlocks.find(block => block.type === 'lesson_4_result_word');
assert.equal(lesson4EndingBlock.label, 'אימוג׳י סיום בתוצאה', 'lesson 4 ending block is named for the emoji it changes');
assert.equal(lesson4EndingBlock.find, 'רעיונות נוצצים 🚀', 'lesson 4 ending block finds the actual starter result ending');
assert.equal(lesson4EndingBlock.replace, 'רעיונות נוצצים {{TEXT}}', 'lesson 4 ending block replaces the visible result ending');
assert.ok(lesson4.exercises[4].check.requiresPreviewResultFromBlockOutput?.some(rule => rule.type === 'lesson_4_result_word'), 'lesson 4 ending block exercise checks the visible preview result');
assert.equal(lesson4.exercises.length, 7, 'lesson 4 keeps the generated-code reading exercise plus optional challenge');
assert.equal(lesson4.exercises[5].check.requiresCodePeek, true, 'lesson 4 generated-code reading exercise requires opening code peek');
assert.ok(lesson4.exercises[5].check.jsIncludes?.includes('getElementById("nameInput").value'), 'lesson 4 generated-code reading exercise checks the nameInput value line exists');
assert.equal(lesson4.exercises.at(-1).optional, true, 'lesson 4 final challenge is optional/skippable');
assert.ok(['lesson_4_name_label','lesson_4_topic_label','lesson_4_button_text','lesson_4_sentence','lesson_4_result_word'].every(type => lesson4.exercises.at(-1).blocklyStarterXml?.includes(type)), 'lesson 4 optional challenge provides the full connected starter block program to fix');
assert.equal(lesson4.exercises.at(-1).check.exactBlocklyFields?.[0]?.value, '🎉', 'lesson 4 optional challenge checks the exact starter-block fix');
assert.ok(lesson4.vocabulary.some(v => v[0] === 'input'), 'lesson 4 vocabulary includes input');

const lesson5 = lessons[4];
assert.equal(lesson5.durationMinutes, 90, 'lesson 5 is framed as 90 minutes');
assert.ok(lesson5.title.includes('חידון'), 'lesson 5 focuses on quiz building');
assert.ok(lesson5.starter.html.includes('answerInput'), 'lesson 5 uses a text input so quizzes are not limited to yes/no choices');
assert.ok(!lesson5.starter.html.includes("chooseAnswer('yes')"), 'lesson 5 no longer uses fixed yes/no choices');
assert.ok(lesson5.starter.js.includes('const answer = document.getElementById("answerInput").value.trim()'), 'lesson 5 reads the typed answer from the preview');
assert.ok(lesson5.starter.js.includes('if (answer === "CSS")'), 'lesson 5 includes a text-answer if condition');
assert.ok(lesson5.starter.js.includes('else'), 'lesson 5 includes else branch');
assert.ok(lesson5.exercises[0].check.blocklyFieldsContaining?.some(rule => rule.type === 'lesson_5_question' && rule.field === 'TEXT' && rule.includes === '?'), 'lesson 5 question exercise requires a question mark in the question text');
const lesson5AnswerBlock = lesson5.blocklyBlocks.find(block => block.type === 'lesson_5_answer');
assert.ok(lesson5AnswerBlock?.args0?.some(arg => arg.type === 'field_input' && arg.name === 'TEXT'), 'lesson 5 correct-answer block is free text, not a dropdown');
assert.ok(!lesson5AnswerBlock?.args0?.some(arg => arg.type === 'field_dropdown'), 'lesson 5 correct-answer block avoids limiting answers to dropdown options');
assert.ok(lesson5.exercises[1].check.nonEmptyBlocklyFields?.some(rule => rule.type === 'lesson_5_answer' && rule.field === 'TEXT'), 'lesson 5 answer exercise rejects empty answers');
assert.ok(lesson5.exercises[1].check.generatedBlockOutputs?.some(rule => rule.type === 'lesson_5_answer' && rule.target === 'js'), 'lesson 5 answer exercise checks the generated JS condition matches the typed block value');
assert.equal(lesson5.exercises[1].check.requiresPreviewButtonClick, true, 'lesson 5 answer exercise requires trying an answer in the preview');
assert.ok(lesson5.exercises[1].check.requiresPreviewFilledInputs?.includes('answerInput'), 'lesson 5 answer exercise requires typing an answer before checking the preview');
assert.ok(!lesson5.exercises[1].check.requiresPreviewInputMatchesBlockFields, 'lesson 5 answer exercise does not require the preview answer to match the block answer exactly');
assert.ok(!lesson5.exercises[1].check.requiresPreviewFeedbackClass, 'lesson 5 answer exercise does not require the preview answer to be accepted as correct');
const lesson5ButtonColorBlock = lesson5.blocklyBlocks.find(block => block.type === 'lesson_5_button_style');
assert.ok(lesson5ButtonColorBlock?.args0?.[0]?.options?.length <= 6, 'lesson 5 button-color menu adds only a few options');
assert.ok(JSON.stringify(lesson5ButtonColorBlock?.args0?.[0]?.options || []).includes('#2563eb') && JSON.stringify(lesson5ButtonColorBlock?.args0?.[0]?.options || []).includes('#db2777') && JSON.stringify(lesson5ButtonColorBlock?.args0?.[0]?.options || []).includes('#facc15'), 'lesson 5 button-color menu includes three extra useful color choices');
assert.equal(lesson5.exercises.length, 7, 'lesson 5 keeps seven exercises with one short code-writing task at the end');
assert.equal(lesson5.exercises.at(-1).id, 7, 'lesson 5 final exercise is the short code-writing task');
assert.ok(lesson5.exercises.at(-1).check.requiresCodePeek, 'lesson 5 still ends with a generated-code writing exercise');
assert.ok(lesson5.starter.html.includes('id="colorChoice"'), 'lesson 5 includes a separate color choice input for the extra condition');
const lesson5ColorBlock = lesson5.blocklyBlocks.find(block => block.type === 'lesson_5_chosen_background');
assert.ok(lesson5ColorBlock?.replace?.includes('colorChoice === "{{COLOR}}"') && lesson5ColorBlock?.replace?.includes('document.body.style.background = "{{BG}}"'), 'lesson 5 has a flexible separate color condition block that changes the page background');
assert.ok(lesson5ColorBlock?.args0?.some(arg => arg.name === 'COLOR' && arg.options?.length >= 3), 'lesson 5 color condition lets learners choose which color to check, not only red');
assert.ok(lesson5.exercises[2].title.includes('הודעות אם נכון / אחרת'), 'lesson 5 combines success and else message work into one exercise');
assert.ok(lesson5.exercises[2].check.blockTypes?.includes('lesson_5_success') && lesson5.exercises[2].check.blockTypes?.includes('lesson_5_wrong'), 'combined message exercise requires both success and wrong blocks');
assert.ok(lesson5.exercises[3].title.includes('בחירת צבע') && lesson5.exercises[3].check.blockTypes?.includes('lesson_5_chosen_background'), 'lesson 5 exercise 4 adds a flexible separate color-choice condition');
assert.ok(lesson5.exercises[4].title.includes('צבע כפתור') && lesson5.exercises[4].check.blockTypes?.includes('lesson_5_button_style'), 'lesson 5 keeps button-color styling after the new condition');
assert.ok(lesson5.exercises[5].title.includes('דיבאג הודעות') && lesson5.exercises[5].blocklyStarterXml?.includes('כמעט! רמז') && lesson5.exercises[5].blocklyStarterXml?.includes('נכון! JavaScript'), 'lesson 5 exercise 6 is a self-contained debug task with swapped correct/wrong messages');
assert.ok(lesson5.exercises[5].check.exactBlocklyFields?.some(rule => rule.type === 'lesson_5_success' && rule.value.includes('נכון!')) && lesson5.exercises[5].check.exactBlocklyFields?.some(rule => rule.type === 'lesson_5_wrong' && rule.value.includes('כמעט!')), 'lesson 5 debug task requires putting success and wrong messages back in the correct blocks');
assert.ok(lesson5.exercises.at(-1).title.includes('כותבים קטע קוד קצר') && lesson5.exercises.at(-1).answerBox?.label.includes('קוד'), 'lesson 5 final exercise requires writing one short JavaScript condition fragment');
assert.equal(lesson5.exercises.at(-1).check.requiresCodeSelectionTab, 'js', 'lesson 5 final code-writing exercise requires selecting generated JavaScript');
assert.ok(lesson5.exercises.at(-1).check.requiresCodeLineAnswer?.requiredSnippets?.includes('answer ==='), 'lesson 5 final code-writing exercise asks learners to type a short comparison fragment');
assert.ok(!lesson5.exercises[2].check.requiresPreviewInputMatchesBlockFields, 'lesson 5 combined message exercise does not tell learners to copy the correct-answer block text');
assert.equal(lesson5.exercises[2].check.requiresPreviewButtonClick, true, 'lesson 5 combined message exercise still requires trying the quiz in the preview');
assert.ok(lesson5.vocabulary.some(v => v[0] === 'if'), 'lesson 5 vocabulary includes if');
assert.ok(lesson5.vocabulary.some(v => v[0] === 'answer'), 'lesson 5 vocabulary names the typed answer');

const lesson6 = lessons[5];
assert.equal(lesson6.durationMinutes, 90, 'lesson 6 is framed as 90 minutes');
assert.ok(lesson6.title.includes('ניקוד') || lesson6.title.includes('score'), 'lesson 6 focuses on scoring');
assert.ok(lesson6.starter.html.includes("chooseAnswer('yes')"), 'lesson 6 keeps scoring on fixed choices');
assert.ok(!lesson6.starter.html.includes('answerInput'), 'lesson 6 avoids typed-answer matching while teaching score');
assert.ok(lesson6.starter.js.includes('const startScore = 0') && lesson6.starter.js.includes('let score = startScore'), 'lesson 6 initializes score from a reusable starting-score value');
assert.ok(lesson6.starter.js.includes('const pointsForCorrect = 0'), 'lesson 6 starter does not add points before the add-points block is connected');
assert.ok(lesson6.starter.js.includes('pointsForCorrect === 1 ? "נקודה" : "נקודות"'), 'lesson 6 success message uses singular/plural points wording');
assert.ok(lesson6.starter.js.includes('pointsForCorrect === 1 ? "נכון! קיבלת נקודה ⭐"'), 'lesson 6 default success message says נקודה without the number for one point');
assert.ok(lesson6.starter.js.includes('נכון! קיבלת " + pointsForCorrect') && lesson6.starter.js.includes('נקודות'), 'lesson 6 default success message includes the actual points value for multiple points');
assert.ok(!lesson6.starter.js.includes('answeredCorrectly'), 'lesson 6 lets learners press the correct answer repeatedly without anti-spam lockout');
assert.ok(lesson6.starter.js.includes('if (choice === "yes")'), 'lesson 6 correct-answer branch remains simple and repeatable');
assert.ok(lesson6.starter.js.includes('score = startScore;') && lesson6.starter.js.includes('feedback.className = "try-again"'), 'lesson 6 reset button returns to the starting score and clears success state');
assert.ok(lesson6.blocklyBlocks.some(block => block.type === 'lesson_6_start_score'), 'lesson 6 keeps the original starting-score block');
assert.ok(lesson6.exercises[0].prompt.includes('כבר מחובר בקוד ההתחלה') && lesson6.exercises[0].prompt.includes('ערך אחר מ־0'), 'lesson 6 start-score exercise starts with the block connected and asks only for a value change');
assert.ok(lesson6.exercises[0].blocklyStarterXml?.includes('lesson_6_start_score'), 'lesson 6 start-score exercise preloads the starting-score block');
assert.ok(lesson6.exercises[0].check.fieldFeedback.includes('עדיין על 0'), 'lesson 6 start-score error points to the actual required value change');
const lesson6StartScoreBlock = lesson6.blocklyBlocks.find(block => block.type === 'lesson_6_start_score');
const lesson6PlusBlock = lesson6.blocklyBlocks.find(block => block.type === 'lesson_6_plus');
assert.equal(lesson6StartScoreBlock.find, 'const startScore = 0;', 'lesson 6 start-score block changes only the starting score constant');
assert.equal(lesson6StartScoreBlock.replace, 'const startScore = {{N}};', 'lesson 6 start-score block does not change per-answer scoring');
assert.equal(lesson6PlusBlock.find, 'const pointsForCorrect = 0;', 'lesson 6 add-points block changes the points value used by scoring and feedback');
assert.equal(lesson6PlusBlock.replace, 'const pointsForCorrect = {{N}};', 'lesson 6 add-points block keeps scoring and default message in sync');
assert.ok(lesson6.blocklyBlocks.some(block => block.type === 'lesson_6_plus'), 'lesson 6 has a Blockly block for score increment size');
assert.ok(lesson6.blocklyBlocks.some(block => block.type === 'lesson_6_message' && block.find === 'const successMessage = "";'), 'lesson 6 message block overrides the dynamic default success message only when connected');
assert.ok(lesson6.blocklyBlocks.some(block => block.type === 'lesson_6_reset_message' && block.find === 'איפוס ניקוד'), 'lesson 6 reset-label block matches the starter button text');
assert.ok(!lesson6.exercises[1].check.orderedBlockTypes, 'lesson 6 exercise 2 does not contain the score-label ordering rule');
assert.ok(lesson6.exercises[3].prompt.includes('מעל הבלוק “ניקוד התחלתי”'), 'lesson 6 exercise 4 tells learners to connect the score-label block above the starting-score block');
assert.deepEqual(Array.from(lesson6.exercises[3].check.orderedBlockTypes), ['lesson_6_score_label', 'lesson_6_start_score'], 'lesson 6 exercise 4 check requires the same above-start-score order as the prompt');
assert.ok(lesson6.exercises[3].check.orderFeedback.includes('מעל “ניקוד התחלתי”'), 'lesson 6 exercise 4 order feedback matches the prompt');
assert.equal(lesson6.exercises.length, 6, 'lesson 6 removes the weak preview/reset exercises and keeps a shorter flow');
assert.deepEqual(Array.from(lesson6.exercises.map(ex => ex.id)), [1, 2, 3, 4, 5, 6], 'lesson 6 exercises are renumbered after deleting exercises 6 and 7');
assert.equal(lesson6.exercises[5].title, 'תרגיל 6 — בלוק הופך לקוד', 'lesson 6 final generated-code exercise is renumbered to exercise 6');
assert.ok(lesson6.exercises.every(ex => !ex.check.requiresPreviewScoreSum && !ex.check.requiresPreviewScoreFromBlockField), 'lesson 6 has no stale preview-score checks from deleted exercises');

const lesson7 = lessons[6];
const lesson7WinTextBlock = lesson7.blocklyBlocks.find(block => block.type === 'lesson_7_win_text');
const lesson7TargetBlock = lesson7.blocklyBlocks.find(block => block.type === 'lesson_7_target');
assert.ok(lesson7.title.includes('קליקים'), 'lesson 7 focuses on the first click game');
assert.equal(lesson7WinTextBlock.find, 'המגש מלא! העוגיות מוכנות 🍪', 'lesson 7 win-message block finds the actual starter win text');
assert.ok(lesson7.starter.js.includes(lesson7WinTextBlock.find), 'lesson 7 starter contains the text changed by the win-message block');
assert.ok(lesson7.starter.html.includes('id="targetText"'), 'lesson 7 preview shows the visible win target total');
assert.ok(lesson7.starter.js.includes('document.getElementById("targetText").textContent = target'), 'lesson 7 starter syncs the visible target total from target');
assert.ok(lesson7.starter.js.includes('"דני מתחיל לאפות. הגיעו ל־" + target'), 'lesson 7 reset message uses the current target instead of hard-coded 10');
assert.ok(lesson7TargetBlock.find.includes('targetText') && lesson7TargetBlock.replace.includes('targetText'), 'lesson 7 target block updates the visible target total as well as the JS constant');
assert.ok(lesson7TargetBlock.find.includes('message') && lesson7TargetBlock.replace.includes('message'), 'lesson 7 target block updates the visible instruction message with the selected target');
assert.equal(lesson7.exercises.length, 7, 'lesson 7 keeps six gameplay exercises plus one code-writing exercise');
assert.ok(lesson7.exercises.at(-1).title.includes('כותבים את שורת הניקוד'), 'lesson 7 final exercise is a code-writing task about score');
assert.ok(lesson7.exercises.at(-1).answerBox?.label.includes('ניקוד'), 'lesson 7 final exercise has a typed answer box');
assert.ok(lesson7.exercises.at(-1).check.requiresCodeLineAnswer?.requiredSnippets?.includes('score = score +'), 'lesson 7 final exercise asks for the score increment fragment');
assert.ok(lesson7.exercises.at(-1).prompt.includes('איזה חלק בקוד מגדיל את הניקוד') && !lesson7.exercises.at(-1).prompt.includes('score +='), 'lesson 7 final prompt asks learners to find the fragment without giving the exact answer');

const lesson8 = lessons[7];
const lesson8TimeBlock = lesson8.blocklyBlocks.find(block => block.type === 'lesson_8_time');
const lesson8EndBlock = lesson8.blocklyBlocks.find(block => block.type === 'lesson_8_end');
assert.ok(lesson8.title.includes('טיימר'), 'lesson 8 focuses on timer gameplay');
const lesson8WindowsBlock = lesson8.blocklyBlocks.find(block => block.type === 'lesson_8_windows');
assert.ok(lesson8WindowsBlock, 'lesson 8 includes a block for changing the number of city windows');
assert.equal(JSON.stringify(lesson8WindowsBlock.args0[0].options.map(option => option[1])), JSON.stringify(['5', '10', '15', '20']), 'lesson 8 window-count dropdown options are ordered smallest to largest');
assert.equal(lesson8WindowsBlock.toolboxFields?.N, '10', 'lesson 8 window-count block displays 10 as the default value');
assert.equal(JSON.stringify(lesson8TimeBlock.args0[0].options.map(option => option[1])), JSON.stringify(['10', '15', '20']), 'lesson 8 time dropdown is ordered smallest to largest');
assert.equal(lesson8TimeBlock.toolboxFields?.N, '15', 'lesson 8 time block displays 15 as the default value');
assert.ok(lesson8.exercises[0].check.requiresPreviewTimeFromBlockField, 'lesson 8 exercise 1 validates the live time display');
assert.ok(lesson8.exercises[2].check.requiresPreviewMessageFromBlockOutput, 'lesson 8 exercise 3 requires seeing the ending message after the timer ends');
assert.equal(lesson8.exercises.length, 6, 'lesson 8 deletes weak exercises 6 and 7 like lesson 7');
assert.equal(lesson8.exercises.at(-1).check.requiresCodeSelectionTab, 'js', 'lesson 8 final generated-code check requires JavaScript highlighting');
assert.equal(lesson8TimeBlock.find, 'const startTime = 15;', 'lesson 8 time block changes the game start time source');
assert.ok(lesson8.starter.js.includes('timeLeft = startTime;'), 'lesson 8 starts each run from the configurable start time');
assert.ok(lesson8.starter.js.includes('const totalWindows = 10;') && lesson8.starter.js.includes('function buildCity()'), 'lesson 8 builds the city from the configurable window count');
assert.ok(lesson8.starter.js.includes('if (score >= windows.length)') && lesson8.starter.js.includes('return;'), 'lesson 8 stops lighting when all displayed windows are lit');
assert.ok(lesson8.starter.js.includes(lesson8EndBlock.find), 'lesson 8 end-message block finds the actual starter end text');
assert.ok(!lesson8.starter.js.includes(' + score + " חלונות."'), 'lesson 8 ending message does not append a fixed windows word after learner text');
assert.ok(lesson8EndBlock.args0[0].text === 'כל הכבוד 🎉', 'lesson 8 ending-message block default text is only the ending message');

for (const lesson of lessons.slice(3, 15)) {
  for (const block of lesson.blocklyBlocks || []) {
    const targetSource = block.target === 'css' ? lesson.starter.css : block.target === 'js' ? lesson.starter.js : lesson.starter.html;
    const finds = Array.isArray(block.find) ? block.find : [block.find];
    assert.ok(finds.some(find => find && targetSource.includes(find)), `lesson ${lesson.id} block ${block.type} finds real starter ${block.target || 'html'} text`);
  }
}

const lesson9 = lessons[8];
assert.equal(lesson9.durationMinutes, 90, 'lesson 9 is framed as 90 minutes');
assert.ok(lesson9.title.includes('מכשולים'), 'lesson 9 focuses on obstacles');
assert.ok(lesson9.starter.js.includes('const startLives = 3') && lesson9.starter.js.includes('let lives = startLives'), 'lesson 9 initializes lives from one configurable source');
assert.ok(lesson9.starter.js.includes('lives <= 0'), 'lesson 9 checks game over');
assert.equal(lesson9.exercises.length, 6, 'lesson 9 removes weak recap exercises like lessons 7 and 8');
assert.equal(lesson9.exercises.at(-1).id, 6, 'lesson 9 final code-peek exercise is renumbered to 6');
assert.ok(lesson9.vocabulary.some(v => v[0] === 'lives'), 'lesson 9 vocabulary includes lives');
const lesson9LivesBlock = lesson9.blocklyBlocks.find(block => block.type === 'lesson_9_lives');
const lesson9StarBlock = lesson9.blocklyBlocks.find(block => block.type === 'lesson_9_star');
const lesson9ObstacleBlock = lesson9.blocklyBlocks.find(block => block.type === 'lesson_9_obstacle');
const lesson9SkipBlock = lesson9.blocklyBlocks.find(block => block.type === 'lesson_9_smart_skip');
assert.ok(lesson9LivesBlock.find.includes('startLives') && lesson9LivesBlock.replace.includes('livesText'), 'lesson 9 lives block syncs initial display and reset source');
assert.equal(lesson9.exercises[0].check.requiresPreviewLivesFromBlockField?.type, 'lesson_9_lives', 'lesson 9 lives exercise checks the visible lives display');
assert.equal(lesson9.exercises[1].check.requiresPreviewScoreFromBlockField?.clickText, '⭐', 'lesson 9 star exercise requires clicking the star in preview');
assert.equal(lesson9.exercises[1].check.requiresPreviewScoreFromBlockField?.mode, 'increase', 'lesson 9 star exercise checks score increase rather than an exact total');
assert.equal(lesson9.exercises[2].check.requiresPreviewLivesAfterPenalty?.clickText, '🌋', 'lesson 9 obstacle exercise requires clicking an obstacle and seeing lives drop');
assert.ok(lesson9.exercises[3].check.requiresPreviewMessageFromBlockOutput?.some(rule => rule.type === 'lesson_9_gameover'), 'lesson 9 Game Over exercise requires the changed ending message in preview');
const lesson9GameoverBlock = lesson9.blocklyBlocks.find(block => block.type === 'lesson_9_gameover');
assert.notEqual(lesson9GameoverBlock.args0[0].text, 'נגמרו החיים. נסו שוב!', 'lesson 9 game-over block default differs from starter message so adding it visibly changes the game');
assert.equal(lesson9.exercises[3].check.requiresPreviewCardClass, 'game-over', 'lesson 9 Game Over exercise requires reaching the game-over state');
assert.ok(lesson9SkipBlock && lesson9.exercises[4].check.requiresPreviewMessageFromBlockOutput?.some(rule => rule.type === 'lesson_9_smart_skip'), 'lesson 9 has a preview-checked smart-skip game rule block');
assert.notEqual(lesson9SkipBlock.args0[0].text, 'דילוג חכם!', 'lesson 9 smart-skip block default differs from starter message so adding it visibly changes the game');
assert.ok(!lesson9.exercises.slice(0, 5).some(ex => ex.check.changedBlocklyFields), 'lesson 9 does not force changing defaults that may already be the best game balance');
assert.ok(lesson9.starter.js.includes('nextItem(feedbackText = "")') && lesson9.starter.js.includes('feedbackText + " " + nextMessage'), 'lesson 9 keeps reward/skip feedback visible with the current-item hint naturally appended');
assert.ok(lesson9.starter.js.includes('score = Math.max(0, score - 1)') && lesson9.starter.js.includes('דילגתם על כוכב ואיבדתם נקודה'), 'lesson 9 penalizes skipping a star by losing a point');
assert.ok(!JSON.stringify(lesson9).includes('פריט חדש'), 'lesson 9 removes the redundant new-item button/copy');
assert.equal(lesson9.exercises[4].check.requiresPreviewButtonText, 'דלגו', 'lesson 9 smart-skip exercise validates the actual skip button');
assert.ok(lesson9.starter.js.includes('if (lives > 0)') && lesson9.starter.js.includes('if (lives <= 0)'), 'lesson 9 keeps Game Over visible and stops actions after lives run out');
assert.equal(lesson9.exercises.at(-1).check.requiresCodeSelectionTab, 'js', 'lesson 9 final generated-code check requires JavaScript highlighting');
assert.ok(lesson9.exercises.at(-1).check.requiresCodeSelectionBlockTypes?.includes('lesson_9_obstacle'), 'lesson 9 final generated-code check targets risk/lives JavaScript blocks');

const lesson10 = lessons[9];
assert.equal(lesson10.durationMinutes, 90, 'lesson 10 is framed as 90 minutes');
assert.ok(lesson10.title.includes('כוח מיוחד'), 'lesson 10 focuses on special power');
assert.ok(lesson10.starter.js.includes('let powerReady = true'), 'lesson 10 initializes power state');
assert.ok(lesson10.starter.js.includes('if (powerReady)'), 'lesson 10 checks power availability');
assert.ok(lesson10.exercises.length >= 8, 'lesson 10 includes many exercises');
assert.ok(lesson10.vocabulary.some(v => v[0] === 'powerReady'), 'lesson 10 vocabulary includes powerReady');

const lesson11 = lessons[10];
assert.equal(lesson11.durationMinutes, 90, 'lesson 11 is framed as 90 minutes');
assert.ok(lesson11.title.includes('הרפתקה') && lesson11.concept.includes('מסכים'), 'lesson 11 focuses on adventure screens');
assert.ok(lesson11.starter.js.includes('function showScreen'), 'lesson 11 includes screen switching');
assert.ok(lesson11.starter.html.includes('id="startScreen"'), 'lesson 11 has start screen');
assert.ok(lesson11.exercises.length >= 8, 'lesson 11 includes many exercises');
assert.ok(lesson11.vocabulary.some(v => v[0] === 'screen'), 'lesson 11 vocabulary includes screen');

const lesson12 = lessons[11];
assert.equal(lesson12.durationMinutes, 90, 'lesson 12 is framed as 90 minutes');
assert.ok(lesson12.title.includes('מיני־פרויקט'), 'lesson 12 is a mini project');
assert.ok(lesson12.starter.js.includes('function updateScreen'), 'lesson 12 consolidates screen updates');
assert.ok(lesson12.starter.js.includes('const target = 5'), 'lesson 12 has project target');
assert.ok(lesson12.exercises.length >= 8, 'lesson 12 includes many exercises');
assert.ok(lesson12.vocabulary.some(v => v[0] === 'project'), 'lesson 12 vocabulary includes project');

const lesson13 = lessons[12];
assert.ok(lesson13.title.includes('הקוד שנוצר'), 'lesson 13 starts the generated-code lab phase');
assert.ok(lesson13.progressionStage.includes('בלוקים אמיתיים'), 'lesson 13 remains block-first under the new progression requirement');
assert.ok(lesson13.blocklyBlocks.length >= 3, 'lesson 13 has generated-code Blockly cards');
assert.ok(lesson13.blocklyBlocks.some(block => block.target === 'html'), 'lesson 13 asks learners to identify generated HTML');
assert.ok(lesson13.blocklyBlocks.some(block => block.target === 'css'), 'lesson 13 asks learners to identify generated CSS');
assert.ok(lesson13.blocklyBlocks.some(block => block.target === 'js'), 'lesson 13 asks learners to identify generated JavaScript');

const lesson14 = lessons[13];
assert.ok(lesson14.title.includes('HTML'), 'lesson 14 focuses on HTML');
assert.ok(lesson14.blocklyBlocks.every(block => block.target === 'html'), 'lesson 14 uses HTML-only Blockly cards');

const lesson15 = lessons[14];
assert.ok(lesson15.title.includes('CSS'), 'lesson 15 focuses on CSS');
assert.ok(lesson15.blocklyBlocks.every(block => block.target === 'css'), 'lesson 15 uses CSS-only Blockly cards');

const lesson19 = lessons[18];
assert.ok(lesson19.title.includes('כרטיסי HTML'), 'lesson 19 keeps the HTML-card focus');
assert.ok(lesson19.mode.includes('Real Blockly full rework'), 'lesson 19 now uses real Blockly card blocks');
assert.ok(lesson19.blocklyBlocks.some(block => block.label.includes('כותרת HTML')), 'lesson 19 exposes real HTML as draggable Blockly blocks');

const lesson24 = lessons[23];
assert.ok(lesson24.concept.includes('חוקי משחק'), 'lesson 24 edits game rules conceptually');
assert.ok(lesson24.blocklyBlocks.some(block => block.label.includes('פלט JavaScript')), 'lesson 24 has real JS Blockly cards');

const lesson25 = lessons[24];
assert.ok(lesson25.progressionStage.includes('כתיבה מודרכת'), 'lesson 25 starts guided coding');
assert.ok(!lesson25.bridgeBlocks?.length, 'guided coding phase reduces code-card scaffolding');

const lesson30 = lessons[29];
assert.ok(lesson30.title.includes('פרויקט סיום'), 'lesson 30 is the final project');
assert.ok(lesson30.concept.includes('HTML + CSS + JS'), 'lesson 30 combines HTML CSS and JS');

const hub = read('webcode.html');
assert.ok(hub.includes('WebCode Lab'), 'hub page exists');
assert.ok(hub.includes('webcode-play.html?lesson=1'), 'hub links to lesson 1');
assert.ok(hub.includes('webcode-slides.html?lesson=1'), 'hub links to guide slides');
assert.ok(hub.includes('25–30'), 'hub explains gradual move to real coding');
assert.ok(hub.includes('formatMixedText') && hub.includes('tech-term'), 'hub isolates English tech terms so RTL lesson cards do not flip mixed text');
assert.ok(hub.includes('js/webcode-lessons-lesson3-show-message-v48.js'), 'hub loads a cache-busted lesson-data asset to avoid stale course cards');
assert.ok(!hub.includes('Blockly אמיתי'), 'course-page hero avoids unclear “Blockly אמיתי” phrasing');
assert.ok(!JSON.stringify(lessons.slice(0, 3).map(lesson => lesson.concept)).includes('Blockly אמיתי'), 'visible course-card concepts avoid unclear “Blockly אמיתי” phrasing');

const play = read('webcode-play.html');
const loadedLessonAsset = (play.match(/<script src="(js\/webcode-lessons-[^"]+)"/) || [])[1];
assert.ok(loadedLessonAsset, 'play page should load a versioned WebCode lesson asset');
const loadedLessonsCode = read(loadedLessonAsset);
const loadedSandbox = { window: {} };
vm.createContext(loadedSandbox);
vm.runInContext(loadedLessonsCode, loadedSandbox);
const loadedLessons = loadedSandbox.window.WEBCODE_LESSONS;
assert.ok(loadedLessons.find(lesson => lesson.id === 1).exercises.some(exercise => exercise.title.includes('שתי קוביות מידע וסדר') && exercise.prompt.includes('מתחת לפסקה') && exercise.prompt.includes('לפני הכפתור')), 'loaded lesson asset should teach block order in the information-columns exercise');
assert.ok(loadedLessons.find(lesson => lesson.id === 1).exercises.some(exercise => exercise.title.includes('חתימה בסוף הדף') && exercise.prompt.includes('הבלוק האחרון') && !exercise.prompt.includes('שתי קוביות מידע')), 'loaded lesson asset should keep the footer exercise focused only on placing the signature at the end');
assert.ok(loadedLessons.find(lesson => lesson.id === 1).exercises.some(exercise => exercise.check?.qualityBlocklyFields?.length && exercise.check?.qualityFeedback), 'loaded lesson asset should require meaningful learner text, not only non-empty text');
assert.ok(loadedLessons.find(lesson => lesson.id === 1).exercises.some(exercise => exercise.check?.relatedBlocklyTextGroups?.length && exercise.check?.relatedTextFeedback), 'loaded lesson asset should gently require related text across a chosen page idea');
assert.ok(!loadedLessonsCode.includes('הזיזו אותו למקום אחר בשרשרת'), 'loaded lesson asset must not contain the old instruction to move the footer elsewhere');
assert.ok(play.includes('repairSavedCodeState') && play.includes('function makeGreeting'), 'player repairs stale lesson 4 saved state when makeGreeting is missing');
assert.ok(play.includes('hasPreviewFilledInputs') && play.includes('hasPreviewResultFromInputs'), 'player can validate preview input/result interactions');
assert.ok(play.includes('blocklyLessonBuilder'), 'play page supports lesson-specific Blockly blocks for lessons 4-24');
assert.ok(play.includes('webcodeLessonState:v15'), 'play page uses a fresh lesson state key so stale Blockly defaults do not persist');
assert.ok(play.includes('<block type="lesson_8_time"><field name="N">15</field>') && play.includes('<block type="lesson_8_windows"><field name="N">10</field>'), 'lesson 8 starter XML defaults to 15 seconds and 10 windows');
assert.ok(play.includes('block.toolboxFields') && play.includes('<field name="${name}">'), 'toolbox blocks can display explicit default field values');
assert.ok(play.includes('defineLessonBlocklyBlocks'), 'play page defines dynamic draggable lesson blocks');
assert.ok(play.includes('js/webcode-lessons-lesson3-show-message-v48.js'), 'play page loads a cache-busted lesson data asset for refreshed WebCode lessons');
assert.ok(play.includes('scoreText:scoreText?String(scoreText.textContent') && play.includes('scoreBefore:event.data.scoreBefore'), 'preview click bridge records before/after scoreText for score validators');
assert.ok(play.includes('function hasPreviewScoreSum(rule)'), 'play page can validate preview score sums');
assert.ok(play.includes('timeText') && play.includes('hasPreviewTimeFromBlockField'), 'play page can validate preview timer display text');
assert.ok(play.includes('function hasPreviewScoreFromBlockField(rule)') && play.includes("rule.mode === 'increase'"), 'play page can validate preview score totals or score increases against a block field');
assert.ok(play.includes('function generateLesson4ChallengeCode') && play.includes('חסר בלוק'), 'lesson 4 challenge preview is generated from connected starter blocks, not the hidden lesson starter');
assert.ok(play.includes('applyExerciseBlocklyStarter(activeExercise)') && play.includes('blocklyStarterXml'), 'play page loads exercise-specific starter blocks into the Blockly workspace for debug-style challenges');
assert.ok(play.includes('if(ex?.blocklyStarterXml) return ex.blocklyStarterXml') && play.includes('delete checkMemory.exerciseBaselines[activeExercise]'), 'starter-code reset uses the current exercise starter XML instead of stale/blank baseline state');
assert.ok(play.includes('hasExactBlocklyFields') && play.includes('exactBlocklyFields'), 'play page can validate exact Blockly field values for specific challenges');
assert.ok(play.includes('ex.optional') && play.includes('דלגו וסיימו'), 'play page lets optional final challenges be skipped');
assert.ok(play.includes("$('topRunButton').style.display = lesson.realBlocklyBuilder ? 'none' : ''"), 'top run button is hidden for auto-running Blockly lessons');
assert.ok(play.includes('if(lesson.blocklyLessonBuilder) return;') && play.includes('x="130" y="70"'), 'lesson-specific Blockly lessons keep starter block placed comfortably instead of pushed to the far right');
assert.ok(play.includes('hasGeneratedBlockOutputs') && play.includes('generatedBlockOutputs'), 'checks can require the selected lesson-block field value to appear in generated code');
assert.ok(play.includes('hasBlocklyFieldsContaining') && play.includes('blocklyFieldsContaining'), 'checks can require learner text fields to contain needed characters such as a question mark');
assert.ok(play.includes('function hasQualityBlocklyFields') && play.includes('qualityBlocklyFields') && play.includes('isGenericQualityText'), 'checks can reject too-short or generic learner text');
assert.ok(play.includes('function hasRelatedBlocklyTextGroups') && play.includes('relatedBlocklyTextGroups'), 'checks can require a soft relationship between title, paragraph, and information blocks');
assert.ok(play.includes('hasPreviewInputMatchesBlockFields') && play.includes('requiresPreviewFeedbackClass'), 'checks can require trying a typed block answer in the preview and receiving correct feedback');
assert.ok(play.includes('hasPreviewInputDiffersFromBlockFields') && play.includes('requiresPreviewInputDiffersFromBlockFields'), 'checks can require trying a wrong answer that differs from the configured correct answer');
assert.ok(play.includes('hasAnyChangedBlocklyField') && play.includes('anyChangedBlocklyFields'), 'checks can require at least one edited block field when the prompt says to change one block');
assert.ok(play.includes('hasPreviewButtonClick') && play.includes('requiresPreviewButtonClick'), 'checks can require pressing a preview button for visible-result exercises');
assert.ok(play.includes('hasPreviewResultFromBlockOutput') && play.includes('requiresPreviewResultFromBlockOutput'), 'checks can require the preview result to include the generated output from a block');
assert.ok(!play.includes('בחרו תרגיל, שנו קוד ולחצו הרצה.'), 'exercise feedback no longer tells auto-running Blockly learners to press run');
assert.ok(play.includes('textarea id="htmlCode"'), 'play page has HTML editor');
assert.ok(play.includes('textarea id="cssCode"'), 'play page has CSS editor');
assert.ok(play.includes('textarea id="jsCode"'), 'play page has JS editor');
assert.ok(play.includes('.btn:disabled') && play.includes('cursor:not-allowed') && play.includes('grayscale'), 'disabled Continue button is visually muted and cannot look available');
assert.ok(play.includes('לראות קוד שנוצר'), 'play page has explicit generated-code button');
assert.ok(play.includes('showGeneratedCode'), 'play page can open generated code panel for students');
assert.ok(play.includes("if(lesson.realBlocklyBuilder){\n        $('htmlCode').value = saved.html || '';"), 'real Blockly lessons do not briefly show legacy starter code before blocks generate');
assert.ok(play.includes('if(!lesson.realBlocklyBuilder) runCode();'), 'real Blockly lessons skip the legacy starter-code preview during init');
assert.ok(play.includes('<bdi>${lesson.id}</bdi>'), 'top lesson title keeps lesson number/colon in correct RTL order');
assert.ok(play.includes('iframe id="preview"'), 'play page has live preview');
assert.ok(play.includes('lessonPanel'), 'play page wraps lesson text in a collapsible panel');
assert.ok(play.includes('compact-info') && play.includes('id="story" hidden') && play.includes('id="mission" hidden'), 'lesson intro stays compact so exercises remain visible');
assert.ok(play.includes('toggleLessonPanel'), 'play page can collapse and expand lesson instructions');
assert.ok(play.includes('aria-expanded'), 'collapsible lesson panel is accessible');
assert.ok(play.includes('lessonToggleIcon') && play.includes('⌃') && play.includes('⌄'), 'collapse toggle uses standard chevron icons instead of plus/minus');
assert.ok(play.includes('lesson-collapsed'), 'collapsing instructions reallocates space to Blockly and preview sections');
assert.ok(play.includes('previewResize') && play.includes('--preview-width'), 'preview panel has a draggable width resizer');
assert.ok(play.includes('webcodePreviewWidth') && play.includes('pointermove'), 'preview width drag persists and handles pointer movement');
assert.ok(play.includes('webcodeLessonState:v15') && play.includes('saveLessonState') && play.includes('restoreProgress'), 'lesson progress and code persist across page refreshes');
assert.ok(play.includes('validExerciseIds') && play.includes('filter(id => validExerciseIds.has(id))'), 'saved completed exercises are pruned when a lesson is shortened');
assert.ok(play.includes('blocklyXml') && play.includes('workspaceToDom') && play.includes('saved.blocklyXml || webBuilderStarterXml()'), 'real Blockly workspace persists across page refreshes');
assert.ok(play.includes('stateReady = true; saveLessonState();'), 'initial restore does not overwrite saved work before Blockly loads');
assert.ok(play.includes('Blockly.svgResize'), 'layout changes resize Blockly after layout change');
assert.ok(play.includes('alignBlocklyStarterBlocksRight'), 'starter Blockly program is aligned to the right side of the workspace');
assert.ok(play.includes('safeRightEdge') && play.includes('blocklyToolboxCategoryGroup'), 'starter blocks align to free workspace edge without overlapping toolbox');
assert.ok(play.includes('checkExercise()'), 'play page has exercise checking');
assert.ok(play.includes('function isStarterStructureLockedExercise(){ return false; }'), 'lesson 3 should not forcibly detach or reposition blocks while learners drag them');
assert.ok(play.includes('.page-card.magic') && play.includes('box-shadow: 0 0 0 8px') && play.includes('content: " ✨"'), 'lesson 3 magic mode should create a clear visual change, not just a tiny shake');
assert.ok(play.includes('checkMemory.starterLockBaselines') && play.includes('starterChainBlocks().map(block => block.id)'), 'locked exercises snapshot the starter chain block ids');
assert.ok(play.includes('blocklyWorkspace.getTopBlocks(false).forEach(setBlockTreeFree)') && play.includes('setStarterBlockLock(block, baselineIds.has(block.id))'), 'locked exercises lock only the starter baseline blocks, not newly added blocks');
assert.ok(play.includes('detachBlocksConnectedAfterStarterBaseline'), 'locked exercises detach newly added blocks connected into the starter chain');
assert.ok(play.includes('ensureExerciseBaseline(activeExercise);'), 'direct-open exercise 6 captures its baseline after Blockly loads');
assert.ok(!play.includes('setBlockTreeStructureLock'), 'old recursive lock-all helper is removed');
assert.ok(play.includes('activeExercise === 2 && block.type === \'web_button\' && name === \'LABEL\''), 'lesson 3 exercise 2 unlocks only the button label field');
assert.ok(play.includes("message0:'כפתור %1'") && !play.includes("message0:'כפתור %1 מציג הודעה %2'"), 'generic button block should only define the visible button label, not the click message');
assert.ok(play.includes('activeExercise === 6 && block.type === \'web_action_background\' && name === \'BG\''), 'lesson 3 exercise 6 unlocks only the existing background-action dropdown');
assert.ok(play.includes('hasExactBlockTypeCounts(c.exactBlockTypeCounts)'), 'player supports rejecting added duplicate blocks when an exercise must change a starter block');
assert.ok(play.includes('ensureRequiredStarterBlocks(id)') && play.includes('connectNewBlockInChain(block, rule.after)'), 'locked starter-change exercises add required blocks only when missing and connect them into the code chain');
assert.ok(play.includes('ensureRequiredStarterBlocks(activeExercise);') && play.includes('ensureExerciseBaseline(id)') && play.includes("'web_action_background.BG': firstBlocklyFieldValue('web_action_background', 'BG')"), 'lesson 3 exercise 6 inserts missing required block before capturing the user workspace as the entry baseline');
assert.ok(play.includes('hasChangedBlocklyFieldsFromBaseline(c.changedBlocklyFieldsFromBaseline)') && play.includes('exerciseResetXml()'), 'lesson 3 exercise 6 checks/resets against the entry baseline, not lesson starter XML');
assert.ok(play.includes('field.setEnabled(enabled)') && !play.includes('setEditable?.(!locked)'), 'lesson 3 field lock uses field enable state, not blanket block edit lock');
assert.ok(play.includes('block.setMovable?.(true);') && play.includes('block.setDeletable?.(true);') && !play.includes('block.setMovable?.(!locked);') && !play.includes('block.setDeletable?.(!locked);'), 'Blockly blocks should stay movable/deletable even when specific starter fields are locked');
assert.ok(play.includes('resetStarterBlocksOnly') && play.includes('↺ קוד התחלה'), 'lesson 3 exercise 2 has a starter-code reset button');
assert.ok(play.includes('previewClicks.push({ exerciseId:activeExercise') && play.includes('click.exerciseId === activeExercise'), 'preview button clicks are tracked per current exercise');
assert.ok(play.includes('emojiText:emoji?String(emoji.textContent') && play.includes('hasPreviewEmojiChanged'), 'player can require visible emoji changes in the preview');
assert.ok(play.includes('cardClass:card?String(card.className') && play.includes('hasPreviewCardClass'), 'player can require visible class toggles in the preview');
assert.ok(play.includes('function goNextLesson()') && play.includes('לשיעור הבא ←') && play.includes('lesson.id + 1'), 'last exercise should offer a clear next-lesson button');
assert.ok(play.includes('function courseLessonCount()') && !play.includes('lessons.length'), 'next lesson controls should not reference an undefined lessons variable that can stop rendering at 0/0');
assert.ok(play.includes('goCourseHome') && play.includes("location.href = 'webcode.html'") && play.includes('עמוד הקורס'), 'last exercise should still offer a course-home option');
assert.ok(play.includes('completedTitle'), 'check button keeps success feedback visible after checking');
assert.ok(!/function checkExercise\(\)[\s\S]*?runCode\(\);[\s\S]*?renderProgress\(\); saveLessonState\(\); \}/.test(play), 'check button does not rerun/reset the live preview after click-result exercises');
assert.ok(play.includes('exercise-bottom') && play.includes('exercise-feedback'), 'check/run feedback is shown next to the exercise controls, not over the preview');
assert.ok(play.includes('.exercise-actions-main{display:flex;gap:.55rem;flex-wrap:wrap}') && play.includes('.starter-reset-row{display:flex;justify-content:flex-start}'), 'lesson 3 exercise 2 uses normal controls with starter reset below Back');
assert.ok(play.includes('<div class="starter-reset-row">${starterResetButton}</div>'), 'starter-code reset is placed below the Back button row');
assert.ok(!play.includes('exercise-meta">${esc(ex.minutes)}'), 'exercise cards do not show internal minute ranges');
assert.ok(!play.includes('<div class="feedback" id="feedback">בחרו תרגיל, שנו קוד ולחצו הרצה.</div>'), 'feedback is not placed at the bottom of the preview panel where the bug-report button can cover it');
assert.ok(play.includes('webcode-error'), 'play page catches preview JavaScript errors');
assert.ok(play.includes('debugHint'), 'play page gives student-friendly syntax/debug hints');
assert.ok(play.includes('validateJavaScriptSyntax'), 'play page validates JavaScript syntax before preview injection');
assert.ok(play.includes('שגיאת סינטקס ב־JavaScript'), 'play page shows Hebrew syntax error feedback');
assert.ok(play.includes('js/blockly.min.js'), 'play page loads local Blockly so NetFree/external CDN blocking does not leave the page blank');
assert.ok(play.includes('Blockly.inject'), 'play page injects a real Blockly workspace');
assert.ok(play.includes("$('blocksIntro').style.display = 'none'"), 'real Blockly lessons hide the redundant intro above the workspace');
assert.ok(play.includes("$('blocksStage').classList.add('real-blockly-stage')") && play.includes('.blocks-stage.real-blockly-stage{padding:0;gap:0}'), 'real Blockly workspace removes the orange barrier and fills the panel');
assert.ok(play.includes('defineWebBuilderBlocks'), 'play page defines draggable Web builder blocks');
assert.ok(play.includes('if(!window.getWebCodeLesson)') && play.includes('WEBCODE_LESSONS') && play.includes('0/0'), 'play page should include lesson-data fallback protection instead of remaining at 0/0 if the lesson asset fails');
assert.ok(play.includes('function hasRenderablePageBlocks()') && play.includes('if(!hasRenderablePageBlocks())') && play.includes('Blockly.Xml.domToWorkspace(parseBlocklyXml(webBuilderStarterXml()), blocklyWorkspace)'), 'real Blockly lessons should recover starter blocks instead of showing an almost-empty preview after stale/blank saved state');
assert.ok(play.includes("lesson.id === 2 ? ['web_theme','web_card_shape','web_shadow','web_title_color','web_button_style','web_hover']"), 'lesson 2 CSS-only saved work should count as renderable so added design blocks persist after refresh');
assert.ok(play.includes("lesson.id === 2 ? (blocklyWorkspace?.getAllBlocks(false) || []) : collectPageBlocks()"), 'lesson 2 should preserve even unconnected design blocks after refresh instead of only counting connected page-chain blocks');
assert.ok(play.includes('generateCodeFromBlockly(); refreshPageStartToolbox(); saveLessonState(); setTimeout(saveLessonState, 60);'), 'Blockly workspace changes should be explicitly saved immediately after drag/connect/delete events');
assert.ok(play.includes('סגור קוד ✕') && play.includes('function closeCodePeek()') && play.includes('codePeekOpened = false') && play.includes("$('codePeek').open = false"), 'code peek panel should have a clear close button that hides the generated code view');
assert.ok(play.includes('codePeekOpened = Boolean') && play.includes('.code-peek-actions'), 'closing/opening the code peek should be saved and styled clearly');
assert.ok(play.includes('webBuilderToolbox'), 'play page exposes a Blockly toolbox');
assert.ok(play.includes('pageStartDisabled') && play.includes('<block type="page_start"${pageStartDisabled}></block>\n      <sep gap="14"></sep>\n      <label text="מבנה עמוד"></label>'), 'page-start toolbox block appears above the page-structure section and disables when a root already exists');
assert.ok(play.includes('enforceSinglePageStart') && play.includes('כבר יש בלוק “עמוד האתר שלי”') && !play.includes('אפשר בלוק עמוד אחד בלבד'), 'player removes duplicate page root blocks without an extra toolbox note');
assert.ok(play.includes('refreshPageStartToolbox') && play.includes('blocklyWorkspace.updateToolbox(webBuilderToolbox())'), 'page-start toolbox availability refreshes when the root block is added or removed');

assert.ok(play.includes('web_card_shape') && play.includes('web_hover'), 'play page defines design studio blocks for lesson 2');
assert.ok(play.includes("['ללא אפקט','none'],['גדל קצת','grow']") && !play.includes("['גדל קצת','grow'],['קופץ','jump'],['מחליף צבע','color'],['בלי אפקט','none']"), 'hover block should start from a neutral no-effect option so Grow remains a valid learner choice');
assert.ok(play.includes('.blocklyDropDownDiv,.blocklyWidgetDiv,.blocklyTooltipDiv') && play.includes('z-index:99999!important'), 'Blockly dropdown menus should appear above the lesson panels instead of being hidden');
assert.ok(play.includes("['בחרו צורה','none']") && play.includes("['בחרו צל','choose']") && play.includes("['בלי צל','none']") && play.includes("['בחרו צבע','none']") && play.includes("['בחרו סגנון','none']"), 'design dropdowns should use neutral placeholders instead of real default choices');
assert.ok(lessons.find(lesson => lesson.id === 2).exercises.some(exercise => exercise.title.includes('אפקט Hover') && exercise.check?.changedBlocklyFields?.some(rule => rule.type === 'web_hover' && rule.defaultValue === 'none') && exercise.prompt.includes('בחרו אפקט עכבר') && !exercise.prompt.includes('ברירת המחדל')), 'lesson 2 hover task should ask for a chosen effect, not a different-than-default effect');
assert.ok(lessons.find(lesson => lesson.id === 2).exercises.some(exercise => exercise.check?.changedBlocklyFields?.some(rule => rule.type === 'web_card_shape' && rule.defaultValue === 'none')) && lessons.find(lesson => lesson.id === 2).exercises.some(exercise => exercise.check?.changedBlocklyFields?.some(rule => rule.type === 'web_shadow' && rule.defaultValue === 'choose')), 'lesson 2 neutral dropdown placeholders should be treated as the values learners must change after dragging the block');
const lesson2CssAnswerExercise = lessons.find(lesson => lesson.id === 2).exercises.find(exercise => exercise.title.includes('מקלידים שורת CSS'));
assert.ok(lesson2CssAnswerExercise && lesson2CssAnswerExercise.answerBox?.label.includes('שורת CSS') && !lesson2CssAnswerExercise.answerBox?.parts && lesson2CssAnswerExercise.prompt.includes('איזה בלוק נבחר') && !lesson2CssAnswerExercise.prompt.includes('איזה בלוק ושורה נבחרו') && lesson2CssAnswerExercise.check?.requiresCodeLineAnswer?.tab === 'css', 'lesson 2 CSS-peek exercise should require manually typing one generated CSS line and make the selected block visible');
assert.ok(lesson2CssAnswerExercise.check.requiresCodeSelectionBlockTypes.includes('web_theme') && lesson2CssAnswerExercise.check.requiresCodeLineAnswer.blockTypes.includes('web_theme') && lesson2CssAnswerExercise.check.requiresCodeLineAnswer.requiredSnippets.includes('background:'), 'lesson 2 CSS-peek exercise should accept the page-design/theme block and its generated background line');
assert.ok(play.includes('function hasCodeLineAnswer') && play.includes('requiresCodeLineAnswer') && play.includes('lastGeneratedCodeSelection.line') && play.includes('exerciseAnswer') && !play.includes('exerciseAnswerProperty'), 'player should validate one typed CSS line against the selected CSS block line');
assert.ok(play.includes('function expectedSelectionText') && play.includes('function codeSelectionStatusHtml') && play.includes('נבחר בלוק:') && play.includes('refreshCodeSelectionStatus()') && !play.includes('<code>${esc(selected.line || \'\')}</code>'), 'code answer task should visibly show only the Hebrew selected block name, not the generated code line');
assert.ok(play.includes("if(types.includes('web_button')) return 'בלוק הכפתור'") && play.includes("return 'בלוק עיצוב שמייצר CSS'"), 'wrong-block selection feedback should name the expected kind of block for each task');
assert.ok(play.includes('function blockAnswerPaste') && play.includes('onpaste="return blockAnswerPaste(event)"'), 'CSS answer input should block paste so learners type the line themselves');
assert.ok(/id="exerciseAnswer"[^\n]*placeholder="הקלד כאן את קוד הבלוק"/.test(play) && !play.includes('exerciseAnswerProperty') && !play.includes('css-answer-parts'), 'CSS answer UI should be one input with the requested clear Hebrew placeholder and no old three-part fields');
assert.ok(/id="exerciseAnswer"[^\n]*autocomplete="off"[^\n]*autocorrect="off"[^\n]*autocapitalize="off"/.test(play) && play.includes('function blockAnswerKeydown') && play.includes("event.key !== 'Tab'") && play.includes('בלי השלמה אוטומטית עם Tab'), 'CSS answer input should disable browser autocomplete and prevent Tab from accepting/completing a previous answer');
assert.ok(play.includes('function persistedCheckMemory') && play.includes('delete copy.exerciseAnswers[ex.id]') && play.includes('if(!currentExercise()?.check?.requiresCodeLineAnswer) saveLessonState();'), 'typed CSS code-line answers should not be persisted to localStorage for later autocomplete/restoration');
assert.ok(play.includes("typeof value === 'object' ? ''") && play.includes('object\\s*object') && play.includes('Object.entries(checkMemory.exerciseAnswers)'), 'CSS answer input should ignore and delete stale object/stringified object answers from the old three-part answer UI');
assert.ok(play.includes('hasButton') && play.includes('cssParts'), 'generated CSS only includes styles for blocks students added');
assert.ok(play.includes('if(lesson.id === 2){') && play.includes('html.length = 0') && play.includes('כרטיס העיצוב שלי') && play.includes('בשיעור הזה משנים רק CSS'), 'lesson 2 should render fixed starter card content so CSS-only tasks never show an empty card');
assert.ok(play.includes("if(block.getFieldValue('COLOR') === 'none') return null") && play.includes("value && value !== 'none') titleColor = value") && play.includes("value && value !== 'choose') shadow = value"), 'neutral design placeholders should not be treated as selected/generated CSS or produce undefined CSS values');
assert.ok(play.includes('סטודיו עיצוב'), 'play page toolbox includes design studio category');
assert.ok(play.includes('סטודיו פעולה'), 'play page toolbox includes action studio category for lesson 3');
assert.ok(play.includes('web_action_message') && play.includes('web_action_emoji') && play.includes('web_action_background') && play.includes('web_action_magic'), 'play page defines action studio blocks for lesson 3');
assert.ok(play.includes("message0:'בלחיצה הצג הודעה %1'") && play.includes("text:'הודעה חדשה מהפעולה ✨'") && !play.includes('בלחיצה שנה הודעה'), 'message action block should be phrased as showing a new message, not changing a pre-existing one');
assert.ok(lessons.find(lesson => lesson.id === 1).exercises.some(exercise => exercise.title.includes('שתי קוביות מידע וסדר') && exercise.check?.orderedBlockTypes?.join('>').includes('web_paragraph>web_columns>web_button') && exercise.check?.qualityBlocklyFields?.length === 2 && exercise.check?.relatedBlocklyTextGroups?.length), 'lesson 1 exercise 6 should teach order and meaningful related text in the information-columns task');
assert.ok(lessons.find(lesson => lesson.id === 1).exercises.some(exercise => exercise.title.includes('חתימה בסוף הדף') && exercise.check?.footerMustBeLast), 'lesson 1 exercise 7 should focus only on the footer being last');
assert.ok(play.includes('function checkFooterAtEndExercise') && play.includes('footerMustBeLast') && play.includes("blocks.at(-1)?.type !== 'web_footer'"), 'footer exercise should require the footer to be the final block without moving information columns');
assert.ok(!play.includes('columnsMovedWithFooterLast') && !play.includes('checkColumnsMovedWithFooterLastExercise'), 'old mixed columns/footer validation should be removed');
assert.ok(play.includes('<p id="message"></p>') && play.includes('#message:empty') && play.includes('display: none;') && !play.includes('כאן תופיע הודעה מהכפתור...'), 'button message placeholder should be hidden until the preview button is clicked');
assert.ok(play.includes('const webEmojiOptions = [') && play.includes("['📚 ספרים','📚']") && play.includes("['⚽ ספורט','⚽']") && play.includes("['🛍️ חנות','🛍️']") && play.includes('options:webEmojiOptions'), 'emoji dropdowns should offer a broad set of symbols for different website topics');
assert.ok(play.includes('classList.toggle("magic")') && play.includes('document.body.style.background'), 'lesson 3 action blocks generate real JavaScript actions');
assert.ok(play.includes('generateCodeFromBlockly'), 'play page generates HTML/CSS/JS from connected Blockly blocks');
assert.ok(play.includes('highlightGeneratedCodeForBlock'), 'selecting a Blockly block highlights its generated code');
assert.ok(play.includes('codeTargetForBlock'), 'play page maps block types to generated code snippets');
assert.ok(play.includes('setSelectionRange'), 'generated code highlight selects the relevant text in the editor');
assert.ok(play.includes('shareProject'), 'play page can create a share link for the student project');
assert.ok(play.includes('navigator.clipboard.writeText(shareUrl)'), 'share button copies only the public link');
assert.ok(play.includes('הקישור הציבורי הועתק'), 'share button confirms the public link was copied');
assert.ok(!play.includes('navigator.share'), 'share button does not open native share UI');
assert.ok(play.includes('🏠 עמוד הקורס'), 'top course-home button is clearly named');
assert.ok(play.includes('webcode-share.html'), 'play page shares to a clean viewer page');
assert.ok(play.includes('renderBridgeBlocks'), 'play page keeps bridge blocks fallback for any legacy lessons outside 4-24');
assert.ok(play.includes('applyBridgeBlock'), 'play page can still apply bridge blocks if needed outside the block-first range');

const shared = read('webcode-share.html');
assert.ok(shared.includes('עמוד משותף'), 'shared project viewer page exists');
assert.ok(shared.includes('decodeSharePayload'), 'shared project viewer decodes link payload');
assert.ok(shared.includes('sandbox="allow-scripts"'), 'shared project viewer isolates student code in sandboxed iframe');
assert.ok(shared.includes('לבנות עמוד משלי'), 'shared project viewer invites friends to build their own page');

const slides = read('webcode-slides.html');
assert.ok(slides.includes('מהלך שיעור 90 דקות'), 'slides include 90-minute flow');
assert.ok(slides.includes('רצף תרגילים לשיעור'), 'slides include exercise sequence');
assert.ok(slides.includes('שימוש נכון ב־AI'), 'slides include AI guidance');

const grade4 = read('holon-scope-grade4.html');
assert.ok(grade4.includes('webcode.html'), 'grade 4 page links to WebCode hub');
assert.ok(grade4.includes('webcode-play.html?lesson=1'), 'grade 4 page links to first lesson');

console.log('webcode-course tests passed');
