import { readFileSync } from 'node:fs';
import { strict as assert } from 'node:assert';
import vm from 'node:vm';

const root = new URL('../', import.meta.url);
const read = path => readFileSync(new URL(path, root), 'utf8');

const dataCode = read('js/webcode-lessons.js');
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(dataCode, sandbox);

const lessons = sandbox.window.WEBCODE_LESSONS;
assert.equal(Array.isArray(lessons), true, 'lessons array exists');
assert.equal(lessons.length, 30, 'WebCode course includes thirty lessons');
assert.deepEqual(Array.from(lessons, l => l.id), Array.from({ length: 30 }, (_, i) => i + 1), 'lesson ids are sequential 1-30');
lessons.forEach(lessonItem => {
  assert.equal(lessonItem.durationMinutes, 90, `lesson ${lessonItem.id} is framed as 90 minutes`);
  assert.ok(lessonItem.starter?.html?.includes('<main'), `lesson ${lessonItem.id} has starter HTML`);
  assert.ok(lessonItem.starter?.css?.includes('background'), `lesson ${lessonItem.id} has starter CSS`);
  assert.ok(lessonItem.starter?.js?.includes('function'), `lesson ${lessonItem.id} has starter JavaScript`);
  assert.ok(lessonItem.lessonFlow.length >= 7, `lesson ${lessonItem.id} has a full guide flow`);
  const minimumExercises = lessonItem.id === 4 ? 7 : lessonItem.id === 2 ? 7 : 8;
  assert.ok(lessonItem.exercises.length >= minimumExercises, `lesson ${lessonItem.id} has enough exercises`);
  assert.ok(lessonItem.vocabulary.length >= 4, `lesson ${lessonItem.id} has vocabulary`);
});

const lesson = lessons[0];
assert.equal(lesson.durationMinutes, 90, 'lesson is framed as 90 minutes');
assert.ok(lesson.title.includes('עמוד אמיתי') && lesson.title.includes('Blockly'), 'lesson has concise real Blockly page-builder title');
assert.ok(lesson.starter.html.includes('<button onclick="sayHello()">'), 'starter has working button');
assert.ok(lesson.starter.css.includes('border-radius'), 'starter includes visible styling');
assert.ok(lesson.starter.js.includes('getElementById("message")'), 'starter JS targets message id');
assert.ok(lesson.exercises.length >= 8, 'lesson includes many exercises');
assert.ok(lesson.lessonFlow.length >= 7, 'lesson includes full 90-minute guide flow');
assert.ok(lesson.vocabulary.some(v => v[0] === 'HTML'), 'vocabulary includes HTML');
assert.ok(lesson.vocabulary.some(v => v[0] === 'CSS'), 'vocabulary includes CSS');
assert.ok(lesson.vocabulary.some(v => v[0] === 'JavaScript'), 'vocabulary includes JavaScript');
assert.equal(lesson.mode, 'Real Blockly page builder', 'lesson 1 uses a real Blockly page builder');
assert.equal(lesson.realBlocklyBuilder, true, 'lesson 1 enables real Blockly workspace');
assert.ok(lesson.exercises.some(ex => ex.prompt.includes('גררו')), 'lesson 1 exercises require dragging blocks');

const lesson2 = lessons[1];
assert.equal(lesson2.durationMinutes, 90, 'lesson 2 is framed as 90 minutes');
assert.ok(lesson2.title.includes('סטודיו עיצוב'), 'lesson 2 focuses on real Blockly design studio');
assert.equal(lesson2.mode, 'Real Blockly design studio', 'lesson 2 uses real Blockly design studio mode');
assert.equal(lesson2.realBlocklyBuilder, true, 'lesson 2 enables real Blockly workspace');
assert.ok(lesson2.exercises.some(ex => ex.title.includes('Hover')), 'lesson 2 includes hover design exercise');
assert.ok(lesson2.exercises[0].title.includes('מתחילים פשוט'), 'lesson 2 starts simple before adding design blocks');
assert.equal(lesson2.exercises.length, 7, 'lesson 2 keeps only the non-redundant design exercises');
assert.ok(lesson2.vocabulary.some(v => v[0] === 'hover'), 'lesson 2 vocabulary includes hover');

const lesson3 = lessons[2];
assert.equal(lesson3.durationMinutes, 90, 'lesson 3 is framed as 90 minutes');
assert.equal(lesson3.title, 'כפתורים ופעולות קסם עם Blockly', 'lesson 3 title is clear and natural Hebrew');
assert.ok(lesson3.starter.html.includes('onclick="makeHappy()"'), 'lesson 3 has onclick event');
assert.ok(lesson3.starter.js.includes('classList.toggle("magic")'), 'lesson 3 includes classList toggle');
assert.ok(lesson3.exercises.length >= 8, 'lesson 3 includes many exercises');
assert.ok(!lesson3.exercises[0].prompt.includes('הרצה'), 'lesson 3 exercise 1 does not ask for a missing Run button');
assert.ok(lesson3.exercises[0].prompt.includes('כפתור “הפעילו קסם”') && lesson3.exercises[0].prompt.includes('בתצוגה החיה בצד שמאל'), 'lesson 3 exercise 1 points learners to the named live preview button');
assert.equal(lesson3.exercises[0].check.requiresPreviewButtonText, 'הפעילו קסם', 'lesson 3 exercise 1 requires clicking the preview magic button');
assert.ok(!lesson3.exercises[1].prompt.includes('הרצה'), 'lesson 3 exercise 2 does not ask for a missing Run button');
assert.equal(JSON.stringify(lesson3.exercises[1].check.changedBlocklyFields), JSON.stringify([{ type: 'web_button', field: 'MESSAGE', defaultValue: 'הכפתור הפעיל קסם 🎉' }]), 'lesson 3 exercise 2 requires changing the button message');
assert.equal(JSON.stringify(lesson3.exercises[1].check.unchangedBlocklyFields), JSON.stringify([{ type: 'web_button', field: 'LABEL', value: 'הפעילו קסם' }]), 'lesson 3 exercise 2 rejects changing the button label instead of message');
assert.ok(lesson3.exercises[1].check.unchangedFieldFeedback.includes('שיניתם את שם הכפתור'), 'lesson 3 exercise 2 gives accurate label-changed feedback');
assert.equal(lesson3.exercises[1].check.requiresPreviewButtonText, 'הפעילו קסם', 'lesson 3 exercise 2 requires trying the changed preview button');
assert.equal(lesson3.exercises[2].check.requiresCodePeek, true, 'lesson 3 exercise 3 requires opening generated code peek');
assert.equal(lesson3.exercises[2].check.requiresCodeSelectionTab, 'html', 'lesson 3 exercise 3 requires HTML generated-code selection');
assert.deepEqual(Array.from(lesson3.exercises[2].check.requiresCodeSelectionBlockTypes), ['web_button'], 'lesson 3 exercise 3 requires selecting the button block');
assert.equal(JSON.stringify(lesson3.exercises[3].check.changedBlocklyFields), JSON.stringify([{ type: 'web_action_message', field: 'TEXT', defaultValue: 'הכפתור הפעיל קסם 🎉' }]), 'lesson 3 exercise 4 requires changing the action-message text');
assert.equal(lesson3.exercises[3].check.requiresPreviewButtonText, 'הפעילו קסם', 'lesson 3 exercise 4 requires pressing the preview button after changing message');
assert.equal(lesson3.exercises[3].check.requiresPreviewMessageChangedFrom, 'כאן תופיע הודעה מהכפתור...', 'lesson 3 exercise 4 requires visible preview message change');
assert.ok(lesson3.exercises[3].check.blockFeedback.includes('חסר בלוק'), 'lesson 3 exercise 4 gives specific missing-action-block feedback');
assert.ok(lesson3.exercises[4].check.changedBlocklyFields?.some(rule => rule.type === 'web_action_emoji' && rule.field === 'EMOJI' && rule.defaultValue === '🤖'), 'lesson 3 exercise 5 requires changing the action emoji from default');
assert.equal(lesson3.exercises[4].check.requiresPreviewEmojiChangedFrom, '✨', 'lesson 3 exercise 5 requires the visible emoji to change in preview');
assert.ok(lesson3.exercises[5].check.changedBlocklyFieldsFromBaseline?.some(rule => rule.type === 'web_action_background' && rule.field === 'BG'), 'lesson 3 exercise 6 requires changing the background action from the entry baseline');
assert.equal(lesson3.exercises[5].check.ensureStarterBlocks?.[0]?.type, 'web_action_background', 'lesson 3 exercise 6 auto-adds the required background action block when missing');
assert.equal(lesson3.exercises[5].check.ensureStarterBlocks?.[0]?.after, 'web_button', 'lesson 3 exercise 6 inserts the background action after the button');
assert.equal(lesson3.exercises[5].check.exactBlockTypeCounts?.web_action_background, 1, 'lesson 3 exercise 6 rejects adding a second background action block');
assert.equal(lesson3.exercises[5].check.requiresPreviewButtonText, 'הפעילו קסם', 'lesson 3 exercise 6 requires pressing the preview button');
assert.equal(lesson3.exercises[6].check.requiresPreviewCardClass, 'magic', 'lesson 3 exercise 7 requires the preview card to enter magic mode');
assert.equal(lesson3.exercises[7].check.requiresCodeSelectionTab, 'js', 'lesson 3 exercise 8 requires selecting generated JavaScript');
assert.ok(lesson3.exercises[7].check.requiresCodeSelectionBlockTypes?.includes('web_action_emoji'), 'lesson 3 exercise 8 requires selecting an action block');
assert.ok(lesson3.exercises[3].check.fieldFeedback.includes('שנו את הטקסט'), 'lesson 3 exercise 4 gives specific unchanged-text feedback');
assert.ok(lesson3.vocabulary.some(v => v[0] === 'onclick'), 'lesson 3 vocabulary includes onclick');

const lessons4to24 = lessons.slice(3, 24);
lessons4to24.forEach(lessonItem => {
  assert.equal(lessonItem.realBlocklyBuilder, true, `lesson ${lessonItem.id} uses real draggable Blockly blocks`);
  assert.equal(lessonItem.blocklyLessonBuilder, true, `lesson ${lessonItem.id} uses the lesson-specific Blockly builder`);
  assert.equal(lessonItem.bridgeBlocks.length, 0, `lesson ${lessonItem.id} does not expose legacy helper/code-card buttons`);
  assert.ok(lessonItem.mode.includes('Real Blockly full rework'), `lesson ${lessonItem.id} is marked as a full real Blockly rework`);
  assert.ok(lessonItem.progressionStage.includes('בלוקים אמיתיים'), `lesson ${lessonItem.id} stays in the block-first phase`);
  assert.ok(lessonItem.blocklyBlocks.length >= 5, `lesson ${lessonItem.id} has several draggable lesson blocks`);
  assert.ok(lessonItem.blocklyBlocks.some(block => block.args0?.length), `lesson ${lessonItem.id} has editable fields/dropdowns inside lesson blocks`);
  assert.equal(lessonItem.exercises.length, lessonItem.id === 4 ? 7 : 8, `lesson ${lessonItem.id} has the reviewed exercise count`);
  lessonItem.exercises.forEach(ex => {
    assert.ok(ex.prompt.includes('בלוק') || ex.prompt.includes('תצוגה') || ex.prompt.includes('קוד שנוצר') || ex.prompt.includes('תיבת הקוד'), `lesson ${lessonItem.id} exercise ${ex.id} is phrased around blocks/preview/generated code`);
    assert.ok(ex.noCheck || (ex.check && Object.keys(ex.check).length > 0), `lesson ${lessonItem.id} exercise ${ex.id} has a validator or is explicitly no-check`);
  });
  assert.ok(!lessonItem.exercises[0].prompt.includes('הריצו'), `lesson ${lessonItem.id} exercise 1 is not a fake run-the-already-running-preview task`);
  assert.ok(lessonItem.exercises[0].check.blockTypes?.length, `lesson ${lessonItem.id} exercise 1 requires a real block action`);
  const blockChecks = lessonItem.exercises.filter(ex => ex.check.blockTypes?.length);
  assert.ok(blockChecks.length >= (lessonItem.id === 4 ? 5 : 6), `lesson ${lessonItem.id} requires connected Blockly blocks in most exercises`);
  const final = lessonItem.exercises.at(-1).check;
  if (lessonItem.id !== 4) {
    assert.equal(final.requiresCodePeek, true, `lesson ${lessonItem.id} final exercise requires generated-code peek`);
    assert.ok(final.requiresCodeSelectionBlockTypes?.length >= 1, `lesson ${lessonItem.id} final exercise requires selecting a connected generated-code block`);
  }
});

const lesson4 = lessons[3];
assert.equal(lesson4.durationMinutes, 90, 'lesson 4 is framed as 90 minutes');
assert.ok(lesson4.title.includes('קלט'), 'lesson 4 focuses on user input');
assert.ok(lesson4.title.includes('ברכות'), 'lesson 4 is framed as a fun personal generator');
assert.ok(lesson4.starter.html.includes('id="nameInput"'), 'lesson 4 has name input');
assert.ok(lesson4.starter.js.includes('.value'), 'lesson 4 reads input value');
assert.ok(lesson4.exercises[0].prompt.includes('גררו') && lesson4.exercises[0].check.blockTypes?.includes('lesson_4_name_label'), 'lesson 4 uses a draggable block for the first input-label change');
assert.ok(lesson4.exercises[1].check.blockTypes?.includes('lesson_4_topic_label'), 'lesson 4 uses a draggable block for the topic-label change');
assert.ok(lesson4.exercises[3].prompt.includes('לחצו על כפתור הברכה'), 'lesson 4 result-sentence exercise tells learners to press the preview button');
assert.equal(lesson4.exercises[3].check.requiresPreviewButtonClick, true, 'lesson 4 result-sentence exercise requires pressing the preview button');
assert.ok(lesson4.exercises[3].check.requiresPreviewResultFromBlockOutput?.some(rule => rule.type === 'lesson_4_sentence'), 'lesson 4 result-sentence exercise checks the preview result contains the generated sentence text');
const lesson4EndingBlock = lesson4.blocklyBlocks.find(block => block.type === 'lesson_4_result_word');
assert.equal(lesson4EndingBlock.label, 'אימוג׳י סיום בתוצאה', 'lesson 4 ending block is named for the emoji it changes');
assert.equal(lesson4EndingBlock.find, 'רעיונות נוצצים 🚀', 'lesson 4 ending block finds the actual starter result ending');
assert.equal(lesson4EndingBlock.replace, 'רעיונות נוצצים {{TEXT}}', 'lesson 4 ending block replaces the visible result ending');
assert.ok(lesson4.exercises[4].check.requiresPreviewResultFromBlockOutput?.some(rule => rule.type === 'lesson_4_result_word'), 'lesson 4 ending block exercise checks the visible preview result');
assert.equal(lesson4.exercises.length, 7, 'lesson 4 keeps the generated-code reading exercise plus optional challenge');
assert.equal(lesson4.exercises[5].check.requiresCodePeek, true, 'lesson 4 generated-code reading exercise requires opening code peek');
assert.ok(lesson4.exercises[5].check.jsIncludes?.includes('getElementById("nameInput").value'), 'lesson 4 generated-code reading exercise checks the nameInput value line exists');
assert.equal(lesson4.exercises.at(-1).optional, true, 'lesson 4 final challenge is optional/skippable');
assert.ok(['lesson_4_name_label','lesson_4_topic_label','lesson_4_button_text','lesson_4_sentence','lesson_4_result_word'].every(type => lesson4.exercises.at(-1).blocklyStarterXml?.includes(type)), 'lesson 4 optional challenge provides the full connected starter block program to fix');
assert.equal(lesson4.exercises.at(-1).check.exactBlocklyFields?.[0]?.value, '🎉', 'lesson 4 optional challenge checks the exact starter-block fix');
assert.ok(lesson4.vocabulary.some(v => v[0] === 'input'), 'lesson 4 vocabulary includes input');

const lesson5 = lessons[4];
assert.equal(lesson5.durationMinutes, 90, 'lesson 5 is framed as 90 minutes');
assert.ok(lesson5.title.includes('חידון'), 'lesson 5 focuses on quiz building');
assert.ok(lesson5.starter.html.includes("chooseAnswer('yes')"), 'lesson 5 uses fixed yes/no choices instead of free text');
assert.ok(!lesson5.starter.html.includes('answerInput'), 'lesson 5 avoids exact typed-answer matching');
assert.ok(lesson5.starter.js.includes('if (choice === "yes")'), 'lesson 5 includes a simple choice-based if condition');
assert.ok(lesson5.starter.js.includes('else'), 'lesson 5 includes else branch');
assert.ok(lesson5.blocklyBlocks.some(block => block.type === 'lesson_5_choice' && block.args0?.some(arg => JSON.stringify(arg.options || []).includes('no'))), 'lesson 5 has a Blockly dropdown that changes the correct yes/no choice');
assert.ok(lesson5.vocabulary.some(v => v[0] === 'if'), 'lesson 5 vocabulary includes if');
assert.ok(lesson5.vocabulary.some(v => v[0] === 'choice'), 'lesson 5 vocabulary names the user choice');

const lesson6 = lessons[5];
assert.equal(lesson6.durationMinutes, 90, 'lesson 6 is framed as 90 minutes');
assert.ok(lesson6.title.includes('ניקוד') || lesson6.title.includes('score'), 'lesson 6 focuses on scoring');
assert.ok(lesson6.starter.html.includes("chooseAnswer('yes')"), 'lesson 6 keeps scoring on fixed choices');
assert.ok(!lesson6.starter.html.includes('answerInput'), 'lesson 6 avoids typed-answer matching while teaching score');
assert.ok(lesson6.starter.js.includes('let score = 0'), 'lesson 6 initializes score');
assert.ok(lesson6.starter.js.includes('score = score + 1'), 'lesson 6 increments score');
assert.ok(lesson6.blocklyBlocks.some(block => block.type === 'lesson_6_plus'), 'lesson 6 has a Blockly block for score increment size');
assert.ok(lesson6.blocklyBlocks.some(block => block.type === 'lesson_6_reset_message' && block.find === 'איפוס ניקוד'), 'lesson 6 reset-label block matches the starter button text');

const lesson13 = lessons[12];
assert.ok(lesson13.title.includes('הקוד שנוצר'), 'lesson 13 starts the generated-code lab phase');
assert.ok(lesson13.progressionStage.includes('בלוקים אמיתיים'), 'lesson 13 remains block-first under the new progression requirement');
assert.ok(lesson13.blocklyBlocks.length >= 3, 'lesson 13 has generated-code Blockly cards');

const lesson19 = lessons[18];
assert.ok(lesson19.title.includes('כרטיסי HTML'), 'lesson 19 keeps the HTML-card focus');
assert.ok(lesson19.mode.includes('Real Blockly full rework'), 'lesson 19 now uses real Blockly card blocks');
assert.ok(lesson19.blocklyBlocks.some(block => block.label.includes('כותרת HTML')), 'lesson 19 exposes real HTML as draggable Blockly blocks');

const lesson24 = lessons[23];
assert.ok(lesson24.concept.includes('חוקי משחק'), 'lesson 24 edits game rules conceptually');
assert.ok(lesson24.blocklyBlocks.some(block => block.label.includes('פלט JavaScript')), 'lesson 24 has real JS Blockly cards');

const lesson25 = lessons[24];
assert.ok(lesson25.progressionStage.includes('כתיבה מודרכת'), 'lesson 25 starts guided coding');
assert.ok(!lesson25.bridgeBlocks?.length, 'guided coding phase reduces code-card scaffolding');

const lesson30 = lessons[29];
assert.ok(lesson30.title.includes('פרויקט סיום'), 'lesson 30 is the final project');
assert.ok(lesson30.concept.includes('HTML + CSS + JS'), 'lesson 30 combines HTML CSS and JS');

const hub = read('webcode.html');
assert.ok(hub.includes('WebCode Lab'), 'hub page exists');
assert.ok(hub.includes('webcode-play.html?lesson=1'), 'hub links to lesson 1');
assert.ok(hub.includes('webcode-slides.html?lesson=1'), 'hub links to guide slides');
assert.ok(hub.includes('25–30'), 'hub explains gradual move to real coding');
assert.ok(hub.includes('formatMixedText') && hub.includes('tech-term'), 'hub isolates English tech terms so RTL lesson cards do not flip mixed text');
assert.ok(hub.includes('js/webcode-lessons.js?v=20260819-course-v76'), 'hub bumps internal lesson-data script version to avoid stale course cards');
assert.ok(!hub.includes('Blockly אמיתי'), 'course-page hero avoids unclear “Blockly אמיתי” phrasing');
assert.ok(!JSON.stringify(lessons.slice(0, 3).map(lesson => lesson.concept)).includes('Blockly אמיתי'), 'visible course-card concepts avoid unclear “Blockly אמיתי” phrasing');

const play = read('webcode-play.html');
assert.ok(play.includes('repairSavedCodeState') && play.includes('function makeGreeting'), 'player repairs stale lesson 4 saved state when makeGreeting is missing');
assert.ok(play.includes('hasPreviewFilledInputs') && play.includes('hasPreviewResultFromInputs'), 'player can validate preview input/result interactions');
assert.ok(play.includes('blocklyLessonBuilder'), 'play page supports lesson-specific Blockly blocks for lessons 4-24');
assert.ok(play.includes('defineLessonBlocklyBlocks'), 'play page defines dynamic draggable lesson blocks');
assert.ok(play.includes('js/webcode-lessons.js?v=20260820-lesson4-reset-starter-v101'), 'play page bumps internal lesson data script for lesson 4 starter reset fix');
assert.ok(play.includes('function generateLesson4ChallengeCode') && play.includes('חסר בלוק'), 'lesson 4 challenge preview is generated from connected starter blocks, not the hidden lesson starter');
assert.ok(play.includes('applyExerciseBlocklyStarter(activeExercise)') && play.includes('blocklyStarterXml'), 'play page loads exercise-specific starter blocks into the Blockly workspace for debug-style challenges');
assert.ok(play.includes('if(ex?.blocklyStarterXml) return ex.blocklyStarterXml') && play.includes('delete checkMemory.exerciseBaselines[activeExercise]'), 'starter-code reset uses the current exercise starter XML instead of stale/blank baseline state');
assert.ok(play.includes('hasExactBlocklyFields') && play.includes('exactBlocklyFields'), 'play page can validate exact Blockly field values for specific challenges');
assert.ok(play.includes('ex.optional') && play.includes('דלגו וסיימו'), 'play page lets optional final challenges be skipped');
assert.ok(play.includes("$('topRunButton').style.display = lesson.realBlocklyBuilder ? 'none' : ''"), 'top run button is hidden for auto-running Blockly lessons');
assert.ok(play.includes('if(lesson.blocklyLessonBuilder) return;') && play.includes('x="130" y="70"'), 'lesson-specific Blockly lessons keep starter block placed comfortably instead of pushed to the far right');
assert.ok(play.includes('hasGeneratedBlockOutputs') && play.includes('generatedBlockOutputs'), 'checks can require the selected lesson-block field value to appear in generated code');
assert.ok(play.includes('hasAnyChangedBlocklyField') && play.includes('anyChangedBlocklyFields'), 'checks can require at least one edited block field when the prompt says to change one block');
assert.ok(play.includes('hasPreviewButtonClick') && play.includes('requiresPreviewButtonClick'), 'checks can require pressing a preview button for visible-result exercises');
assert.ok(play.includes('hasPreviewResultFromBlockOutput') && play.includes('requiresPreviewResultFromBlockOutput'), 'checks can require the preview result to include the generated output from a block');
assert.ok(!play.includes('בחרו תרגול, שנו קוד ולחצו הרצה.'), 'exercise feedback no longer tells auto-running Blockly learners to press run');
assert.ok(play.includes('textarea id="htmlCode"'), 'play page has HTML editor');
assert.ok(play.includes('textarea id="cssCode"'), 'play page has CSS editor');
assert.ok(play.includes('textarea id="jsCode"'), 'play page has JS editor');
assert.ok(play.includes('.btn:disabled') && play.includes('cursor:not-allowed') && play.includes('grayscale'), 'disabled Continue button is visually muted and cannot look available');
assert.ok(play.includes('לראות קוד שנוצר'), 'play page has explicit generated-code button');
assert.ok(play.includes('showGeneratedCode'), 'play page can open generated code panel for students');
assert.ok(play.includes("if(lesson.realBlocklyBuilder){\n        $('htmlCode').value = saved.html || '';"), 'real Blockly lessons do not briefly show legacy starter code before blocks generate');
assert.ok(play.includes('if(!lesson.realBlocklyBuilder) runCode();'), 'real Blockly lessons skip the legacy starter-code preview during init');
assert.ok(play.includes('<bdi>${lesson.id}</bdi>'), 'top lesson title keeps lesson number/colon in correct RTL order');
assert.ok(play.includes('iframe id="preview"'), 'play page has live preview');
assert.ok(play.includes('lessonPanel'), 'play page wraps lesson text in a collapsible panel');
assert.ok(play.includes('compact-info') && play.includes('id="story" hidden') && play.includes('id="mission" hidden'), 'lesson intro stays compact so exercises remain visible');
assert.ok(play.includes('toggleLessonPanel'), 'play page can collapse and expand lesson instructions');
assert.ok(play.includes('aria-expanded'), 'collapsible lesson panel is accessible');
assert.ok(play.includes('lessonToggleIcon') && play.includes('⌃') && play.includes('⌄'), 'collapse toggle uses standard chevron icons instead of plus/minus');
assert.ok(play.includes('lesson-collapsed'), 'collapsing instructions reallocates space to Blockly and preview sections');
assert.ok(play.includes('previewResize') && play.includes('--preview-width'), 'preview panel has a draggable width resizer');
assert.ok(play.includes('webcodePreviewWidth') && play.includes('pointermove'), 'preview width drag persists and handles pointer movement');
assert.ok(play.includes('webcodeLessonState:v2') && play.includes('saveLessonState') && play.includes('restoreProgress'), 'lesson progress and code persist across page refreshes');
assert.ok(play.includes('blocklyXml') && play.includes('workspaceToDom') && play.includes('saved.blocklyXml || webBuilderStarterXml()'), 'real Blockly workspace persists across page refreshes');
assert.ok(play.includes('stateReady = true; saveLessonState();'), 'initial restore does not overwrite saved work before Blockly loads');
assert.ok(play.includes('Blockly.svgResize'), 'layout changes resize Blockly after layout change');
assert.ok(play.includes('alignBlocklyStarterBlocksRight'), 'starter Blockly program is aligned to the right side of the workspace');
assert.ok(play.includes('safeRightEdge') && play.includes('blocklyToolboxCategoryGroup'), 'starter blocks align to free workspace edge without overlapping toolbox');
assert.ok(play.includes('checkExercise()'), 'play page has exercise checking');
assert.ok(play.includes('function isStarterStructureLockedExercise(){ return lesson.id === 3 && (activeExercise <= 2 || activeExercise === 6); }'), 'lesson 3 starter exercises and background-change exercise lock starter block structure');
assert.ok(play.includes('checkMemory.starterLockBaselines') && play.includes('starterChainBlocks().map(block => block.id)'), 'locked exercises snapshot the starter chain block ids');
assert.ok(play.includes('blocklyWorkspace.getTopBlocks(false).forEach(setBlockTreeFree)') && play.includes('setStarterBlockLock(block, baselineIds.has(block.id))'), 'locked exercises lock only the starter baseline blocks, not newly added blocks');
assert.ok(play.includes('detachBlocksConnectedAfterStarterBaseline'), 'locked exercises detach newly added blocks connected into the starter chain');
assert.ok(play.includes('ensureExerciseBaseline(activeExercise);'), 'direct-open exercise 6 captures its baseline after Blockly loads');
assert.ok(!play.includes('setBlockTreeStructureLock'), 'old recursive lock-all helper is removed');
assert.ok(play.includes('activeExercise === 2 && block.type === \'web_button\' && name === \'MESSAGE\''), 'lesson 3 exercise 2 unlocks only the button message field');
assert.ok(play.includes('activeExercise === 6 && block.type === \'web_action_background\' && name === \'BG\''), 'lesson 3 exercise 6 unlocks only the existing background-action dropdown');
assert.ok(play.includes('hasExactBlockTypeCounts(c.exactBlockTypeCounts)'), 'player supports rejecting added duplicate blocks when an exercise must change a starter block');
assert.ok(play.includes('ensureRequiredStarterBlocks(id)') && play.includes('connectNewBlockInChain(block, rule.after)'), 'locked starter-change exercises add required blocks only when missing and connect them into the code chain');
assert.ok(play.includes('ensureRequiredStarterBlocks(activeExercise);') && play.includes('ensureExerciseBaseline(id)') && play.includes("'web_action_background.BG': firstBlocklyFieldValue('web_action_background', 'BG')"), 'lesson 3 exercise 6 inserts missing required block before capturing the user workspace as the entry baseline');
assert.ok(play.includes('hasChangedBlocklyFieldsFromBaseline(c.changedBlocklyFieldsFromBaseline)') && play.includes('exerciseResetXml()'), 'lesson 3 exercise 6 checks/resets against the entry baseline, not lesson starter XML');
assert.ok(play.includes('field.setEnabled(enabled)') && !play.includes('setEditable?.(!locked)'), 'lesson 3 field lock uses field enable state, not blanket block edit lock');
assert.ok(play.includes('resetStarterBlocksOnly') && play.includes('↺ קוד התחלה'), 'lesson 3 exercise 2 has a starter-code reset button');
assert.ok(play.includes('previewClicks.push({ exerciseId:activeExercise') && play.includes('click.exerciseId === activeExercise'), 'preview button clicks are tracked per current exercise');
assert.ok(play.includes('emojiText:emoji?String(emoji.textContent') && play.includes('hasPreviewEmojiChanged'), 'player can require visible emoji changes in the preview');
assert.ok(play.includes('cardClass:card?String(card.className') && play.includes('hasPreviewCardClass'), 'player can require visible class toggles in the preview');
assert.ok(play.includes('goCourseHome') && play.includes("location.href = 'webcode.html'") && play.includes('חזרה לעמוד הקורס'), 'last exercise Continue clearly goes back to the WebCode course home after completion');
assert.ok(play.includes('completedTitle'), 'check button keeps success feedback visible after checking');
assert.ok(!/function checkExercise\(\)[\s\S]*?runCode\(\);[\s\S]*?renderProgress\(\); saveLessonState\(\); \}/.test(play), 'check button does not rerun/reset the live preview after click-result exercises');
assert.ok(play.includes('exercise-bottom') && play.includes('exercise-feedback'), 'check/run feedback is shown next to the exercise controls, not over the preview');
assert.ok(play.includes('.exercise-actions-main{display:flex;gap:.55rem;flex-wrap:wrap}') && play.includes('.starter-reset-row{display:flex;justify-content:flex-start}'), 'lesson 3 exercise 2 uses normal controls with starter reset below Back');
assert.ok(play.includes('<div class="starter-reset-row">${starterResetButton}</div>'), 'starter-code reset is placed below the Back button row');
assert.ok(!play.includes('exercise-meta">${esc(ex.minutes)}'), 'exercise cards do not show internal minute ranges');
assert.ok(!play.includes('<div class="feedback" id="feedback">בחרו תרגול, שנו קוד ולחצו הרצה.</div>'), 'feedback is not placed at the bottom of the preview panel where the bug-report button can cover it');
assert.ok(play.includes('webcode-error'), 'play page catches preview JavaScript errors');
assert.ok(play.includes('debugHint'), 'play page gives student-friendly syntax/debug hints');
assert.ok(play.includes('validateJavaScriptSyntax'), 'play page validates JavaScript syntax before preview injection');
assert.ok(play.includes('שגיאת סינטקס ב־JavaScript'), 'play page shows Hebrew syntax error feedback');
assert.ok(play.includes('https://unpkg.com/blockly/blockly.min.js'), 'play page loads real Blockly');
assert.ok(play.includes('Blockly.inject'), 'play page injects a real Blockly workspace');
assert.ok(play.includes("$('blocksIntro').style.display = 'none'"), 'real Blockly lessons hide the redundant intro above the workspace');
assert.ok(play.includes("$('blocksStage').classList.add('real-blockly-stage')") && play.includes('.blocks-stage.real-blockly-stage{padding:0;gap:0}'), 'real Blockly workspace removes the orange barrier and fills the panel');
assert.ok(play.includes('defineWebBuilderBlocks'), 'play page defines draggable Web builder blocks');
assert.ok(play.includes('webBuilderToolbox'), 'play page exposes a Blockly toolbox');
assert.ok(play.includes('web_card_shape') && play.includes('web_hover'), 'play page defines design studio blocks for lesson 2');
assert.ok(play.includes('hasButton') && play.includes('cssParts'), 'generated CSS only includes styles for blocks students added');
assert.ok(play.includes('סטודיו עיצוב'), 'play page toolbox includes design studio category');
assert.ok(play.includes('סטודיו פעולה'), 'play page toolbox includes action studio category for lesson 3');
assert.ok(play.includes('web_action_message') && play.includes('web_action_emoji') && play.includes('web_action_background') && play.includes('web_action_magic'), 'play page defines action studio blocks for lesson 3');
assert.ok(play.includes('classList.toggle("magic")') && play.includes('document.body.style.background'), 'lesson 3 action blocks generate real JavaScript actions');
assert.ok(play.includes('generateCodeFromBlockly'), 'play page generates HTML/CSS/JS from connected Blockly blocks');
assert.ok(play.includes('highlightGeneratedCodeForBlock'), 'selecting a Blockly block highlights its generated code');
assert.ok(play.includes('codeTargetForBlock'), 'play page maps block types to generated code snippets');
assert.ok(play.includes('setSelectionRange'), 'generated code highlight selects the relevant text in the editor');
assert.ok(play.includes('shareProject'), 'play page can create a share link for the student project');
assert.ok(play.includes('navigator.clipboard.writeText(shareUrl)'), 'share button copies only the public link');
assert.ok(play.includes('הקישור הציבורי הועתק'), 'share button confirms the public link was copied');
assert.ok(!play.includes('navigator.share'), 'share button does not open native share UI');
assert.ok(play.includes('🏠 עמוד הקורס'), 'top course-home button is clearly named');
assert.ok(play.includes('webcode-share.html'), 'play page shares to a clean viewer page');
assert.ok(play.includes('renderBridgeBlocks'), 'play page keeps bridge blocks fallback for any legacy lessons outside 4-24');
assert.ok(play.includes('applyBridgeBlock'), 'play page can still apply bridge blocks if needed outside the block-first range');

const shared = read('webcode-share.html');
assert.ok(shared.includes('עמוד משותף'), 'shared project viewer page exists');
assert.ok(shared.includes('decodeSharePayload'), 'shared project viewer decodes link payload');
assert.ok(shared.includes('sandbox="allow-scripts"'), 'shared project viewer isolates student code in sandboxed iframe');
assert.ok(shared.includes('לבנות עמוד משלי'), 'shared project viewer invites friends to build their own page');

const slides = read('webcode-slides.html');
assert.ok(slides.includes('מהלך שיעור 90 דקות'), 'slides include 90-minute flow');
assert.ok(slides.includes('רצף תרגולים לשיעור'), 'slides include exercise sequence');
assert.ok(slides.includes('שימוש נכון ב־AI'), 'slides include AI guidance');

const grade4 = read('holon-scope-grade4.html');
assert.ok(grade4.includes('webcode.html'), 'grade 4 page links to WebCode hub');
assert.ok(grade4.includes('webcode-play.html?lesson=1'), 'grade 4 page links to first lesson');

console.log('webcode-course tests passed');
