const ROBLOX_LESSONS = [
  {id:1,title:'היכרות עם Roblox Studio והוספת עצמים',unit:'משחק המדרגות המעופפות',product:'עולם Baseplate עם SpawnLocation, חלקים ושמות מסודרים',concept:'Studio, Workspace, Explorer, Properties, Move/Scale/Rotate, צירי X/Y/Z',studio:['פותחים Baseplate חדש','מוודאים ש־Explorer, Properties ו־Output פתוחים','מוסיפים SpawnLocation ומבינים שהוא מופיע תחת Workspace','מוסיפים Parts, משנים מיקום, גודל, סיבוב ושם','מארגנים כמה משטחי שיגור בתיקייה'],properties:['Name','Position','Size','Orientation','Parent'],code:['-- שיעור 1: אין חובה לכתוב Script','-- בדיקת Output ראשונה, אם רוצים להתנסות:','print("Roblox Studio is ready!")'],practice:['הזיזו SpawnLocation לגובה אחר והריצו Play','צרו 3 משטחי שיגור בגבהים שונים','הוסיפו Block ו־Sphere, שנו שם, גודל וסיבוב','הכניסו עצמים קשורים לתיקייה בעזרת Ctrl+G'],teacher:'לוודא שכל תלמיד מבין איפה רואים עצם בעולם ואיפה הוא מופיע ב־Explorer. לעצור על ההבדל בין Workspace לבין מה שרואים במסך.',check:['אני יודע לפתוח Baseplate','אני יודע למצוא Workspace','אני יודע להזיז, לסובב ולהגדיל Part','אני יודע לשנות Name ב־Properties']},
  {id:2,title:'תכונות חלקים ובניית מסלול מכשולים',unit:'משחק המדרגות המעופפות',product:'Obby בסיסי עם בלוקים, צבעים, חומרים וחלקים שאפשר/אי אפשר להתנגש בהם',concept:'Anchored, CanCollide, Color, BrickColor, Material, Transparency',studio:['בונים Part באוויר ומריצים כדי לראות שהוא נופל','מפעילים Anchored כדי להשאיר חלק במקום','משנים CanCollide כדי ליצור בלוקים “מטעים” במסלול','משנים צבע, חומר ושקיפות','בונים התחלה של מסלול מכשולים'],properties:['Anchored','CanCollide','BrickColor','Color','Material','Transparency'],code:['-- שיעור 2: התכונות נלמדות דרך Properties','-- בהמשך אפשר לשנות את אותן תכונות דרך Script:','local part = workspace.Part','part.Anchored = true','part.CanCollide = false','part.Transparency = 0.3'],practice:['צרו מסלול מכשולים עם לפחות 8 חלקים','בחרו 3 בלוקים שהשחקן ייפול דרכם: CanCollide = false','שנו Material וצבע לכל אזור במסלול','נסו ערכי Transparency שונים: 0, 0.3, 0.8'],teacher:'זה שיעור מצוין לשאלות ניבוי: מה יקרה אם Anchored כבוי? מה יקרה אם CanCollide כבוי אבל החלק באוויר?',check:['אני יודע להסביר מה עושה Anchored','אני יודע להסביר מה עושה CanCollide','אני יודע לשנות צבע וחומר','בניתי התחלה של Obby']},
  {id:3,title:'שלט כניסה, GUI ויחסי Parent/Child',unit:'משחק המדרגות המעופפות',product:'שלט כניסה מעוצב עם SurfaceGui ו־TextLabel',concept:'SurfaceGui, TextLabel, AnchorPoint, Position, Size, Parent/Child',studio:['משנים את Baseplate לחומר וצבע שמתאימים לעולם','יוצרים Part בשם Sign','מוסיפים לתוך Sign רכיב SurfaceGui','מוסיפים TextLabel לתוך ה־SurfaceGui','מעצבים Text, Font, TextColor, TextSize, Size ו־BackgroundTransparency'],properties:['Text','Font','TextColor','TextSize','AnchorPoint','Position','Size','BackgroundTransparency'],code:['-- שיעור 3: מבנה האובייקטים לפני קוד','-- Workspace > Sign > SurfaceGui > TextLabel','local label = workspace.Sign.SurfaceGui.TextLabel','label.Text = "Welcome to my obby!"','label.TextSize = 48'],practice:['כתבו הודעת פתיחה לשחקנים','מקמו את הטקסט במרכז השלט עם AnchorPoint ו־Position','הגדילו את התווית עם Size','העלימו את רקע התווית בעזרת BackgroundTransparency'],teacher:'להדגיש שה־Sign הוא Parent, וה־SurfaceGui/TextLabel הם Children. זו הכנה חשובה מאוד לכתיבת הפניות בקוד בשיעור הבא.',check:['אני יודע להוסיף SurfaceGui לחלק','אני יודע להוסיף TextLabel','אני יודע להסביר Parent ו־Child','יצרתי שלט כניסה מעוצב']},
  {id:4,title:'הפניות לאובייקטים וצעדים ראשונים ב־Luau',unit:'משחק המדרגות המעופפות',product:'Script שמדפיס ומשנה תכונה של אובייקט',concept:'Script, print, game.Workspace, references',studio:['מוסיפים Script','פותחים Output','מריצים print ראשון','יוצרים הפניה לאובייקט ב־Workspace','משנים תכונה דרך קוד'],properties:['Name','BrickColor','Transparency'],code:['print("Hello Roblox")','local part = game.Workspace.Part','part.Transparency = 0.5'],practice:['הדפיסו הודעה ל־Output','צרו הפניה לחלק בשם Sign','שנו צבע או שקיפות בעזרת קוד'],teacher:'להקפיד על שמות אובייקטים באנגלית וללא רווחים כדי שההפניות יהיו פשוטות.'},
  {id:5,title:'משתנים ושמירת הפניות',unit:'משחק המדרגות המעופפות',product:'קוד מסודר עם משתנים לאובייקטים ולערכים',concept:'variables, string, number, boolean, object reference',studio:['יוצרים משתנה לחלק','יוצרים משתנה למספר','יוצרים משתנה לטקסט','יוצרים משתנה בוליאני','משתמשים במשתנים כדי לשנות עולם'],properties:['Name','Value'],code:['local sign = game.Workspace.Sign','local speed = 10','local message = "Welcome"','local isOpen = true'],practice:['שמרו הפניה לשלט במשתנה','שמרו צבע/מספר/טקסט במשתנים','השתמשו במשתנה כדי לשנות TextLabel']},
  {id:6,title:'תנאים וקבלת החלטות',unit:'משחק המדרגות המעופפות',product:'Script שמגיב אחרת לפי מצב',concept:'if, then, else, comparison',studio:['בודקים ערך של משתנה','מריצים if בסיסי','מוסיפים else','משנים תכונה לפי החלטה'],properties:['Transparency','CanCollide'],code:['local isOpen = false','if isOpen then','    print("Open")','else','    print("Closed")','end'],practice:['צרו תנאי שבודק אם דלת פתוחה','שנו CanCollide לפי מצב','הדפיסו הודעה שונה לכל מצב']},
  {id:7,title:'פונקציות חלק א',unit:'משחק המדרגות המעופפות',product:'פונקציה שמבצעת פעולה חוזרת',concept:'function, call',studio:['מגדירים פונקציה','קוראים לפונקציה','מעבירים פעולה חוזרת לקוד מסודר'],properties:['Name'],code:['local function showWinner()','    print("Winner!")','end','','showWinner()'],practice:['צרו פונקציה שמדפיסה הודעת ניצחון','קראו לה כמה פעמים','הכניסו לתוכה שינוי בשלט']},
  {id:8,title:'פונקציות חלק ב — ארגומנטים',unit:'משחק המדרגות המעופפות',product:'פונקציה שמקבלת ערך ומשתמשת בו',concept:'parameters, arguments',studio:['מוסיפים פרמטר לפונקציה','שולחים ערך בקריאה','משתמשים בערך בתוך הפונקציה'],properties:['Text'],code:['local function setSignText(text)','    print(text)','end','','setSignText("Welcome")'],practice:['צרו פונקציה שמשנה טקסט בשלט','שלחו אליה הודעות שונות','השתמשו בה כדי לעדכן מנצח']},
  {id:9,title:'אירועים וחיבור פעולה לנגיעה',unit:'משחק המדרגות המעופפות',product:'אובייקט שמפעיל פונקציה כשנוגעים בו',concept:'events, Touched, Connect',studio:['מזהים אירוע מתאים','מחברים פונקציה ל־Touched','מדפיסים מי נגע','מתחילים להציג מנצח על שלט'],properties:['Touched'],code:['local part = script.Parent','part.Touched:Connect(function(hit)','    print("Touched")','end)'],practice:['חברו Touched לחלק סוף המסלול','הדפיסו הודעת ניצחון','נסו לזהות מה נגע בחלק']},
  {id:10,title:'מציאת מנצח ו־Toolbox',unit:'משחק המדרגות המעופפות',product:'שלט שמציג מנצח ושימוש מבוקר ב־Toolbox',concept:'winner display, toolbox assets',studio:['משלימים פונקציית מנצח','מעדכנים TextLabel','מכירים Toolbox','בודקים מודלים לפני שימוש'],properties:['Text','Parent'],code:['local label = workspace.Sign.SurfaceGui.TextLabel','label.Text = "Winner!"'],practice:['עדכנו את השלט כאשר שחקן מגיע לסוף','הוסיפו מודל מה־Toolbox בצורה מבוקרת','בדקו שהמודל לא שובר את המשחק']},
  {id:11,title:'כתיבת סיפורים — קלט מהשחקן',unit:'כתיבת סיפורים ב־Luau',product:'סיפור שמתחיל מתשובה של שחקן',concept:'questions, input idea, strings',studio:['שואלים שאלה','שומרים תשובה','משלבים תשובה במשפט'],properties:['Text'],code:['local name = "Noa"','local sentence = "Hello " .. name','print(sentence)'],practice:['כתבו משפט עם שם שחקן','חברו כמה מחרוזות','הציגו משפט ב־Output']},
  {id:12,title:'הדפסת הסיפור והרחבת שאלות',unit:'כתיבת סיפורים ב־Luau',product:'סיפור קצר שמודפס בשלבים',concept:'string concatenation, sequence',studio:['מוסיפים כמה שאלות','בונים משפטים','מדפיסים סיפור שלם'],properties:['Text'],code:['local hero = "Robot"','local place = "Forest"','print(hero .. " went to " .. place)'],practice:['צרו 3 משתנים לסיפור','חברו אותם למשפט אחד','הדפיסו התחלה/אמצע/סוף']},
  {id:13,title:'בחירת המשך לסיפור',unit:'כתיבת סיפורים ב־Luau',product:'סיפור עם מסלולים שונים',concept:'conditions in stories',studio:['מוסיפים בחירה','בודקים תנאי','מדפיסים המשך שונה'],properties:['Text'],code:['local choice = "left"','if choice == "left" then','    print("You found a cave")','else','    print("You found a bridge")','end'],practice:['צרו שתי בחירות לסיפור','כתבו המשך לכל בחירה','הוסיפו סוף שונה']},
  {id:14,title:'התחלת משחק המדורה',unit:'משחק המדורה',product:'עיצוב חלקי משחק ופונקציית PickUp ראשונה',concept:'game rules, PickUp function',studio:['מסבירים חוקי משחק','מעצבים עצים/חלקים לאיסוף','מתחילים פונקציה לאיסוף'],properties:['Name','Anchored'],code:['local function pickUp()','    print("Picked up")','end'],practice:['צרו חלקים לאיסוף','כתבו פונקציה בסיסית','חברו אותה לאירוע מתאים']},
  {id:15,title:'סיום הרמת מקל וזיהוי שחקן',unit:'משחק המדורה',product:'איסוף שמוודא שמי שנגע הוא שחקן',concept:'humanoid, character detection',studio:['מקבלים את החלק שנגע','מחפשים Humanoid','מפעילים איסוף רק לשחקן'],properties:['Parent'],code:['local humanoid = hit.Parent:FindFirstChild("Humanoid")','if humanoid then','    print("Player touched")','end'],practice:['בדקו האם לנוגע יש Humanoid','מנעו איסוף מחפצים רגילים','הדפיסו הודעה רק לשחקן']},
  {id:16,title:'פונקציות גלובליות',unit:'משחק המדורה',product:'פונקציה משותפת לכמה Scripts',concept:'global/shared functions',studio:['מזהים פעולה שחוזרת בכמה מקומות','מעבירים אותה לפונקציה משותפת','משתמשים בה מכמה Scripts'],properties:['Script organization'],code:['-- דוגמה רעיונית: פונקציה משותפת לאיסוף','_G.pickUp = function()','    print("global pickup")','end'],practice:['זהו קוד שחוזר על עצמו','הפכו אותו לפונקציה','קראו לפונקציה מכמה מקומות']},
  {id:17,title:'עבודה עם Instance',unit:'משחק המדורה',product:'יצירת אובייקט חדש דרך קוד',concept:'Instance.new, Parent',studio:['יוצרים אובייקט דרך קוד','נותנים לו Parent','משנים לו תכונות'],properties:['Parent','Name','Position'],code:['local part = Instance.new("Part")','part.Name = "Wood"','part.Parent = workspace'],practice:['צרו Part דרך קוד','שנו לו שם וצבע','מקמו אותו בעולם']},
  {id:18,title:'טבלת ניקוד',unit:'משחק המדורה',product:'שמירת ניקוד לשחקנים',concept:'tables, players, score',studio:['מבינים צורך בניקוד לכל שחקן','יוצרים טבלה','מעדכנים ערך בטבלה'],properties:['Value'],code:['local scores = {}','scores["Player1"] = 0','scores["Player1"] += 1'],practice:['צרו טבלת scores','הוסיפו שחקן','עדכנו ניקוד אחרי איסוף']},
  {id:19,title:'עדכון ערכי הטבלה ומאגר מידע',unit:'משחק המדורה',product:'ניהול חפצים שנאספו',concept:'tables as data store',studio:['שומרים אילו חפצים נאספו','מעדכנים טבלה','קוראים ערכים מהטבלה'],properties:['Value'],code:['local inventory = {}','table.insert(inventory, "Wood")','print(#inventory)'],practice:['צרו inventory','הוסיפו אליו חפצים','הדפיסו כמה נאסף']},
  {id:20,title:'הדלקת המדורה',unit:'משחק המדורה',product:'מדורה שמופעלת לאחר איסוף מספיק חפצים',concept:'state, conditions, visual feedback',studio:['בונים מדורה','בודקים כמה עצים נאספו','משנים תצוגה כשהתנאי מתקיים'],properties:['Transparency','Color','Material'],code:['if woodCount >= 3 then','    fire.Transparency = 0','end'],practice:['צרו תנאי להדלקה','שנו צבע/שקיפות של אש','הציגו הודעה כשהמדורה דולקת']},
  {id:21,title:'מיקומים רנדומליים וצירי X/Y/Z',unit:'משחק המדורה',product:'חלקים שמופיעים במקומות אקראיים',concept:'random, Vector3, 3D coordinates',studio:['מסבירים X/Y/Z','יוצרים מיקום אקראי','ממקמים חלק במרחב'],properties:['Position'],code:['local x = math.random(-20, 20)','local z = math.random(-20, 20)','part.Position = Vector3.new(x, 5, z)'],practice:['צרו מיקום אקראי','הגבילו את אזור ההופעה','בדקו שהחלק מופיע בגובה מתאים']},
  {id:22,title:'ממשק גרפי למשחק',unit:'משחק המדורה',product:'GUI שמציג כמה חפצים נאספו',concept:'ScreenGui, TextLabel, UI update',studio:['יוצרים ScreenGui','מוסיפים TextLabel','מעדכנים טקסט לפי ניקוד'],properties:['Text','Size','Position'],code:['label.Text = "Wood: " .. woodCount'],practice:['צרו תווית ניקוד','עדכנו אותה לאחר איסוף','מקמו אותה בפינת המסך']},
  {id:23,title:'סיום משחק המדורה',unit:'משחק המדורה',product:'משחק מדורה שלם עם GUI וסיום',concept:'game end, UI script',studio:['מחברים איסוף, טבלה, מדורה ו־GUI','מוסיפים מצב סיום','מציגים הודעת ניצחון'],properties:['Text','Visible'],code:['if woodCount >= target then','    label.Text = "Fire is ready!"','end'],practice:['הגדירו יעד איסוף','הציגו הודעת סיום','בדקו את המשחק מתחילה ועד סוף']},
  {id:24,title:'חזרה וסיכום פרויקט',unit:'סיכום',product:'שיפור, בדיקה והצגת משחק',concept:'review, debugging, presentation',studio:['חוזרים על Studio ו־Properties','חוזרים על variables/functions/events/tables','מתקנים באגים','מציגים משחק לחברים'],properties:['All learned properties'],code:['-- בחרו קטע קוד אחד מהפרויקט והסבירו אותו במילים'],practice:['תקנו באג אחד במשחק','שפרו עיצוב אחד','הציגו לחבר מה הקוד שלכם עושה']}
];

if (typeof window !== 'undefined') window.ROBLOX_LESSONS = ROBLOX_LESSONS;
